### ISSUE TITLE
VSCode extension only work on unocss.config.ts

### ISSUE THREAD

**Issue by joseehilton147** [unocss/unocss#3292] opened 2023-10-31 02:50 UTC
### UnoCSS version

0.57.1

### Describe the bug

![image](https://github.com/unocss/unocss/assets/53986027/0f7a79ef-e69a-4310-909a-cc030157c561)

outside config file:
![image](https://github.com/unocss/unocss/assets/53986027/bf283641-468c-4d6d-9919-3999b52b7a2c)

ive researched the issues trying to find anything related, downgrade extension version but seems to not work, i only have unocss extension with voltar enabled.

As a test i turn the windicss extension on and the classes name shows

### Reproduction

dont know how to make a reproduction

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2023-10-31 02:57
Please provide a minimal repo that can reproduce the problem

**Comment by joseehilton147** [comment] 2023-10-31 12:38
> Please provide a minimal repo that can reproduce the problem

as i said, i dont know how to reproduce a vs code ambient, extension only work for uno config file on nuxt 3.8

**Comment by Simon-He95** [comment] 2023-10-31 13:34
> > Please provide a minimal repo that can reproduce the problem
> 
> as i said, i dont know how to reproduce a vs code ambient, extension only work for uno config file on nuxt 3.8

You can copy your code to create a repo, then delete the code to leave only one page and reproduce the problem.

**Comment by antfu** [comment] 2023-11-03 15:48
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-03 15:48 UTC
Labels: needs reproduction
