### ISSUE TITLE
Allow variablePrefix to be disabled

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#2085] opened 2023-01-16 21:02 UTC
Please allow me to pass `false` to the `variablePrefix` to fully remove the `un-` prefix from all generated custom css properties. An empty string doesn't work right now due to the `.length` check in the transformer

**Comment by zyyv** [comment] 2023-01-17 04:08
Is this duplicate of #2084 ? I had send a PR(#2086) to resovle it. `un-` is our default `variablePrefix`, it should have little effect on you.

**Comment by UltraCakeBakery** [comment] 2023-01-17 07:50
It is not a duplicate. This is a feature request, as where my other issue is a bug report. It is not hindering me at all, but since i dont use any other custom properties, the suffix is unnecessary. Now i just use a non width space character lol

**Closed** 2023-01-25 11:33 UTC

**Comment by UltraCakeBakery** [comment] 2023-01-25 20:34
Thank you all for making this possible! <3
