### ISSUE TITLE
[vscode]: Unable to recognize special class `!<className>` in `style` sfc tag

### ISSUE THREAD

**Issue by tachibana-shin** [unocss/unocss#3323] opened 2023-11-09 04:09 UTC
### UnoCSS version

any

### Describe the bug

As you can see that if in the `<style>` sfc code block I use `@apply` I need an escape character `` and unocss cannot detect it

![image](https://github.com/unocss/unocss/assets/45375496/e90bf858-69e5-4f1d-9d5a-994d5d9267b8)

### Reproduction

This does not require complex reconstruction:
```vue
<template>
  <div>hello world</div>
</template>

<style lang="scss" scoped>
div {
  @apply \!bg-pink-400
}
</style>
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2023-11-09 06:32
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

[Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by tachibana-shin** [comment] 2023-11-09 06:50
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

This is the problem with UnoCSS extension in vscode how do i reproduce the editor problem with my repo?

**Comment by Simon-He95** [comment] 2023-11-09 07:18
` @apply !bg-pink-400`
<img width="900" alt="image" src="https://github.com/unocss/unocss/assets/57086651/0b145dcd-46cf-4375-b815-dfa7f16fab07">

**Comment by tachibana-shin** [comment] 2023-11-09 07:39
> ` @apply !bg-pink-400` <img alt="image" width="900" src="https://user-images.githubusercontent.com/57086651/281648008-0b145dcd-46cf-4375-b815-dfa7f16fab07.png">

i don't know if vue-compiler can pick up `!bg-pink-400` but if using `<style lang='scss'>` then `scss` cannot resolve this syntax and needs escape character `!bg-pink-400`

**Comment by henrikvilhelmberglund** [comment] 2023-11-09 08:06
> > ` @apply !bg-pink-400` <img alt="image" width="900" src="https://user-images.githubusercontent.com/57086651/281648008-0b145dcd-46cf-4375-b815-dfa7f16fab07.png">
> 
> i don't know if vue-compiler can pick up `!bg-pink-400` but if using `<style lang='scss'>` then `scss` cannot resolve this syntax and needs escape character `!bg-pink-400`

Did you try  `--at-apply:`?

**Comment by tachibana-shin** [comment] 2023-11-09 08:39
> > > ` @apply !bg-pink-400` <img alt="image" width="900" src="https://user-images.githubusercontent.com/57086651/281648008-0b145dcd-46cf-4375-b815-dfa7f16fab07.png">
> > 
> > 
> > i don't know if vue-compiler can pick up `!bg-pink-400` but if using `<style lang='scss'>` then `scss` cannot resolve this syntax and needs escape character `!bg-pink-400`
> 
> Did you try `--at-apply:`?

Oh it worked. Thanks!
But this seems inconvenient

**Comment by henrikvilhelmberglund** [comment] 2023-11-09 09:08
> Oh it worked. Thanks! But this seems inconvenient
 
 How? It's basically the same thing, just made to work in vanilla CSS 😊
 Otherwise I think it's better to skip all @apply things and just write the utilities in the elements' classes directly.

**Comment by tachibana-shin** [comment] 2023-11-09 09:59
> > Oh it worked. Thanks! But this seems inconvenient
> 
> How? It's basically the same thing, just made to work in vanilla CSS 😊 Otherwise I think it's better to skip all @apply things and just write the utilities in the elements' classes directly.

😂I certainly won't write a single line of css when I have unocss installed

**Closed** 2023-11-13 06:59 UTC
