### ISSUE TITLE
在vite的开发环境下使用global模式，每次加载一个新的页面，unocss都会更新

### ISSUE THREAD

**Issue by 840354410** [unocss/unocss#3113] opened 2023-09-12 18:21 UTC
### UnoCSS version

0.55.3

### Describe the bug

在vite的开发环境下使用global模式，每次加载一个新的页面，unocss都会更新，unocss更新后会触发之前所有页面的热更新，然后之前的所有页面都会重新加载，在生成环境没问题，我使用的是uni-app开发的，运行命令是yarn dev:h5

### Reproduction

1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2023-09-13 03:13
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2023-09-13 03:13 UTC
