### ISSUE TITLE
Generating umd or iife bundle not working with vite@2.9.14

### ISSUE THREAD

**Issue by kingcw** [unocss/unocss#1241] opened 2022-07-11 01:07 UTC
Generating umd or iife bundle is working with vite@2.9.13, but not working with vite@2.9.14

error is:
[unocss] does not found CSS placeholder in the generated chunks, this is likely an internal bug of unocss vite plugin 

error is found in this file, line 195.  problem code block should start at line 180:
https://github.com/unocss/unocss/blob/main/packages/vite/src/modes/global/build.ts

**Comment by vipero07** [comment] 2022-07-11 14:34
I'm actually seeing this issue with vite@2.9.13 too.
Downgrading unocss to 0.42.1 seems to fix this for me.

**Comment by antfu** [comment] 2022-07-12 04:15
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-12 04:15 UTC
