### ISSUE TITLE
Important ! Uno Css classes does not get styles in laravel blade files

### ISSUE THREAD

**Issue by mithublue** [unocss/unocss#1459] opened 2022-08-23 08:06 UTC
Hi,

I use vite for compilation and installed uno in vite as directed the documentation, configured it in vite.config.js . Added uno.css in main js and linked that js in master.blade.php and run "npm run dev". But I found adding uno classes in blade file does not get styles while if I write those classes in vue component/file, the style is easliy fetched as expected.

I think, uno css can not get style in blade file. Probably , it might be a bug which prevent many people using it in their popular framework, laravel.

**Comment by antfu** [comment] 2022-08-23 08:12
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-23 08:12 UTC

**Comment by pbuzdin** [comment] 2022-11-24 20:27
Hey @antfu !

I created an example for this issue https://codesandbox.io/s/recursing-bhaskara-q930ho?file=/package.json:105-209

There are 3 files in src folder: phtml, php and html

You can run an npm for them:
npm run build-phtml
npm run build-php
npm run build-html

transformer-compile-class works only for html file and does not see css classes inside phtml and php files.

**Comment by pbuzdin** [comment] 2022-12-01 12:19
Hey @mithublue !
Unocss since version 0.47.4 it is now correctly updates css classes in php and phtml files!

see #1939
