### ISSUE TITLE
@unocss/preset-rem-to-px can't be used

### ISSUE THREAD

**Issue by xinlong-chen865** [unocss/unocss#2304] opened 2023-03-05 03:46 UTC
### UnoCSS version

0.45.6

### Describe the bug

@unocss/preset-rem-to-px can't be used

### Reproduction

@unocss/preset-rem-to-px can't be used

### System Info

不能将类型“Preset<{}>”分配给类型“Preset<{}> | Preset<{}>[]”。
  不能将类型“import("/Users/chenxinlong/Desktop/\u8349\u7A3F/month7/svelte-ui-template/node_modules/@unocss/preset-rem-to-px/node_modules/@unocss/core/dist/index").Preset<{}>”分配给类型“import("/Users/chenxinlong/Desktop/\u8349\u7A3F/month7/svelte-ui-template/node_modules/@unocss/core/dist/index").Preset<{}>”。
    属性“prefix”的类型不兼容。
      不能将类型“string | string[]”分配给类型“string”。
        不能将类型“string[]”分配给类型“string”。ts(2322)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2023-03-05 04:09
Please provide a minimal repo or online link.

**Comment by antfu** [comment] 2023-03-06 05:30
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-06 05:30 UTC
