### ISSUE TITLE
已经在main.ts入口处引入，但是运行时提示需要引入，页面也报红，几秒就编译通过没在了，每次启动都会提示。

### ISSUE THREAD

**Issue by baiyajin** [unocss/unocss#3018] opened 2023-08-22 06:57 UTC
### UnoCSS version

0.53.5

### Describe the bug

已经在main.ts入口处引入，但是运行时提示需要引入，页面也报红，几秒就编译通过没在了，每次启动都会提示。

### Reproduction

已经在main.ts入口处引入，但是运行时提示需要引入，页面也报红，几秒就编译通过没在了，每次启动都会提示。

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiyajin** [comment] 2023-08-22 06:58
![image](https://github.com/unocss/unocss/assets/49177898/d5fee783-f8fb-4999-b5cd-84f1a0d4fc4c)

**Comment by antfu** [comment] 2023-08-22 20:08
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-22 20:08 UTC
