### ISSUE TITLE
@unocss/webpack cause errors (v0.44.3)

### ISSUE THREAD

**Issue by whitemay** [unocss/unocss#1297] opened 2022-07-19 03:41 UTC
errors occured on @unocss/webpack v0.44.3. 
if pull back to v0.44.2, it is all ok.

error message like:
```
 Error: Child compilation failed:
  Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/unplugin/dist/webpack/loaders/transform.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html lang="">
  |   <head>:
  SyntaxError: Unexpected token (1:0)
```

**Comment by antfu** [comment] 2022-07-19 06:09
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by whitemay** [comment] 2022-07-19 07:03
from https://github.com/whitemay/unocss-error-1.git

**Closed** 2022-07-19 07:33 UTC
