### ISSUE TITLE
Internal server error: [postcss] /__uno.css:369:47: Unknown word

### ISSUE THREAD

**Issue by sujit-baniya** [unocss/unocss#3843] opened 2024-05-27 06:30 UTC
### UnoCSS version

0.60.3

### Describe the bug

Using with ViteJS + ReactJS
Getting following error:

```
[plugin:vite:css] [postcss] /__uno.css:369:47: Unknown word
/__uno.css:369:46
367|  .\!col-start-10{grid-column-start:10 !important;}
368|  .col-start-10{grid-column-start:10;}
369|  [\!col-start-10~="\}"]{grid-column-start:10-} !important;}
   |                                                ^
370|  .\!col-start-11{grid-column-start:11 !important;}
371|  .col-start-11{grid-column-start:11;}
```

### Reproduction

Just upgraded from 0.59.0-beta.1

And running the application the error.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-05-27 16:19
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-05-27 16:19 UTC
