### ISSUE TITLE
[Bug Report] Latest update broke styling for flexbox properties in Nuxt3

### ISSUE THREAD

**Issue by rylanharper** [unocss/unocss#3660] opened 2024-03-27 16:24 UTC
### UnoCSS version

0.58.7

### Describe the bug

Upon updating Unocss to `v0.58.7` in my Nuxt3 portfolio this morning, I notice a number of styles simply no longer work. Notably flexbox properties (and sometimes borders). **This does not seem to have an effect on live production**.

Here is a pic of a section in my portfolio in dev mode vs live - the styles have not changed at all between these two images. It seems that this issue only happens on the initial load of the page, although it can sometimes revert back to this state when I save changes on a file or component:

*These images are showing that `flex`, `items-center`, and `justify-between` not being applied to these elements. Again, styles have not been changed or edited in any way. Only the `unocss` version has changed.

<img width="484" alt="Screenshot 2024-03-27 at 9 19 09 AM" src="https://github.com/unocss/unocss/assets/16216160/22361370-3ac0-445e-ac65-6b7323887e4e">

<img width="647" alt="Screenshot 2024-03-27 at 9 22 07 AM" src="https://github.com/unocss/unocss/assets/16216160/ea74bb11-8672-4686-a5d1-85a979bd99e3">

### Reproduction

I can't seem to reproduce this in a Stackblitz as it seems to be local environment issue.. But here is the gist of what I have in my project, which always seems to be unstyled upon page load:

https://stackblitz.com/edit/nuxt-starter-xy4uvj?file=package.json,unocss.config.ts,app.vue,nuxt.config.ts

### System Info

Nuxt `v3.11.1`
Node `v18.18.2`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rylanharper** [comment] 2024-03-27 22:30
Hmm so even when I downgrade versions this seems to still occur sometimes. I cannot seem to pinpoint the core issue here..

**Comment by rylanharper** [comment] 2024-04-04 21:59
This issue is seemingly fixed by upgrading Nuxt to the latest version `3.11.2` both on local and live... Not sure what was causing this to begin with and styles have still not been touched haha. Closing issue.

**Comment by rylanharper** [comment] 2024-04-05 20:46
I'm reopening this issue as I found it persists on two more of my Nuxt ecom sites, even with the latest version of Nuxt `^3.11.2` and Uno `^0.59.0`.. 

It definitely has something to do with `flex` type classes, specifically using the `items-center` class is what classes a flexbox/styling error. I have captured a video of the styles not being applied when `items-center` is added to an element (forgive the video quality, Github requires I compress the vid down to 10mb):

> context: I have a basic grid with a flex item inside that is pretty much the same as above, `flex`, `items-center`, and `justify-between`. It seems that adding `items-center` causes no styles to be applied to the flex item. I am using the `@apply` directive here as my order elements are dynamically generated based on the amount of orders a client has.

https://github.com/unocss/unocss/assets/16216160/88f4db44-2f28-4a8c-b9af-56e4a72d4a21

Oddly enough, if I add another class to this element, such as `relative` etc., the styles do go back to what they should be. This is an obvious bug that was introduced in `v0.58.7`. I'm not sure if this could be related to `@apply` or if it is related to Nuxt.

**Comment by Simon-He95** [comment] 2024-04-07 03:17
Can you provide a minimally reproducible demo?

**Comment by owl1n** [comment] 2024-04-08 12:40
With last version of nuxt its actual to me too. Some apply rules like width and height + flex rules sometimes not transform to css. Or it can work in development but not in production.

**Comment by rylanharper** [comment] 2024-04-08 19:16
@Simon-He95 The issue is that this is extremely difficult to reproduce. It also seems to not happen within new Nuxt projects, even when I have the same config as my older projects. I have tried with two new repos to reproduce the issue and simply cannot (despite spending hours on the issue this past weekend). Perhaps I need to remove my node modules folder or uninstall/reinstall uno on my older projects?

Agreed @owl1n. This definitely seems like a potential `@apply` issue, although I am still somewhat unsure of the core cause..

**Comment by microdou** [comment] 2024-04-10 22:46
I also encounter broken style, with SvelteKit. The bug was introduced in version `0.58.7`.
Broken style only occur in very few components. I will try to figure out which styles are affected...

**Comment by rylanharper** [comment] 2024-04-11 00:45
@microdou are you using `@apply` on those components with broken styles?

**Comment by microdou** [comment] 2024-04-11 02:04
@rylanharper I checked again. Yes, there are many @apply in css of my affected components.

**Comment by rylanharper** [comment] 2024-04-19 17:03
So I cannot seem to reproduce this, despite a lot of attempts on a fresh Nuxt project..

It does seem to be an `@apply` issue, as the broken styles are fixed when they are added inline. A quick fix is to rename classes that use the `@apply` styles as well, this way applied styles can stay as they are. I am considering closing this issue, as I can simply not reproduce despite a lot of attempts this past week..

**Comment by Simon-He95** [comment] 2024-05-24 09:28
I will temporarily close this issue first, and you are welcome to open it at any time when a reproducible demo is provided.

**Comment by microdou** [comment] 2024-05-30 18:24
I can confirm the issue is gone for me. I have no idea when it happened 😅 It's possible the prior issue was caused by some other dependencies.

**Comment by microdou** [comment] 2024-08-12 15:57
I still have @apply issue.
It appears to be originating from this commit https://github.com/unocss/unocss/commit/112f2561263e853e664db4a99d14aa4a8d8780e6

@apply works for me after I clone `transformer-directives` package to local and remove all `simicolonOffset`. But apparently this brutal force change may break something else that depends on `simicolonOffset`...

**Comment by rylanharper** [comment] 2024-08-12 18:00
Can confirm. I ended up switching to tailwind because this is a prevalent issue in Unocss with Nuxt. Maybe check out @microdou post above @Simon-He95?

**Comment by microdou** [comment] 2024-08-13 17:44
A bit more digging. I tested the following in my SvelteKit project.
Issue arises **when multiple `@apply` are defined**. For the following example, `@apply shadow-lg` style appears to be ignored in the final result.
```
<div class="test">Test</div>

<style lang="postcss">
  .test {
    @apply shadow-lg;
    @apply rounded-md bg-slate-300 shadow-amber-500;
  }
</style>
```

However, such outcome doesn't seem to be reproduced on UnoCSS Playground.
https://unocss.dev/play/?version=0.58.7&html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJn0B8AKrpsAPTgQFA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNANM8SHL6dwNACKw6LWADco26dzqRwiAIKIGsbAFdEsOQBPB1AnKFcAVSpBAF9QORpKTlAAch8qJkhIFMFBYlFEGXlMH2hC2QVCFTVYdQAKSUdnV0gALlAAbR0m8MQoyjqAShCel3dPRl9-IKGQgF0QvQMjGhMaNs7u3Rp9Q2NTCyt-O0hZnTnYwcEgA&css=HQFwpgziAEDeBQ1oAECGAHdAbAntCAFqgCYD2A7gLRYDmA3IihtngE6kCuAdsWMZQFti0AEY1KELKnCUAzAAZ5%2BImSqoBIsK0oBWRQwC%2BQA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA

**Comment by Simon-He95** [comment] 2024-08-13 22:46
> A bit more digging. I tested the following in my SvelteKit project. Issue arises **when multiple `@apply` are defined**. For the following example, `@apply shadow-lg` style appears to be ignored in the final result.
> 
> ```svelte
> <div class="test">Test</div>
> 
> <style lang="postcss">
>   .test {
>     @apply shadow-lg;  /* This line of style is not applied by @unocss/transformer-directives 0.58.7 or later */
>     @apply rounded-md bg-slate-300 shadow-amber-500;
>   }
> </style>
> ```
> 
> Issue can be resolved by combine style utilities into a single `@apply`. (Or by removing the `simicolonOffset` logic mentioned before)
> 
> ```svelte
> <style lang="postcss">
>   .test {
>     @apply shadow-lg rounded-md bg-slate-300 shadow-amber-500;
>   }
> </style>
> ```
> 
> However, such outcome doesn't seem to be reproduced on UnoCSS Playground. https://unocss.dev/play/?version=0.58.7&html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJn0B8AKrpsAPTgQFA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNANM8SHL6dwNACKw6LWADco26dzqRwiAIKIGsbAFdEsOQBPB1AnKFcAVSpBAF9QORpKTlAAch8qJkhIFMFBYlFEGXlMH2hC2QVCFTVYdQAKSUdnV0gALlAAbR0m8MQoyjqAShCel3dPRl9-IKGQgF0QvQMjGhMaNs7u3Rp9Q2NTCyt-O0hZnTnYwcEgA&css=HQFwpgziAEDeBQ1oAECGAHdAbAntCAFqgCYD2A7gLRYDmA3IihtngE6kCuAdsWMZQFti0AEY1KELKnCUAzAAZ5%2BImSqoBIsK0oBWRQwC%2BQA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA So far the issue is only visible in an actual SvelteKit+Vite project.

nice job，I will try to fix it

**Comment by Simon-He95** [comment] 2024-08-15 06:25
> A bit more digging. I tested the following in my SvelteKit project. Issue arises **when multiple `@apply` are defined**. For the following example, `@apply shadow-lg` style appears to be ignored in the final result.
> 
> ```svelte
> <div class="test">Test</div>
> 
> <style lang="postcss">
>   .test {
>     @apply shadow-lg;  /* This line of style is not applied by @unocss/transformer-directives 0.58.7 or later */
>     @apply rounded-md bg-slate-300 shadow-amber-500;
>   }
> </style>
> ```
> 
> Issue can be resolved by combine style utilities into a single `@apply`. (Or by removing the `simicolonOffset` logic mentioned before)
> 
> ```svelte
> <style lang="postcss">
>   .test {
>     @apply shadow-lg rounded-md bg-slate-300 shadow-amber-500;
>   }
> </style>
> ```
> 
> However, such outcome doesn't seem to be reproduced on UnoCSS Playground. [unocss.dev/play?version=0.58.7&html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJn0B8AKrpsAPTgQFA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69+oAN6DQoVOABmCcAGFK8BQHMANFNANM8SHL6dwNACKw6LWADco26dzqRwiAIKIGsbAFdEsOQBPB1AnKFcAVSpBAF9QORpKTlAAch8qJkhIFMFBYlFEGXlMH2hC2QVCFTVYdQAKSUdnV0gALlAAbR0m8MQoyjqAShCel3dPRl9-IKGQgF0QvQMjGhMaNs7u3Rp9Q2NTCyt-O0hZnTnYwcEgA&css=HQFwpgziAEDeBQ1oAECGAHdAbAntCAFqgCYD2A7gLRYDmA3IihtngE6kCuAdsWMZQFti0AEY1KELKnCUAzAAZ5+ImSqoBIsK0oBWRQwC+QA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA](https://unocss.dev/play/?version=0.58.7&html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJn0B8AKrpsAPTgQFA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNANM8SHL6dwNACKw6LWADco26dzqRwiAIKIGsbAFdEsOQBPB1AnKFcAVSpBAF9QORpKTlAAch8qJkhIFMFBYlFEGXlMH2hC2QVCFTVYdQAKSUdnV0gALlAAbR0m8MQoyjqAShCel3dPRl9-IKGQgF0QvQMjGhMaNs7u3Rp9Q2NTCyt-O0hZnTnYwcEgA&css=HQFwpgziAEDeBQ1oAECGAHdAbAntCAFqgCYD2A7gLRYDmA3IihtngE6kCuAdsWMZQFti0AEY1KELKnCUAzAAZ5%2BImSqoBIsK0oBWRQwC%2BQA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA) So far the issue is only visible in an actual SvelteKit+Vite project.

I tried to reproduce this problem in playground. I didn't catch @apply at first, but there were some problems with the logic processed in playground at that time. I couldn't reproduce it in vue project. I don't use svelte much. Can you provide a reproducible svelte demo?

**Comment by microdou** [comment] 2024-08-15 23:39
@Simon-He95 I will try to find a way to create an online repo

**Comment by microdou** [comment] 2024-08-16 01:11
@Simon-He95 

Here it is
https://stackblitz.com/edit/sveltekit-unocss-4zjjuo

**Closed** 2024-08-24 16:03 UTC
