### ISSUE TITLE
`@apply` and `--at-apply:` not working with vue less

### ISSUE THREAD

**Issue by chioio** [unocss/unocss#1382] opened 2022-08-06 06:14 UTC
Code first:
```vue
// @apply
<style scoped lang="less">
  :deep(.n-layout-sider) {
    .n-menu {
      .n-menu-divider {
        @apply relative mx-1 mt-4 h-6 bg-transparent;
        @apply before:(text-xs text-dark-400 font-light whitespace-nowrap);
      }
    }
  }
// --at-apply
<style scoped lang="less">
  :deep(.n-layout-sider) {
    .n-menu {
      .n-menu-divider {
        --at-apply: relative mx-1 mt-4 h-6 bg-transparent;
        --at-apply: before:(text-xs text-dark-400 font-light whitespace-nowrap);
      }
    }
  }
</style>
Tow ways not working. 🥲

**Comment by antfu** [comment] 2022-08-06 08:19
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-06 08:19 UTC
