### ISSUE TITLE
High CPU usage in VS Code extension

### ISSUE THREAD

**Issue by AnotiaWang** [unocss/unocss#3711] opened 2024-04-11 15:29 UTC
Type: <b>Bug</b>

VS Code stopped showing code suggestions, and plugins became unresponsive. A `Code Helper (Plugin)` process consumes 100% CPU, and can't be killed when reloading the window, resulting CPU being drained after several reloads. I used VS Code's Extension Bisect feature and located UnoCSS plugin.

Maybe related: https://github.com/vuejs/language-tools/issues/4239

Extension version: 0.59.1
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:28:09.495Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|32.00GB (5.00GB free)|
|Process Argv|--crash-reporter-id 33f2db18-d6d2-4571-bcf7-5ce1184f51fc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Saeid-Za** [comment] 2024-04-11 15:48
I have the same issue, vscode is completely frozen and unresponsive for me.
The current workaround is to downgrade to `v0.59.0`.

**Comment by Simon-He95** [comment] 2024-04-12 00:43
I'll check it later.

**Comment by Wangijun** [comment] 2024-04-12 01:30
I also encountered VsCode freeze in version 1.88.1 and unocss 0.59.1. The current solution is to downgrade it to unocss 0.59.0,


PS: Operating System Win10

**Comment by lainbo** [comment] 2024-04-12 02:06
I'm facing the same issue where my VSCode is unable to load any functionality other than typing. Using Start Extension Bisect, I found out the issue is with this extension, so I've now downgraded to v0.59.0 for use

**Comment by Simon-He95** [comment] 2024-04-12 02:19
I have found the reason and will submit a PR to fix it later.

**Comment by Saganic** [comment] 2024-04-12 06:37
Morning, can confirm something happening - blocking extension initialisation from finishing, git etc also not resolving

**Comment by AnotiaWang** [comment] 2024-04-12 08:08
Update to v0.59.2 and seems fine now

**Closed** 2024-04-12 09:06 UTC
Labels: vscode

**Comment by leoboyerbx** [comment] 2024-04-29 11:40
I am running v0.59.4 and the issue happens when I'm editing a typescript file that has this comment in it (needed in the codebase):
```typescript
// @unocss-include
```
Sticking to v0.59.0 fixes the issue.
Maybe I need to update my project's unocss version ?

**Comment by Simon-He95** [comment] 2024-04-29 12:07
can you provider your file to help me test
