### ISSUE TITLE
Slow Build Performance Issue with Astro 3 and UnoCSS in npm run dev

### ISSUE THREAD

**Issue by jasontiw** [unocss/unocss#3121] opened 2023-09-13 15:37 UTC
### UnoCSS version

0.55.7

### Describe the bug

I've encountered a significant performance issue when running npm run dev with Astro 3 and UnoCSS. The reload process takes an unreasonably long time to complete, making it impractical for development.

### Reproduction

**Steps to Reproduce:**

-   Clone the [repository](https://github.com/jasontiw/astro-cortinas-decoraciones-rafael-ac)  with the Astro 3 and UnoCSS setup.
-   Run npm install to ensure all dependencies are installed.
-   Execute npm run dev.

**Expected Behavior:**
The build process should complete within a reasonable timeframe, as experienced in previous versions of Astro.
![Code_oXUVTwzgCy](https://github.com/unocss/unocss/assets/2350184/858b5fcc-7134-4d3e-b516-1bbbcdd71099)

testing with tailwind works faster
![Code_bCD2vyxSgV](https://github.com/unocss/unocss/assets/2350184/a4c514ed-81b7-4e5d-9e31-713242165369)

**Actual Behavior:** 
The npm run build process is extremely slow, taking several times longer than expected. This performance issue makes it challenging to work efficiently with Astro 3 and UnoCSS.

### System Info

Astro Version: 3.0.13
UnoCSS Version: 0.55.7
Node.js Version: v18.17.1
Operating System: Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dunqing** [comment] 2023-09-14 01:03
Duplicate of #3103?

**Comment by Raiondesu** [comment] 2023-09-14 14:15
@Dunqing, looks like this issue is present regardless whether the view transitions are enabled or not, as well as being more about hot reload than production build time, which makes it distinct from #3103.

For me, hot reload for new unocss classes doesn't event work at all, for example, no matter the configs or features used.

**Comment by Dunqing** [comment] 2023-09-15 01:27
> @Dunqing, looks like this issue is present regardless whether the view transitions are enabled or not, as well as being more about hot reload than production build time, which makes it distinct from #3103.
> 
> For me, hot reload for new unocss classes doesn't event work at all, for example, no matter the configs or features used. Only restarting the dev server from scratch makes unocss generate new classes.

About the hot reload, there is a [bug](https://github.com/unocss/unocss/pull/3100) in Windows that has been fixed. Let's wait until the next version to see if this problem still exists

**Comment by jasontiw** [comment] 2023-09-19 18:02
it's working with **0.56.0**

**Closed** 2023-09-21 03:00 UTC

**Comment by mateoroldos** [comment] 2024-02-29 17:12
I'm having the same problem with **UnoCSS 0.58.5** and **Astro 4.4.4**. Any idea how to fix it?
