### ISSUE TITLE
0.60.3 上下文中的符号导致不能正确的生成class

### ISSUE THREAD

**Issue by Djuvl** [unocss/unocss#3847] opened 2024-05-28 07:44 UTC
### UnoCSS version

0.60.3

### Describe the bug

更新到0.60.3后 vue模板中某些代码字符的组合方式 导致class不能正确生成

### Reproduction

https://unocss.dev/play/?html=DwZwxgTglgDgLgAhAUzgVxgPgFAHpcKHB4GGEDeABuQL6U0lkDkAtE9sLuNPDsHMgC2MADYBDATiIATKADcEALjDiQIALwAiJmJYAjJpoQwA9hDgQxUOFvgsArABZNUssFlzM5cggtpkCAD8CJQAjABMAMyUSghMkeGhTAg0NJwerunyfLgCwuKSQA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

portrait中的class没有生成在media里
只保留了关键部分并把script内容放到了注释里 原始代码都是正常功能代码

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-05-29 16:57
It seems that this problem only occurs in playground. It cannot be reproduced when tested in unocss. Can you provide a mini-repo that reproduces it?
<img width="790" alt="image" src="https://github.com/unocss/unocss/assets/57086651/8c1e2734-4181-4b0d-b09a-8eb5d07cc7d8">

**Comment by zyyv** [comment] 2024-05-31 03:10
@Simon-He95 You're going too fast resolve the issue. 👍
It is worth noting that forcibly removing the comment string may be a bit violent. UnoCSS scans all strings for parsing. Whether to remove comments should be decided by the user.

Note that we have some magic strings to work with. https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline


In line 49 of your screenshot, the problem may be caused by multiple single quotes. Refer to [Playground](https://unocss.dev/play/?html=DwZwxgTglgDgLgAhAUzgVxgPgFAHpcKHB4GGEDeABuQL6U0kIDkAtNsLuNPDsHMgFsYAGwCG-HEQAmUAG4IAXGDEgQAXgBETUSwBGTDQgAWAe1nIIm%2BCwCsAFg2SywGbMzlyCOBDTIEAfgRKAEYAJgBmSkVmcNDgpgQaGg5XJxS5Xlx%2BITEJIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA).

**Comment by Simon-He95** [comment] 2024-05-31 03:21
> @Simon-He95 You're going too fast resolve the issue. 👍 你解决问题的速度太快了。 👍 It is worth noting that forcibly removing the comment string may be a bit violent. UnoCSS scans all strings for parsing. Whether to remove comments should be decided by the user. 值得注意的是，强行删除评论字符串可能有点暴力。 UnoCSS 扫描所有字符串进行解析。是否删除评论应由用户决定。
> 
> Note that we have some magic strings to work with. https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline请注意，我们有一些神奇的字符串可以使用。 https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline
> 
> In line 49 of your screenshot, the problem may be caused by multiple single quotes. Refer to [Playground](https://unocss.dev/play/?html=DwZwxgTglgDgLgAhAUzgVxgPgFAHpcKHB4GGEDeABuQL6U0kIDkAtNsLuNPDsHMgFsYAGwCG-HEQAmUAG4IAXGDEgQAXgBETUSwBGTDQgAWAe1nIIm%2BCwCsAFg2SywGbMzlyCOBDTIEAfgRKAEYAJgBmSkVmcNDgpgQaGg5XJxS5Xlx%2BITEJIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA).在屏幕截图的第 49 行中，问题可能是由多个单引号引起的。请参阅游乐场。

I understand your concern. I think it is OK to delete the string in @unocss/preset-attributify/extractor, because it does not affect the code. It just extracts the keywords in the code. Removing comments may even bring performance advantages, reducing more loops and possible special edge cases caused by irregular comments, because no one knows what will be written in his comments, but we don't need to care about this.

**Comment by Simon-He95** [comment] 2024-05-31 03:24
> @Simon-He95 You're going too fast resolve the issue. 👍 It is worth noting that forcibly removing the comment string may be a bit violent. UnoCSS scans all strings for parsing. Whether to remove comments should be decided by the user.
> 
> Note that we have some magic strings to work with. https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline
> 
> In line 49 of your screenshot, the problem may be caused by multiple single quotes. Refer to [Playground](https://unocss.dev/play/?html=DwZwxgTglgDgLgAhAUzgVxgPgFAHpcKHB4GGEDeABuQL6U0kIDkAtNsLuNPDsHMgFsYAGwCG-HEQAmUAG4IAXGDEgQAXgBETUSwBGTDQgAWAe1nIIm%2BCwCsAFg2SywGbMzlyCOBDTIEAfgRKAEYAJgBmSkVmcNDgpgQaGg5XJxS5Xlx%2BITEJIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA).

I understand your concern. I think it is OK to delete the string in `@unocss/preset-attributify/extractor`, because it does not affect the `code`. It just extracts the keywords in the code. Removing `comments` may even bring performance advantages, reducing more loops and possible special edge cases caused by irregular comments, because no one knows what will be written in his comments, but we don't need to care about this.
In addition, if there is any unocss related explanation syntax in the comments, it will also cause redundant code generation

**Comment by Simon-He95** [comment] 2024-05-31 03:35
> > @Simon-He95 You're going too fast resolve the issue. 👍 It is worth noting that forcibly removing the comment string may be a bit violent. UnoCSS scans all strings for parsing. Whether to remove comments should be decided by the user.
> > Note that we have some magic strings to work with. https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline
> > In line 49 of your screenshot, the problem may be caused by multiple single quotes. Refer to [Playground](https://unocss.dev/play/?html=DwZwxgTglgDgLgAhAUzgVxgPgFAHpcKHB4GGEDeABuQL6U0kIDkAtNsLuNPDsHMgFsYAGwCG-HEQAmUAG4IAXGDEgQAXgBETUSwBGTDQgAWAe1nIIm%2BCwCsAFg2SywGbMzlyCOBDTIEAfgRKAEYAJgBmSkVmcNDgpgQaGg5XJxS5Xlx%2BITEJIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA).
> 
> I understand your concern. I think it is OK to delete the string in `@unocss/preset-attributify/extractor`, because it does not affect the `code`. It just extracts the keywords in the code. Removing `comments` may even bring performance advantages, reducing more loops and possible special edge cases caused by irregular comments, because no one knows what will be written in his comments, but we don't need to care about this. In addition, if there is any unocss related explanation syntax in the comments, it will also cause redundant code generation

In addition, I think it is possible to convert the comment code in advance like unocss-skip, and restore it after the subsequent transform. This should make unocss run much faster, and it may also avoid some words in the comment from being parsed to generate redundant css. What do you think? @zyyv @antfu

**Comment by Djuvl** [comment] 2024-05-31 03:56
@Simon-He95 
It is not about comment. I tried using comments to simplify the problem. I create a new code snippet.
https://unocss.dev/play/?html=DwZwxgTglgDgLgAhAUzgVxgPgFALAewDsREBDBAXgQCZgBmAblwOMQCNKEBvUgLgAMuAX35CmeIiTycA5AFoZTYAHpw0eDmBxkAWxgAbUtpwIEwACZQAbgl5hDIEBQBEM0nLYznCGPghwIUig4F3g5AFYAFmcTUzNLK0wuLgQAtGQEAH4EfgBGajp%2BWwQZOmpcmQQhIRUE2NrrTWVtPUNjIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlVABfUDJpKTlAAclMqJkhIEMFBYlFEKVlMU2hE6TlCJRVYVQAKcUFQUBpUqAAuUABtKpCmU0hEINoykM1JZ2g%2BSpC6VBDfAF1B9SLQSAALPkR6gUrC4uK6hqbOZEnp2ZCe1hJkaFVQXZQ%2BTHhVcFApgDdwGnLj5FZMaDaxn1Hiu1056rGv9yILyUPIASk%2Bi2%2BekMxjMFmsYIhAPsiCcLgK-0WkCYL3AlQAjAA6ABMSMWTFQ8B6EyM3Eg5RAUE4hMmwDei184LGI0EPlBgiAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

**Comment by zyyv** [comment] 2024-05-31 05:36
> @Simon-He95 It is not about comment. I tried using comments to simplify the problem. I create a new code snippet. https://unocss.dev/play/?html=DwZwxgTglgDgLgAhAUzgVxgPgFALAewDsREBDBAXgQCZgBmAblwOMQCNKEBvUgLgAMuAX35CmeIiTycA5AFoZTYAHpw0eDmBxkAWxgAbUtpwIEwACZQAbgl5hDIEBQBEM0nLYznCGPghwIUig4F3g5AFYAFmcTUzNLK0wuLgQAtGQEAH4EfgBGajp%2BWwQZOmpcmQQhIRUE2NrrTWVtPUNjIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlVABfUDJpKTlAAclMqJkhIEMFBYlFEKVlMU2hE6TlCJRVYVQAKcUFQUBpUqAAuUABtKpCmU0hEINoykM1JZ2g%2BSpC6VBDfAF1B9SLQSAALPkR6gUrC4uK6hqbOZEnp2ZCe1hJkaFVQXZQ%2BTHhVcFApgDdwGnLj5FZMaDaxn1Hiu1056rGv9yILyUPIASk%2Bi2%2BekMxjMFmsYIhAPsiCcLgK-0WkCYL3AlQAjAA6ABMSMWTFQ8B6EyM3Eg5RAUE4hMmwDei184LGI0EPlBgiAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

```diff
<script setup>
 const a = 2<3;
 const b = {a:`{}`};
+ const c = '-';
- const c = '-;
</script>
<template>
  <div :class="'a-b'" portrait="pt-54">
    <div>{{ true ? `123` : '321' }}</div>
  </div>
</template>
```
Yep, `extractor` error parsing.

**Comment by Simon-He95** [comment] 2024-05-31 06:06
> extractor

I know this is due to problems with the extractor's regular expression, but it is difficult for regular expressions to cover all scenarios. We can still try to reduce the edge cases of regular expressions by filtering comments.

**Comment by Djuvl** [comment] 2024-12-16 13:32
Are there any plans to fix this problem? @zyyv @Simon-He95

**Comment by Simon-He95** [comment] 2024-12-16 14:23
> Are there any plans to fix this problem? @zyyv @Simon-He95

If this [PR](https://github.com/unocss/unocss/pull/4325) is successfully merged, you can try to use @unocss-skip to wrap the code area that causes regular problems

**Closed** 2024-12-18 09:33 UTC
Labels: bug
