### ISSUE TITLE
VSCode extension not working anymore

### ISSUE THREAD

**Issue by joseehilton147** [unocss/unocss#1547] opened 2022-09-05 13:57 UTC
Today I started a new project using vite + Vue 2, the package works fine but the extension not, don't display anymore the syntax when hover it, I don't know if was this last update who break the extension but on Friday was working fine.

![Image](https://user-images.githubusercontent.com/53986027/188465941-59f724d5-e8da-4f97-9cac-900a56b3ac04.png)

**Comment by antfu** [comment] 2022-09-05 15:32
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-09-05 15:32 UTC
