### ISSUE TITLE
0.65.3更新后 vite下unocss

### ISSUE THREAD

**Issue by hyx-del** [unocss/unocss#4355] opened 2024-12-26 03:28 UTC
### UnoCSS version

0.65.2

### Describe the bug

 Cannot find module 'file:///d:/item/web-admin/node_modules/jiti/lib/index.js' Require stack:

c:\Users\hyx.vscode\extensions\antfu.unocss-0.65.3\dist\jiti-NID3X7Y7.cjs
c:\Users\hyx.vscode\extensions\antfu.unocss-0.65.3\dist\dist-OSZRW7AO.cjs
c:\Users\hyx.vscode\extensions\antfu.unocss-0.65.3\dist\index.cjs
d:\Users\hyx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js
 Cannot find module 'file:///d:/item/web-admin/node_modules/jiti/lib/index.js' Require stack:

c:\Users\hyx.vscode\extensions\antfu.unocss-0.65.3\dist\jiti-NID3X7Y7.cjs
c:\Users\hyx.vscode\extensions\antfu.unocss-0.65.3\dist\dist-OSZRW7AO.cjs
c:\Users\hyx.vscode\extensions\antfu.unocss-0.65.3\dist\index.cjs
d:\Users\hyx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js

### Reproduction

![1735183673365](https://github.com/user-attachments/assets/b8d24afd-6106-452e-891a-bb146986b998)

### System Info

windows 10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-12-26 08:17
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2024-12-26 08:23 UTC

**Comment by hyx-del** [comment] 2024-12-26 08:27
![1735201549787](https://github.com/user-attachments/assets/5f247b51-5f94-4f96-a139-9e873179dc51)
![1735201568020](https://github.com/user-attachments/assets/c8e09ba5-bb0a-42c1-a607-00dc9b40771f)
这是我最新构建的vite项目  刚下载的unocss vscode 就会报这个错  
unocss 插件版本0.65.3

**Comment by hyx-del** [comment] 2024-12-26 09:10
![1735204194776](https://github.com/user-attachments/assets/3431c955-08cf-44f7-ae20-b82080504d02)
找到原因了 是你这个必须要扩展文件
