### ISSUE TITLE
Pug full feature support

### ISSUE THREAD

**Issue by Fauny** [unocss/unocss#3979] opened 2024-07-13 06:31 UTC
### UnoCSS version

0.61.3

### Describe the bug

env:

"unocss": "^0.61.3"
"@unocss/extractor-pug": "^0.61.3"
"vite": "^4.2.1"
"pug": "^3.0.3"

this works 
```
<template lang="pug">
div(class="bg-blue-500") hi
</template>
```

but this doesn't:
```
<template lang="pug">
div.bg-blue-500 this doesn't  works
.bg-blue-500 this doesn't  works either
</template>
```

all these works fine with "unocss": "^0.50.6" && "@unocss/extractor-pug": "^0.50.6",

### Reproduction

--

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wkeylin** [comment] 2024-07-22 03:20
@Fauny There is nothing wrong in this reproduction example, can you provide the reproduction project? https://stackblitz.com/edit/unocss-unocss-cfbrsu

**Comment by antfu** [comment] 2024-07-26 14:56
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-26 14:56 UTC
Labels: pr welcome
