### ISSUE TITLE
VScode extension doesn't work in some file types

### ISSUE THREAD

**Issue by woldtwerk** [unocss/unocss#4000] opened 2024-07-19 07:13 UTC
### UnoCSS version

0.61.5

### Describe the bug

I can't get it to work in .twig files.

These are my settings:
```json
"unocss.languageIds": ["twig", "html"],
"emmet.includeLanguages": {
    "twig": "html",
}
```

When I add:
```twig
{# @unocss-include #}
```
to a twig file it works

### Reproduction

install unocss, vscode extension, add config

can't provide a stackblitz since it's vscode related

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-07-19 08:17
Do you have `uno.config` file?

**Comment by woldtwerk** [comment] 2024-07-27 14:08
yes I do

**Comment by antfu** [comment] 2024-07-29 12:59
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-29 12:59 UTC

**Comment by woldtwerk** [comment] 2024-09-17 06:55
I figured it out.
I use content.filesystem for file scanning. This works, but unocss extension doesn't work.
I had to add:
```js
content: {
  pipeline: {
    include: [ /\.(twig|yml)($|\?)/]
  }
}
```
Now the extension works correctly:

![image](https://github.com/user-attachments/assets/737fcc0b-c7ff-4b6c-af04-f3235983421c)


I don't compile compile those files with vite. Thus I did not use this setting.
