### ISSUE TITLE
包含 .html 会导致构建之后的html入口增加一段 import "/@unocss/xxxx.css"的代码

### ISSUE THREAD

**Issue by 1161906592** [unocss/unocss#1375] opened 2022-08-05 07:38 UTC
https://github.com/unocss/unocss/blob/754edad1888b130f1b3db8a80d83fbcdf03b12f1/packages/shared-integration/src/defaults.ts#L4
![image](https://user-images.githubusercontent.com/30269670/183026831-4bf6c714-7ba6-4f3f-956f-5f3ab4467c2b.png)

**Comment by chris-zhu** [comment] 2022-08-05 08:58
Can you provide a minimal reproduction?

**Comment by antfu** [comment] 2022-08-05 15:16
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-05 15:16 UTC
