### ISSUE TITLE
Can not use lodash in uno.config.js

### ISSUE THREAD

**Issue by winter-ice** [unocss/unocss#1299] opened 2022-07-19 06:35 UTC
`import { range } from 'lodash-es'`
...
  rules: [
    range(10, 1).map(i => `grid-cols-${i}`)
  ],
...

Will cause vite dev cannot start

**Comment by antfu** [comment] 2022-07-19 06:37
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-19 06:37 UTC

**Comment by winter-ice** [comment] 2022-07-19 06:39
@antfu isn't it is a minimal reproduction?
