### ISSUE TITLE
VSCode extension doesn't work

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [unocss/unocss#2722] opened 2023-06-05 13:31 UTC
### UnoCSS version

UnoCSS: 0.53.0 / Extension: v0.22.5

### Describe the bug

I followed the installation guide for UnoCSS with astro (https://unocss.dev/integrations/astro), installed the extension and I get the following error in the extension output :
```
Configuration loaded from
 - uno.config.ts
Error on annotation
TypeError: Cannot read properties of undefined (reading 'join')
```

### Reproduction

create new TS astro project , install UnoCSS integration (https://unocss.dev/integrations/astro)

### System Info

linux

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by johnxu77** [comment] 2023-06-27 18:34
When I used unocss and extension together in next.js, it had a similar problem.

After debugging the extension, it seems `ctx.generator.config.separators` is undefined.

You may define separators explicitly in `uno.config.ts` for solving the problem.

```typescript
export default defineConfig({
  separators: [":", "-"],
  presets: [
    presetUno(),
  ]
```

**Comment by antfu** [comment] 2023-06-27 18:37
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-06-27 18:37 UTC

**Comment by Wxw-Gu** [comment] 2023-07-11 08:01
> 当我在 next.js 中一起使用 unocss 和扩展时，也遇到了类似的问题。
> 
> 调试扩展后，似乎`ctx.generator.config.separators`未定义。
> 
> 您可以显式定义分隔符`uno.config.ts`来解决问题。
> 
> ```ts
> export default defineConfig({
>   separators: [":", "-"],
>   presets: [
>     presetUno(),
>   ]
> ```

感谢，它工作了😁
