### ISSUE TITLE
uno build speed is obviously slow 

### ISSUE THREAD

**Issue by aofong19871029** [unocss/unocss#3220] opened 2023-10-11 10:35 UTC
### UnoCSS version

0.56.4

### Describe the bug

我用@unocss/postcss  + rollup进行uno css开发
在组件编译打包过程中发现uno运行时间明显表现的慢

[unocss] `@unocss/postcss` package is in an experimental state right now. It doesn't follow semver, and may introduce breaking changes in patch versions.

每次至少耗时2s 来完成uno css的编译，无论rollup还是next都是如何

@unocss/postcss的版本是0.56.4

### Reproduction

 1

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-10-11 11:03
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-11 11:03 UTC
