### ISSUE TITLE
Attributify styles not applied since 0.51.6 (#2529)

### ISSUE THREAD

**Issue by mwohlan** [unocss/unocss#2620] opened 2023-05-14 11:03 UTC
### UnoCSS version

0.51.12

### Describe the bug

Since 0.51.6, specifically #2529, attributify styles are not being applied for some reason. The attributes are there:

![image](https://github.com/unocss/unocss/assets/76627776/5c019e36-8b16-424a-b1e6-5ab20c383941)

But only some styles are being applied:

![image](https://github.com/unocss/unocss/assets/76627776/ee0a2474-dd14-4034-8dc7-13abb698db34)

Downgrading to 0.51.5 works and afaik I am not using ternaries mentioned in #2529

### Reproduction

I was not able to provide a minimal reproduction as of now. My current project is quite big and not open source. But maybe through some discussion and help I can get there

### System Info

- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.5.0-28066965.d077c10c
- Nitro Version:    2.5.0-28064672.742dc3f
- Package Manager:  pnpm@7.17.0
- Builder:          vite
- User Config:      modules, imports, build, fontMetrics, ssr, experimental, nitro, routeRules, unocss, typescript, headlessui, css, runtimeConfig, supabase, app
- Runtime Modules:  @vueuse/nuxt@10.1.2, @unocss/nuxt@0.51.12, @pinia/nuxt@0.4.10, @nuxtjs/supabase@0.3.5, nuxt-headlessui@1.1.4, @nuxtjs/fontaine@0.2.5, @nuxt/devtools@0.4.6-28063770.3b99477
- Build Modules:    -

Unocss config
```js
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [
    ['btn', 'px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50'],
    ['icon-btn', 'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-teal-600'],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
        mulish: {
          name: 'Mulish',
          weights: [200, 300, 400, 500, 600, 700, 800, 900],
        },
        inter: {
          name: 'Inter',
          weights: [200, 300, 400, 500, 600, 700, 800, 900],
        },
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-05-14 16:03
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-14 16:03 UTC

**Comment by mwohlan** [comment] 2023-06-01 09:46
Coming back to this. Feel free to close it again right away, but I dont really know how I can solve this issue for my project. Looking at the inspector with 0.52.7, styles are definitely being generated as before. 

![Screenshot from 2023-06-01 11-13-03](https://github.com/unocss/unocss/assets/76627776/1668ead7-8a3d-41db-8e2c-cd6f0a6a8236)

They are just not being applied. When turning off attributify with 0.52.7, all styles that are written within the class attribute are being applied.

When reverting the fix #2529 (while still using 0.52.7) 

![image](https://github.com/unocss/unocss/assets/76627776/101f8d16-62fe-4ff9-a0ac-05b9cf817dd9)


All the styles are working again. Pretty sure I am not using ternaries with attributify. And even then It shouldn't break everything, right ? Maybe there is something else in the regex that breaks the styles completely in some edge case.

A solution would be to refactor from attributify to class only. But maybe someone has an idea on how to look into this.

**Comment by mwohlan** [comment] 2023-06-02 19:09
@antfu : Reproduction: [Stackblitz](https://stackblitz.com/edit/github-bhavvb?file=app.vue)

I found the cause. The :display-value prop is matched by unocss and it breaks the entire css of the project silently. Is this behavior as expected since it kind of is a ternary expression...

**Comment by NikitaVelixJob** [comment] 2024-12-25 13:51
Just got the same issue with building on docker @antfu.

@mwohlan how to find this prop value

**Comment by Simon-He95** [comment] 2024-12-26 07:49
> @antfu : Reproduction: [Stackblitz](https://stackblitz.com/edit/github-bhavvb?file=app.vue)
> 
> I found the cause. The :display-value prop is matched by unocss and it breaks the entire css of the project silently. Is this behavior as expected since it kind of is a ternary expression ? But I still would prefer an error message of some sort.

Some special writing methods may cause uno's parsing regular exceptions. Try to put these logics out of the template and then wrap them with uno-skip to make them ignored by uno parsing to solve these problems.
