### ISSUE TITLE
unocss.config presetRemToPx ts报错

### ISSUE THREAD

**Issue by NT-Sasoli** [unocss/unocss#2964] opened 2023-08-09 12:27 UTC
### UnoCSS version

0.54.1

### Describe the bug

不能将类型“Preset<object>”分配给类型“Preset<object> | Preset<object>[]”。

### Reproduction

```
presets: [
    presetAttributify(),
    presetUno(),
    // @ts-ignore
    presetRemToPx({
      baseFontSize: 4
    })
  ```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-08-09 12:56
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-09 12:56 UTC
