### ISSUE TITLE
Using Presets with `presetAttributify` , vitepress build no reponse

### ISSUE THREAD

**Issue by liuben-team** [unocss/unocss#1066] opened 2022-06-06 06:46 UTC
- "unocss": "^0.37.4",
- "vite": "^2.9.9",
- "vitepress": "1.0.0-alpha.1"

```ts
import Unocss from 'unocss/vite'
import { presetAttributify, presetUno } from 'unocss'

export default defineConfig({
  ...
  plugins: [
    Unocss({
      presets: [
        presetUno(),
        presetAttributify()
      ]
    }),
  ]
})
```

When Using Presets with `presetAttributify` , vitepress build no reponse, like this
```bash
vitepress v1.0.0-alpha.1
⠇ building client + server bundles...
```

it's done well when i remove `presetAttributify`

**Comment by antfu** [comment] 2022-06-06 06:47
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-06 06:47 UTC
