### ISSUE TITLE
Icons Preset Causes Large CSS Bundle - Need Solution for On-Demand CSS for Vue Components

### ISSUE THREAD

**Issue by green-mike** [unocss/unocss#3894] opened 2024-06-14 03:52 UTC
### Clear and concise description of the problem

I work with Nuxt 3 and unocss. When using the icons preset, I noticed that it causes the CSS bundle size to increase significantly(600kb). This is problematic for performance, especially for applications where only a few icons are used per page, but the CSS for all icons is included in the final bundle. 

### Suggested solution

To address this, I suggest implementing a way to allow Vue components to include only the CSS for the icons they actually use. This on-demand approach would help keep the CSS bundle size minimal and improve performance.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment] 2024-06-14 06:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-06-14 06:42 UTC
Labels: needs reproduction
