### ISSUE TITLE
【preset-mini】CDN resource request fail

### ISSUE THREAD

**Issue by Tzyito** [unocss/unocss#4001] opened 2024-07-19 10:35 UTC
### UnoCSS version

0.61.5

### Describe the bug

When I use preset-mini's cdn resource, a new cdn resource (shared) is loaded.

<img width="937" alt="image" src="https://github.com/user-attachments/assets/5cee71a4-62a1-4b76-ba4a-1e10f12a39b8">

<img width="1253" alt="image" src="https://github.com/user-attachments/assets/6e733346-1a88-4814-809f-1277a71497c1">

I wonder if this can be packaged into a file

### Reproduction

later

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment] 2024-07-19 11:00
That url should be https://cdn.jsdelivr.net/npm/@unocss/preset-mini/dist/shared/preset-mini.B66ZMXnT.mjs we don't publish shared package, it should be resolved relative to `@unocss/preset-mini` package export.

How are you using preset mini in your app?

**Comment by Tzyito** [comment] 2024-07-19 11:33
I use import-maps import `unocss`, then use it in my app. Just like `import { createGenerator } from 'unocss', and then call this function. This problem occurs because unocss requests the code in the presetmini package.

**Comment by userquin** [comment] 2024-07-19 11:36
what's your import maps?

**Comment by antfu** [comment] 2024-07-19 20:28
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-19 20:28 UTC
Labels: needs reproduction
