### ISSUE TITLE
PostCSS Plugin

### ISSUE THREAD

**Issue by fjloser** [unocss/unocss#3489] opened 2024-01-04 09:24 UTC
### UnoCSS version

0.583

### Describe the bug

i use postcss v8.4.32 and i follow the document for PostCSS Plugin, but it tell me a erro "PostCSS plugin unocss requires PostCSS 8.". I use webpack4 and nodeV19,  i don't know how to make it work.

### Reproduction

![image](https://github.com/unocss/unocss/assets/24973938/7a613029-5e0b-426c-a8a1-e74bc16514f8)
![image](https://github.com/unocss/unocss/assets/24973938/29fd521b-b009-4de7-b4d1-814c77a0a916)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-01-19 10:03
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-19 10:03 UTC
