### ISSUE TITLE
performance about vscode extensions

### ISSUE THREAD

**Issue by Handpear** [unocss/unocss#2750] opened 2023-06-09 15:03 UTC
### UnoCSS version

0.53.1

### Describe the bug

自从 vscode 1.69 版本后，拓展插件会影响 vscode 性能，直到会导致 1.79 版本的 vscode 完全崩溃 - "Initializing JS/TS language features"

已经逐个排查拓展插件，确认为 UnoCSS 的问题

### Reproduction

![image](https://github.com/unocss/unocss/assets/40299372/0ab5b45d-adfa-4c19-8176-eedaa00b6112)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-06-09 18:05
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-06-09 18:05 UTC
