### ISSUE TITLE
terminal spam

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [unocss/unocss#2636] opened 2023-05-19 00:58 UTC
### UnoCSS version

latest

### Describe the bug

I have a huge verbose content about unocss useless and i would like to not show it

`🏃 [start] Running command "astro dev"
  🚀  astro  v2.5.0 started in 813ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  http://192.168.1.90:3000/
  
02:48:42 [content] Watching src/content/ for changes
02:48:42 [content] "posts" is not a collection. Check your content config for typos.
02:48:42 [content] Types generated
02:48:42 [astro] update /home/manjaro/DEV/uno test/marina copie/.astro/types.d.ts
[unocss] The container query rule is experimental and may not follow semver.
[vite:css] grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
550|  .cursor-pointer{cursor:pointer;}
551|  .place-items-center{place-items:center;}
552|  .gap-4{grid-gap:1rem;gap:1rem;}
   |          ^
553|  .gap-x-2{grid-column-gap:0.5rem;column-gap:0.5rem;}
554|  .gap-y-4{grid-row-gap:1rem;row-gap:1rem;}
[vite:css] start value has mixed support, consider using flex-start instead
658|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
659|  .\@container{container-type:inline-size;}
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                  ^
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
658|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
659|  .\@container{container-type:inline-size;}
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                                        ^
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .\@container{container-type:inline-size;}
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
   |                                                                      ^
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
663|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
   |                                               ^
663|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
664|  .p-10-0{padding:2.5rem 0rem;}
[vite:css] grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
550|  .cursor-pointer{cursor:pointer;}
551|  .place-items-center{place-items:center;}
552|  .gap-4{grid-gap:1rem;gap:1rem;}
   |          ^
553|  .gap-x-2{grid-column-gap:0.5rem;column-gap:0.5rem;}
554|  .gap-y-4{grid-row-gap:1rem;row-gap:1rem;}
[vite:css] start value has mixed support, consider using flex-start instead
658|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
659|  .\@container{container-type:inline-size;}
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                  ^
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
658|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
659|  .\@container{container-type:inline-size;}
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                                        ^
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .\@container{container-type:inline-size;}
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
   |                                                                      ^
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
663|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
660|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
661|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
662|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
   |                                               ^
663|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
664|  .p-10-0{padding:2.5rem 0rem;}
[vite:css] grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
551|  .cursor-pointer{cursor:pointer;}
552|  .place-items-center{place-items:center;}
553|  .gap-4{grid-gap:1rem;gap:1rem;}
   |          ^
554|  .gap-x-2{grid-column-gap:0.5rem;column-gap:0.5rem;}
555|  .gap-y-4{grid-row-gap:1rem;row-gap:1rem;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                  ^
662|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
663|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                                        ^
662|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
663|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
662|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
   |                                                                      ^
663|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
664|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
662|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
663|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
   |                                               ^
664|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
665|  .p-10-0{padding:2.5rem 0rem;}
[vite:css] grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
551|  .cursor-pointer{cursor:pointer;}
552|  .place-items-center{place-items:center;}
553|  .gap-4{grid-gap:1rem;gap:1rem;}
   |          ^
554|  .gap-x-2{grid-column-gap:0.5rem;column-gap:0.5rem;}
555|  .gap-y-4{grid-row-gap:1rem;row-gap:1rem;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                  ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                                        ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
   |                                                                      ^
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
665|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
   |                                               ^
665|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
666|  .p-10-0{padding:2.5rem 0rem;}
[vite:css] grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
551|  .cursor-pointer{cursor:pointer;}
552|  .place-items-center{place-items:center;}
553|  .gap-4{grid-gap:1rem;gap:1rem;}
   |          ^
554|  .gap-x-2{grid-column-gap:0.5rem;column-gap:0.5rem;}
555|  .gap-y-4{grid-row-gap:1rem;row-gap:1rem;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                  ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                                        ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
   |                                                                      ^
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
665|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
   |                                               ^
665|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
666|  .p-10-0{padding:2.5rem 0rem;}
[vite:css] grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
551|  .cursor-pointer{cursor:pointer;}
552|  .place-items-center{place-items:center;}
553|  .gap-4{grid-gap:1rem;gap:1rem;}
   |          ^
554|  .gap-x-2{grid-column-gap:0.5rem;column-gap:0.5rem;}
555|  .gap-y-4{grid-row-gap:1rem;row-gap:1rem;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                  ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                                        ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
   |                                                                      ^
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
665|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
   |                                               ^
665|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
666|  .p-10-0{padding:2.5rem 0rem;}
[vite:css] grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
551|  .cursor-pointer{cursor:pointer;}
552|  .place-items-center{place-items:center;}
553|  .gap-4{grid-gap:1rem;gap:1rem;}
   |          ^
554|  .gap-x-2{grid-column-gap:0.5rem;column-gap:0.5rem;}
555|  .gap-y-4{grid-row-gap:1rem;row-gap:1rem;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                  ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
659|  .ease-out{transition-timing-function:cubic-bezier(0, 0, 0.2, 1);}
660|  .\@container{container-type:inline-size;}
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
   |                                                                        ^
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
[vite:css] start value has mixed support, consider using flex-start instead
661|  .flex-col-1{display:flex;flex-direction:column;justify-content:start;align-items:start;}
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
   |                                                                      ^
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}
665|  .flex-row-5{display:flex;flex-direction:row;justify-content:center;align-items:center;}
[vite:css] start value has mixed support, consider using flex-start instead
662|  .flex-col-5{display:flex;flex-direction:column;justify-content:center;align-items:center;}
663|  .flex-row-2{display:flex;flex-direction:row;justify-content:center;align-items:start;}
664|  .flex-row-4{display:flex;flex-direction:row;justify-content:start;align-items:center;}

### Reproduction

pnpm run dev

### System Info

linux arch

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-05-19 07:04
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-19 07:04 UTC
