### ISSUE TITLE
The loop of v-for in Vue cannot be displayed

### ISSUE THREAD

**Issue by a184734919** [unocss/unocss#4263] opened 2024-11-14 09:06 UTC
### UnoCSS version

0.64

### Describe the bug

<template>
  <div class="w-full flex items-center justify-center gap-x-4 text-4xl p-2 mt-4">
    <div class="i-vscode-icons:file-type-light-pnpm" />
    <div class="i-vscode-icons:file-type-light-pnpm?mask text-red-300" />
    <div class="i-vscode-icons:file-type-caddy"></div>
    <div v-for="item in arr" :key="item" :class="`i-vscode-icons:file-type-${item}`"></div>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
const arr = ref(['access2'])
</script>
<style></style>

### Reproduction

<template>
  <div class="w-full flex items-center justify-center gap-x-4 text-4xl p-2 mt-4">
    <div class="i-vscode-icons:file-type-light-pnpm" />
    <div class="i-vscode-icons:file-type-light-pnpm?mask text-red-300" />
    <div class="i-vscode-icons:file-type-caddy"></div>
    <div v-for="item in arr" :key="item" :class="`i-vscode-icons:file-type-${item}`"></div>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
const arr = ref(['access2'])
</script>
<style></style>

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2024-11-14 09:49
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2024-11-14 09:49 UTC
