### ISSUE TITLE
【BUG】[unocss] entry module not found, have you add `import 'uno.css'` in your main entry?

### ISSUE THREAD

**Issue by Mrcxt** [unocss/unocss#3943] opened 2024-07-02 09:46 UTC
### UnoCSS version

^0.58.3

### Describe the bug

vite多入口的情况下，一部分入口未引入unocss，导致弹出报错信息。
不光是多入口，在vite中配置了unocss/vite插件之后，只要没有在入口文件引入unocss，都会报错：

目前在content - pipeline - include 中配置了路径，但是依然会报错。

目前看似乎对生产环境没什么影响。但是开发环境直接这样报错导致组内开发无法通过review。

期望：即使不引入unocss，也不要直接在页面上报错误信息。可以在控制台弹出warning信息。

------

In the case of multiple entry points with Vite, some entry points that do not include Unocss will cause error messages to pop up.

Not only in the case of multiple entry points, but after configuring the unocss/vite plugin in Vite, an error will be thrown as long as Unocss is not included in the entry file:

Currently, I have configured the path in content - pipeline - include, but the error still occurs.

It seems that this issue does not affect the production environment. However, the error in the development environment is preventing the team from passing code reviews.

Expectation: Even if Unocss is not included, do not directly display error messages on the page. A warning message can be displayed in the console instead.

### Reproduction

![image](https://github.com/unocss/unocss/assets/16064831/b8fb43f1-f2ca-42e8-a0fc-e659cd593f48)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-07-03 02:02
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-07-03 02:02 UTC
