### ISSUE TITLE
【BUG】Cannot find module 'uno.css' ,It seems that the new version will have adaptation issues

### ISSUE THREAD

**Issue by Simonmie** [unocss/unocss#4038] opened 2024-08-01 03:09 UTC
### Describe the bug

![bf8a72a66e60bc140893ffd495847c0](https://github.com/user-attachments/assets/35d8b4c9-790c-49c0-bc47-a3f8a032fc8f)
My project is nuxt2 and uses js, why is this happening？

### Reproduction

It seems that as long as it is nuxt2+unocss, this problem will occur

### UnoCSS version 0.45.1

![image](https://github.com/user-attachments/assets/8a42e076-6628-457a-b66b-7385b6df4b0e)

### UnoCSS version 0.33.1

without any problem

### System Info

windows 11

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simonmie** [comment] 2024-08-01 07:44
I'm confused because it seems that a specific version might have this issue, but some versions don't. Just now, I used version 0.60.3, and this problem didn't occur.
我很疑惑，好像特定版本会出现这个，但有些版本就不会，刚刚使用了0.60.3，就不会出现这个问题

**Comment by antfu** [comment] 2024-08-01 11:14
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-01 11:14 UTC

**Comment by Simonmie** [comment] 2024-08-01 11:17
ok，I will



---- Replied Message ----
| From | Anthony ***@***.***> |
| Date | 08/01/2024 19:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [unocss/unocss] 【BUG】Cannot find module 'uno.css' ,It seems that the new version will have adaptation issues (Issue #4038) |

We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a minimal reproduction to reopen the issue.
Thanks.

Why reproduction is required

**Comment by Simonmie** [comment] 2024-08-02 02:00
[unocss-test.zip](https://github.com/user-attachments/files/16464232/unocss-test.zip)
This is a simple demo for the problem

**Comment by Simonmie** [comment] 2024-08-02 02:02
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.由于缺乏足够的信息，我们暂时关闭了此功能。我们无法确定这是一个错误还是给定信息的用户空间配置错误。 Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.请提供[最小的复制](https://stackoverflow.com/help/minimal-reproducible-example)品以重新打开问题。 Thanks. 谢谢。
> 
> > [Why reproduction is required为什么需要繁殖](https://antfu.me/posts/why-reproductions-are-required)



> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.由于缺乏足够的信息，我们暂时关闭了此功能。我们无法确定这是一个错误还是给定信息的用户空间配置错误。 Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.请提供[最小的复制](https://stackoverflow.com/help/minimal-reproducible-example)品以重新打开问题。 Thanks. 谢谢。
> 
> > [Why reproduction is required为什么需要繁殖](https://antfu.me/posts/why-reproductions-are-required)

[unocss-test.zip](https://github.com/user-attachments/files/16464240/unocss-test.zip)

This is a simple demo for the problem

**Comment by adcGG** [comment] 2024-08-10 09:26
我也遇到这个问题了，我试了很多版本
发现在0.58.5之后(不包括0.58.5)就开始出现 Cannot find ... uno.css 
目前我的 nuxt2+unocss, 主要是这几个包和版本
"@unocss/nuxt": "^0.58.5",
"nuxt": "^2.15.8",

**Comment by Simonmie** [comment] 2024-08-10 09:30
> 我也遇到这个问题了，我试了很多版本 发现在0.58.5之后(不包括0.58.5)就开始出现 Cannot find ... uno.css 目前我的 nuxt2+unocss, 主要是这几个包和版本 "@unocss/nuxt": "^0.58.5", "nuxt": "^2.15.8",

目前可能最接近新的版本的是0.60.3，你可以试试

**Comment by adcGG** [comment] 2024-08-10 09:37
> > 我也遇到这个问题了，我试了很多版本 发现在0.58.5之后(不包括0.58.5)就开始出现 Cannot find ... uno.css 目前我的 nuxt2+unocss, 主要是这几个包和版本 "@unocss/nuxt": "^0.58.5", "nuxt": "^2.15.8",
> 
> 目前可能最接近新的版本的是0.60.3，你可以试试

我试过了，会报同样的问题~
我在 unocss 官网的示例，看到是两年前的提交记录，我找到那会的包的版本，大概是0.30..

我创建了一个单独的nuxt2项目，然后尝试安装 unocss 和 @unocss/nuxt,  0.30版本的，是能够使用的，没有报错
后面尝试了几次之后，在0.58.6之后开始报错了，最新的0.60.3也是报错的

所以我现在用0.58.5版本的，目前是够用的
