### ISSUE TITLE
Compile class transformer work error in vite-react-swc

### ISSUE THREAD

**Issue by chioio** [unocss/unocss#2653] opened 2023-05-23 05:31 UTC
### UnoCSS version

v0.51.13

### Describe the bug

Configure the uno transformer with compile class transformer, vite react app get error when using `:uno:` in `className`.
![image](https://github.com/unocss/unocss/assets/36913769/2638c4e6-06dc-4c8f-ada4-ffbdb42731c1)

### Reproduction

https://stackblitz.com/edit/unocss-unocss-tublnd?file=tsconfig.node.json,vite.config.ts,src%2FApp.tsx,package.json

`@vitejs/plugin-react` works
`@vitejs/plugin-react-swc` not work

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jods4** [comment] 2024-02-22 22:54
Did you ever find out what the cause of this error is?

I'm having the same error in a different context: Vite + Vue + CSS files transformer + apparently using nesting, `&` and possibly pseudo selectors like `&::backdrop`.

I'm trying to create a repro on StackBlitz but it seems to work, so not sure what the trigger is.
BTW your repro link actually also works for me?? Yet I'm seeing this issue locally on latest release of everything (unocss, Vite).

**Comment by Simon-He95** [comment] 2024-06-13 07:05
It seems that this error is no longer seen in the latest version. I will close this issue first. If you still have problems, please update the demo and open it again. Thank you.

**Closed by Simon-He95** 2024-06-13 07:05 UTC
Labels: pr welcome
