### ISSUE TITLE
Crash with Astro, preset-wind and Node 16

### ISSUE THREAD

**Issue by sproott** [unocss/unocss#2165] opened 2023-02-07 13:25 UTC
### UnoCSS version

0.49.4

### Describe the bug

Astro crashes with an error when using preset-wind and Node 16. I've tried to isolate the issue further, but the only thing I found is that it doesn't crash when using Node 18 or when not using preset-wind and using the default one instead.

I don't see any mention of supported Node versions in the UnoCSS README, so I'm not sure if it's even intended to work on older LTS versions. Just reporting in case there's a deeper issue somewhere.

### Reproduction

https://github.com/sproott/unocss-astro-wind-crash

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment] 2023-02-13 00:59
As a workaround you can import from "unocss/preset-wind":
```ts
import { presetWind } from "unocss/preset-wind";
```

---

I identified that this is caused by `ofetch` import. I gave it a look but couldn't come up with a solution. 
https://github.com/unocss/unocss/blob/654c7f973878c41cc1c07207f85e439d9fd5869f/packages/preset-icons/src/cdn.ts#L5

Error message:

```
> astro dev

file:///C:/Users/sib/dev/fork/unocss/node_modules/.pnpm/node-fetch-native@1.0.1/node_modules/node-fetch-native/dist/shared/node-fetch-native.25a180d0.mjs:428
                            throw new TypeError(`${context} is not a ReadableStream.`);
                                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (file:///C:/Users/sib/dev/fork/unocss/node_modules/.pnpm/node-fetch-native@1.0.1/node_modules/node-fetch-native/dist/shared/node-fetch-native.25a180d0.mjs:428:21)
    at convertReadableWritablePair (file:///C:/Users/sib/dev/fork/unocss/node_modules/.pnpm/node-fetch-native@1.0.1/node_modules/node-fetch-native/dist/shared/node-fetch-native.25a180d0.mjs:3505:11)
    at ReadableStream.pipeThrough (file:///C:/Users/sib/dev/fork/unocss/node_modules/.pnpm/node-fetch-native@1.0.1/node_modules/node-fetch-native/dist/shared/node-fetch-native.25a180d0.mjs:3580:33)
    at fetchFinale (C:\Users\sib\Downloads\unocss-astro-wind-crash-main\unocss-astro-wind-crash-main\node_modules\.pnpm\undici@5.18.0\node_modules\undici\lib\fetch\index.js:977:52)
    at mainFetch (C:\Users\sib\Downloads\unocss-astro-wind-crash-main\unocss-astro-wind-crash-main\node_modules\.pnpm\undici@5.18.0\node_modules\undici\lib\fetch\index.js:777:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ELIFECYCLE  Command failed with exit code 1.
````

I'm closing this for now as it's not directly related to unocss.

**Closed by sibbng** 2023-02-13 00:59 UTC
