### ISSUE TITLE
VSCode: Unresponsive extension host

### ISSUE THREAD

**Issue by ktdd** [unocss/unocss#4082] opened 2024-08-19 15:34 UTC
### UnoCSS version

Versions during last six months or so

### Describe the bug

When trying to save a file VSCode hangs. Developer tools warns about "UNRESPONSIVE extension host: 'antfu.unocss' took 100% of 5022.275ms". Only thing that helps is restarting extension host in VSCode.

When checking out cpu profiles, it seems that getMatchedPositionsFromCode() or getMatchedPositions() is the function that hangs. I have attached the latest profile, they are all similar. So far I've narrowed this down to the following code in VSCode extension, in getMatchedPositions() function. If I comment it out, it never hangs.

```
      for (const match of code.matchAll(regex)) {
        includeRanges.push([match.index, match.index + match[0].length]);
      }
```

[exthost-46fd78.json](https://github.com/user-attachments/files/16661426/exthost-46fd78.json)

Let me know if I can somehow debug this myself and provide more information. I can't reproduce this reliably.

### Reproduction

Can't reproduce reliably.

### System Info

Windows 11, Vite TS React project. uno.config.ts only has presetUno(), breakpoints and a couple of colors.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ktdd** [comment] 2024-08-19 15:51
Debugged some more and it's this regex in defaultIdeMatchInclude which makes it hang:

```/<[^/?<>0-9$_!](?:"[^"]*"|'[^']*'|[^>])+>/g```

If I switch that to the one in commit 8e615ab, ```/<[^>]+?>/g``` it doesn't hang.

**Comment by Simon-He95** [comment] 2024-09-06 08:56
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-09-06 08:56 UTC
