### ISSUE TITLE
是否有方法实现uno.css置于<head/>中样式引入的最后？

### ISSUE THREAD

**Issue by ying-tch** [unocss/unocss#3952] opened 2024-07-04 03:27 UTC
### Clear and concise description of the problem

我希望能用unocss的样式来修改我UI组件库（例如:element plus，antd这些）的样式，然而UI组件库采用**按需引入**后，Unocss的样式则永远在组件库样式的前面，从而无法实现样式的覆盖。有没有什么方法可以实现我的需求？

### Suggested solution

![image](https://github.com/unocss/unocss/assets/31296940/8c1b7aca-ceb8-46d7-9766-cbcb05903f02)
如图所示

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ying-tch** [comment] 2024-07-08 01:29
> You can try the vite-related plug-in to see if you can determine the position of the uno-related style in the uno head in each hot update, and take it out and put it at the end. You can try the vite-related capabilities

Thanks a lot for the great advice you've given!

**Comment by coderwyd** [comment] 2024-07-12 03:49
Maybe you can try `mode: 'vue-scoped'`

**Comment by z-sq** [comment] 2024-07-24 14:50
开发的时候使用完整引入组件库，等项目完成改成按需引入，就不会有问题了，在uno后的样式表都是运行项目后，新使用的组件，造成在uno后面，清理缓存，重新运行项目，uno.css就又会在最后

**Comment by antfu** [comment] 2024-07-29 13:01
UnoCSS will insert at the point you `import 'uno.css'` where the order is decided by the order of your imports.

**Comment by antfu** [comment] 2024-07-29 13:01
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-29 13:01 UTC

**Comment by Cat1007** [comment] 2025-09-10 11:59
> UnoCSS will insert at the point you `import 'uno.css'` where the order is decided by the order of your imports.UnoCSS 将在您 `import 'uno.css'` 位置插入，其顺序由导入的顺序决定。

在使用 unplugin-auto-import 和 unplugin-vue-components 按需引入时，单个组件的样式文件被插入在 index.ts 中引入的 css 之后，这个表现和开发时候不同，因为前后原因优先级变动后 unocss 在生产版本失效
