### ISSUE TITLE
Webstorm Intellisense support

### ISSUE THREAD

**Issue by SnowingFox** [unocss/unocss#1166] opened 2022-06-25 14:43 UTC
vscode is a nice ide, but there  has a lost of people using others like webstorm, and webstorm only has `tailwindcss` Intellisense, i noticed that unocss has `tailwindcss-preset`, it means i can use tailwindcss synatx to use unocss.
So it's possible to use unocss in webstorm with tailwindcss intellisense?

**Comment by panzhangguo** [comment] 2022-06-25 16:23
同  现在的问题不只是智能提示，很多unocss的写法直接报错。例如：<i i-icon-park-outline:search></i>；after:flex-auto after:content-none；等

**Comment by antfu** [comment] 2022-06-26 05:09
I don't use WebStorm myself. Counting on the community to come up with a WebStorm plugin. Later we could consider making it official or so.

**Comment by Xwudao** [comment] 2022-06-29 02:52
> I don't use WebStorm myself. Counting on the community to come up with a WebStorm plugin. Later we could consider making it official or so.

Webstorm implement Tailwindcss Intellisense because of it's LSP, does unocss has it's language server?

**Comment by shtse8** [comment] 2022-07-03 14:25
I am in need too. Anyone could provide this so that I don't need to check the interactive doc always.

**Comment by EvanMeek** [comment] 2022-08-26 01:39
> > 我自己不使用 WebStorm。指望社区想出一个 WebStorm 插件。稍后我们可以考虑将其正式化。
> 
> Webstorm 实现 Tailwindcss Intellisense 因为它提供 LSP，unocss 有语言服务器吗？

我赞成提供一个语言服务器，这样各大编辑器可以写一段简单的json配置即可

**Comment by antfu** [comment] 2022-08-26 06:07
I am also open to refactoring it into an LSP. PR also welcome on that direction.

**Comment by SnowingFox** [comment] 2022-08-30 01:44
> I am also open to refactoring it into an LSP. PR also welcome on that direction.

Could you provide the url about unocss LSP package?

**Comment by agileago** [comment] 2022-09-19 03:20
+1

**Comment by chz** [comment] 2022-10-10 21:32
+1

**Comment by meritozh** [comment] 2022-10-11 03:43
@SnowingFox it's a monorepo. https://github.com/unocss/unocss/tree/main/packages/vscode

**Comment by ouuan** [comment] 2022-10-11 03:52
> it's a monorepo. [`main`/packages/vscode](https://github.com/unocss/unocss/tree/main/packages/vscode?rgh-link-date=2022-10-11T03%3A43%3A48Z)

I think that's a VS Code extension, not an LSP server. No one said there is an LSP package. But there's an issue for LSP #869, which has been closed by the stale bot.

**Comment by adoin** [comment] 2023-04-18 05:50
> I don't use WebStorm myself. Counting on the community to come up with a WebStorm plugin. Later we could consider making it official or so.

大哥，windi的插件已经放弃了，这个也没下文吗？

**Comment by adoin** [comment] 2023-05-03 15:35
Already/
&nbsp;


adoin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shyam ***@***.***&gt;; 
发送时间: 2023年5月3日(星期三) 下午4:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [unocss/unocss] Webstorm Intellisense support (Issue #1166)





 
Should we move this issue to https://plugins.jetbrains.com/plugin-ideas?

**Comment by ylucifer** [comment] 2023-05-28 09:34
一年了，还是没有插件，可以放弃了。

**Comment by agileago** [comment] 2023-05-28 11:40
何弃疗

**Comment by ShivamJoker** [comment] 2023-06-10 17:19
@antfu any updates on the LSP? Would be great to get it to work properly with neovim as well.
Right now no proper LSP to migrate to.

**Comment by antfu** [comment] 2023-06-10 18:51
Again, this is an open-source project, the team and contributors work on it **voluntarily**. That said people are mostly driven by their own needs and not mandatorily responsible to anything. For this particular request, I personally don't have any incentive to implement the WebStorm plugin or the LSP, because I don't use them. But also, since this is an open-source project, we are open to accepting contributions for people who actually interested in them.

I am not able to represent all the team members, but as far as I know, **there is no plan for our team to work on this topic any sooner**. If you made one, we could also discuss joining the team to cover this missing area.

**Comment by SnowingFox** [comment] 2023-06-11 13:54
I have an plan to make a idea plugin for unocss

**Comment by adoin** [comment] 2023-06-11 14:06
> I have an plan to make a idea plugin for unocss

需要什么语言呢？

**Comment by re-ovo** [comment] 2023-06-26 11:50
https://github.com/re-ovo/unocss-intellij 🥰working on it

**Comment by badlym** [comment] 2023-07-06 02:00
如果你是从windicss转过来的，使用这个插件暂时可以解决webstorm的智能提示问题
https://github.com/windicss/windicss-analysis

**Comment by adoin** [comment] 2023-07-06 02:19
> 如果你是从windicss转过来的，使用这个插件暂时可以解决webstorm的智能提示问题 https://github.com/windicss/windicss-analysis

上面的大佬开发的插件已经非常好用了，我们在群里试了下，完美

**Comment by badlym** [comment] 2023-07-06 02:54
这个插件怎么安装啊，我看github上也没有明确说明

> > 如果你是从windicss转过来的，使用这个插件暂时可以解决webstorm的智能提示问题 https://github.com/windicss/windicss-analysis
> 
> 上面的大佬开发的插件已经非常好用了，我们在群里试了下，完美

**Comment by adoin** [comment] 2023-07-06 03:19
> 这个插件怎么安装啊，我看github上也没有明确说明
> 
> > > 如果你是从windicss转过来的，使用这个插件暂时可以解决webstorm的智能提示问题 https://github.com/windicss/windicss-analysis
> > 
> > 
> > 上面的大佬开发的插件已经非常好用了，我们在群里试了下，完美

已经在审核中了，别急，很快plugin市场就有了。
插件得群里面拿

**Comment by re-ovo** [comment] 2023-07-08 01:45
https://plugins.jetbrains.com/plugin/22204-unocss
done 🤗

**Comment by adoin** [comment] 2023-07-08 02:38
> https://plugins.jetbrains.com/plugin/22204-unocss done 🤗

@antfu  Plz help to broadcast, at least add this plugin to README.

**Comment by pauleveritt** [comment] 2023-07-08 08:37
Hi, I'm a developer advocate from JetBrains. Thanks for doing this!

**Comment by re-ovo** [comment] 2023-07-08 10:09
> Hi, I'm a developer advocate from JetBrains. Thanks for doing this! Curious to ask: does it use our just-announced LSP API?

No

**Comment by re-ovo** [comment] 2023-07-08 10:52
> Hi, I'm a developer advocate from JetBrains. Thanks for doing this! Curious to ask: does it use our just-announced LSP API?

Moreover, since you are a staff member of jetbrains, I want to say that jb's developer support is really bad, and there is always no reply or the reply is extremely slow, no matter on the official support website or slack.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/12152491079954-css-code-Highlighting-in-documentation

Can you explain why my question has not been answered for so many days?🙂

**Comment by pauleveritt** [comment] 2023-07-09 07:49
@re-ovo Sorry about that, I will poke around and ask our SDK advocates if the community forum is a place they participate in. If not, then who keeps an eye on it. Let me see if I can get the answer.

**Comment by pauleveritt** [comment] 2023-07-10 06:23
@re-ovo I heard back: "The question is marked as answered without our replies because they wrote that the problem is solved. And then, they asked another question in the answered topic, and I just missed it. I'll answer again." 

So: sorry about that! If it happens again, give me a nudge.

**Closed** 2023-07-16 12:15 UTC
Labels: help wanted, pr welcome
