### ISSUE TITLE
ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @unocss/preset-tagify@0.58.6

### ISSUE THREAD

**Issue by chufeng-official** [unocss/unocss#3622] opened 2024-03-15 00:18 UTC
### UnoCSS version

0.58.6

### Describe the bug

ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @unocss/preset-tagify@0.58.6

This error happened while installing the dependencies of @unocss/nuxt@0.58.6

The latest release of @unocss/preset-tagify is "0.58.5".

### Reproduction

run
```shell
pnpm up --latest
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chufeng-official** [comment] 2024-03-15 00:36
Running
```shell
pnpm add -D @unocss/nuxt@0.58.6
```
can also trigger this bug

**Comment by antfu** [comment] 2024-03-15 01:26
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-15 01:26 UTC
