### ISSUE TITLE
 Nuxt Build Error: [unocss:global:build:scan] [postcss] /Users/[route…]/server.mjs-unocss-hash.css:1:6400: Unknown word

### ISSUE THREAD

**Issue by Jorckx** [unocss/unocss#4312] opened 2024-12-05 11:37 UTC
### UnoCSS version

^0.65.1

### Describe the bug

Recently when building my Nuxt (v3.11.2) app through `pnpm` I run into this error:
Nuxt Build Error: [unocss:global:build:scan] [postcss] /Users/[route…]/server.mjs-unocss-hash.css:1:6400: Unknown word

When I set the global ssr-setting to `false` it builds correctly. When I add the wildcard `/*` in my routeRules as `ssr: true`in combination with global ssr set to `false` it also works.

Can someone help me understand what this might mean? Or is it really just a typo i should look for? To my knowledge if i look at my commits there's no css-difference between before the error and after the error. 

Looking into a reproduction (of the more extensive repo) if the provided log is not enough.

### Reproduction

```
vite v5.4.11 building SSR bundle for production...                                                       12:32:27 PM
ℹ ✓ 373 modules transformed.                                                                               12:32:28 PM

 ERROR  x Build failed in 1.71s                                                                             12:32:28 PM


[12:32:28 PM]  ERROR  Nuxt Build Error: [unocss:global:build:scan] [postcss] /Users/joredierckx/Documents/_1/localhost/2024/2024 | MUCE/MUCE--frontend/server.mjs-unocss-hash.css:1:6400: Unknown word

  at Input.error (node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/input.js:106:16)
  at Parser.unknownWord (node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parser.js:593:22)
  at Parser.other (node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parser.js:435:12)
  at Parser.parse (node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parser.js:470:16)
  at parse (node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/parse.js:11:12)
  at new LazyResult (node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/lazy-result.js:133:16)
  at Processor.process (node_modules/.pnpm/postcss@8.4.49/node_modules/postcss/lib/processor.js:53:14)
  at compileCSS (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/vite@5.4.11_@types+node@20.17.9_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36897:59)
  at async Object.transform (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/vite@5.4.11_@types+node@20.17.9_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36170:11)
  at async applyCssTransform (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/@unocss+vite@0.62.4_rollup@4.28.0_vite@5.4.11_@types+node@20.17.9_terser@5.36.0_/node_modules/@unocss/vite/dist/index.mjs:539:20)
  at async Object.renderChunk (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/@unocss+vite@0.62.4_rollup@4.28.0_vite@5.4.11_@types+node@20.17.9_terser@5.36.0_/node_modules/@unocss/vite/dist/index.mjs:651:15)
  at async transformChunk (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:18853:16)
  at async /Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:18927:17
  at async Promise.all (index 0)
  at async transformChunksAndGenerateContentHashes (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:18922:5)
  at async renderChunks (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:18831:151)
  at async Bundle.generate (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:19089:13)
  at async /Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21776:27
  at async catchUnfinishedHookActions (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21158:16)
  at async Module.build (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/vite@5.4.11_@types+node@20.17.9_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65449:16)
  at async buildServer (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/@nuxt+vite-builder@3.11.2_@types+node@20.17.9_eslint@9.16.0_jiti@2.4.1__magicast@0.3.5_option_q5zoo224frnrze3ch5a7g4r77i/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.Cz3sykDo.mjs:781:5)
  at async bundle (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/@nuxt+vite-builder@3.11.2_@types+node@20.17.9_eslint@9.16.0_jiti@2.4.1__magicast@0.3.5_option_q5zoo224frnrze3ch5a7g4r77i/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.Cz3sykDo.mjs:1587:3)
  at async bundle (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.0_@types+node@20.17.9_eslint@9.16.0_jiti@2.4.1__ioredis@5.4.1_gjyzd2gydzns2hz62374onsi7m/node_modules/nuxt/dist/index.mjs:5125:5)
  at async Promise.all (index 1)
  at async build (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/nuxt@3.11.2_@parcel+watcher@2.5.0_@types+node@20.17.9_eslint@9.16.0_jiti@2.4.1__ioredis@5.4.1_gjyzd2gydzns2hz62374onsi7m/node_modules/nuxt/dist/index.mjs:5000:5)
  at async Object.run (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/build.mjs:104:5)
  at async runCommand$1 (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1648:16)
  at async runCommand$1 (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1639:11)
  at async runMain$1 (/Users/joredierckx/Documents/_1/localhost/2024/2024%20|%20MUCE/MUCE--frontend/node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1777:7)

 ELIFECYCLE  Command failed with exit code 1.
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2024-12-07 12:01
Can you provide a minimal reproduction?

**Comment by zyyv** [comment] 2024-12-18 14:35
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2024-12-18 14:35 UTC
Labels: needs reproduction
