### ISSUE TITLE
nuxt3 vscode No code prompt ；console output Error: Cannot find module 'unocss'

### ISSUE THREAD

**Issue by fjh1610** [unocss/unocss#3738] opened 2024-04-17 07:10 UTC
### UnoCSS version

^0.59.3

### Describe the bug

nuxt3 vscode No code prompt ；console output Error: Cannot find module 'unocss'，Dependencies are installed
![image](https://github.com/unocss/unocss/assets/85326708/dd9c3b40-ab87-4a47-8b38-ef35e360ad3e)

![image](https://github.com/unocss/unocss/assets/85326708/cf7b301f-886d-44ee-a756-e875611e9877)

### Reproduction

no link

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by douxuefeng666** [comment] 2024-04-17 16:13
I have the same question , plz help!!

**Comment by Simon-He95** [comment] 2024-04-18 01:00
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-04-18 01:00 UTC

**Comment by fjh1610** [comment] 2024-04-18 06:25
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.由于缺乏足够的信息，我们暂时关闭了它。我们无法确定这是错误还是给定信息的用户空间配置错误。 Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.请提供最低限度的复制品以重新打开该问题。 Thanks. 谢谢。
> 
> > [Why reproduction is required 为什么需要复制](https://antfu.me/posts/why-reproductions-are-required)

It's done exactly as per the documentation, I don't know what else to provide

**Comment by Simon-He95** [comment] 2024-04-18 07:25
> > We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.由于缺乏足够的信息，我们暂时关闭了它。我们无法确定这是错误还是给定信息的用户空间配置错误。 Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.请提供最低限度的复制品以重新打开该问题。 Thanks. 谢谢。
> > > [Why reproduction is required 为什么需要复制](https://antfu.me/posts/why-reproductions-are-required)
> 
> It's done exactly as per the documentation, I don't know what else to provide

If you follow the documentation, you can create a new project and provide a link to reproduce it, because it is very likely that we will not encounter the same problem as you.

**Comment by WaterAndBin** [comment] 2024-07-09 14:40
me too.I have the same problem.and I think the easily to solve is download Unocss. You package.json can have @Unocss/nuxt and Unocss. I used that that solve your problem and features is not problem and using in normal.

**Comment by florianjs** [comment] 2024-07-10 09:22
> ### UnoCSS version
> ^0.59.3
> 
> ### Describe the bug
> nuxt3 vscode No code prompt ；console output Error: Cannot find module 'unocss'，Dependencies are installed ![image](https://private-user-images.githubusercontent.com/85326708/323116269-dd9c3b40-ab87-4a47-8b38-ef35e360ad3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDM2MDksIm5iZiI6MTcyMDYwMzMwOSwicGF0aCI6Ii84NTMyNjcwOC8zMjMxMTYyNjktZGQ5YzNiNDAtYWI4Ny00YTQ3LThiMzgtZWYzNWUzNjBhZDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZmI1Y2M0MzVkZTAzMDIxY2U5ZjVmNTZhMWJkMGIwMGNiMWNmZWQzOGE4ODZlNGY5ZTRkOWM5NjcyYWVjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gV_Uq9oNYluQfNSfER2SVa-yh0EEhkc3WYjJ0kuPwC0)
> 
> ![image](https://private-user-images.githubusercontent.com/85326708/323115083-cf7b301f-886d-44ee-a756-e875611e9877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDM2MDksIm5iZiI6MTcyMDYwMzMwOSwicGF0aCI6Ii84NTMyNjcwOC8zMjMxMTUwODMtY2Y3YjMwMWYtODg2ZC00NGVlLWE3NTYtZTg3NTYxMWU5ODc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MjIzNTJhNjBmNWQ5MGY0NzQzYTAxMzk1ZTBmYjQ4YzJiMWFhYjkyN2QwYjg2NmUwNGI4NTk1NjM5Njk3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BL5BeBvgoRqi2bf1QcIa2lLIo11QnnZhfGq9wtRB4Zw)
> 
> ### Reproduction
> no link
> 
> ### System Info
> _No response_
> 
> ### Validations
> * [x]  Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

https://github.com/unocss/unocss/issues/3844#issuecomment-2133772410
