### ISSUE TITLE
[vscode extenstion] reset theme don't show colors in vscode 

### ISSUE THREAD

**Issue by moHaHa** [unocss/unocss#3479] opened 2023-12-31 11:19 UTC
### UnoCSS version

0.58.2

### Describe the bug

![photo_2023-12-31 03 18 08](https://github.com/unocss/unocss/assets/72744132/f4d7366e-2b01-4841-a486-73f4dc4f6624)

![photo_2023-12-31 03 18 12](https://github.com/unocss/unocss/assets/72744132/d725e228-51db-43d0-8d2c-be13ac7dd717)

### Reproduction

.

### System Info

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-01-01 03:59
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-01 03:59 UTC
