### ISSUE TITLE
Attributify Mode Error

### ISSUE THREAD

**Issue by Scouterdev** [unocss/unocss#1122] opened 2022-06-20 10:10 UTC
**Solidjs** with **Vite** and **Unocss**, **TypeScript Enable**

Module app: **@unocss/preset-attributify**
Add examples for [here](https://github.com/unocss/unocss/tree/main/examples/vite-solid)

install npm > npm run dev

and have error.. **TypeError: extractor.extract is not a function**

`Type 'Preset' is not assignable to type 'Preset<{}> | Preset<{}>[]'.
  Property 'name' is missing in type 'Preset' but required in type 'Preset<{}>'.`

**Comment by antfu** [comment] 2022-07-09 06:26
The example failed due to they are referencing different Vite installations. Or do you have the problem in a real project?

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-09 06:26 UTC
