### ISSUE TITLE
version 0.55.0   '@unocss/core' does not provide an export named 'CountableSet'

### ISSUE THREAD

**Issue by 6313504** [unocss/unocss#2977] opened 2023-08-12 06:16 UTC
### Clear and concise description of the problem

when i use version 0.55.0

```shell
packages\desktop\electron.vite.config.ts
error during start dev server and electron app:
file:///E:/code/2023/%E4%BB%AA%E5%BE%81%E4%B8%8D%E5%8A%A8%E4%BA%A7%E7%94%B3%E6%8A%A5%E6%9C%BA/code/sbj-app/node_modules/.pnpm/@unocss+inspector@0.55.0/node_modules/@unocss/inspector/dist/index.mjs:4
import { escapeSelector, createValueHandler, isString, escapeRegExp, CountableSet, BetterMap } from '@unocss/core';
                                                                     ^^^^^^^^^^^^
SyntaxError: The requested module '@unocss/core' does not provide an export named 'CountableSet'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
 ELIFECYCLE  Command failed with exit code 1.
```

then change version to 0.54.3.
there is no problem

### Suggested solution

change version to 0.54.3.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by codesyofo** [comment] 2023-08-14 01:44
是不是装了其他预设，镜像源没有同步到最新版本，目前看是已经同步了

**Comment by 6313504** [comment] 2023-08-14 02:37
可能吧&nbsp; 我用的自己的私服镜像



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 14, 2023 09:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [unocss/unocss] version 0.55.0   ***@***.***/core' does not providean export named 'CountableSet' (Issue #2977)




 
是不是装了其他预设，镜像源没有同步到最新版本，目前看是已经同步了

**Comment by antfu** [comment] 2023-08-14 07:54
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-14 07:54 UTC

**Comment by ash0080** [comment] 2023-08-18 16:37
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

https://github.com/unocss/unocss/blame/main/packages/core/src/types.ts#:~:text=%2C-,CountableSet,-%7D

看了下似乎确实没有export, @0.55.1

**Comment by alshdotme** [comment] 2023-09-05 18:59
Seems a subpackage was pulling an older version of `@unocss/core`

Setting it to resolve a specific version solved this issue for me.

```
  "resolutions": {
     "@unocss/core": "^0.55.7"
  }
```

**Comment by michealroberts** [comment] 2023-09-06 15:37
A few questions: 

- Is this issue happening inside a monorepo with multiple projects / apps / packages etc
- Do you have any ignore example / playground apps in your 

If yes to either of the above, you might have different versions of unocss installed ...

**Comment by userquin** [comment] 2023-09-09 15:36
I can reproduce the error when using it in VitePress rc10:

![imagen](https://github.com/unocss/unocss/assets/6311119/5b2686f3-e07d-4a29-936e-f3524d785bb9)

**Comment by beejaz** [comment] 2023-10-28 08:30
> Seems a subpackage was pulling an older version of `@unocss/core`
> 
> Setting it to resolve a specific version solved this issue for me.
> 
> ```
>   "resolutions": {
>      "@unocss/core": "^0.55.7"
>   }
> ```

Had to add same but for 0.57.1 to fix my issue with CountableSet.

Thanks.
