### ISSUE TITLE
Error: Dependency Cycle Found

### ISSUE THREAD

**Issue by t0mri** [unocss/unocss#3343] opened 2023-11-16 10:32 UTC
### UnoCSS version

0.57.4

### Describe the bug

an unnecessary dependency cycle. refer bug reproduction for details 

### Reproduction

```vim
-- file structure --

root dir
    |- src
        |- stylesheets
            |- course.css
    |- package.json
    |- postcss.config.js
    |- uno.config.ts
```
```typescript
// package.json

...
  "scripts": {
    "dev": "bun run --watch src/server.tsx",
    "devCSS": "postcss src/stylesheets/*.css --dir public/stylesheet -w"
  },
...
```
```typescript
// posctcss.config.js

export default {
  plugins: {
    "@unocss/postcss": {},
    cssnano: {},
  },
};
```
```typescript
// uno.config.ts
import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
  content: {
    filesystem: [
      '**/*.tsx',
    ]
  },
  presets: [
    presetUno(),
  ],
})
```
```css
/* course.css */

[title="Pause"] {
  display: none;
}

pre[class*="language-"] {
  @apply bg-glass;
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-11-16 10:38
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-16 10:38 UTC

**Comment by t0mri** [comment] 2023-11-22 09:41
# Steps to reproduce

#### 1. Open or create a clean empty dir.
#### 2. Installing dependencies
```bash
bun add postcss postcss-cli unocss @unocss/postcss
```
#### 3. Create posctcss.config.json
```typescript
// posctcss.config.js

export default {
  plugins: {
    "@unocss/postcss": {}
  },
};
```
#### 4. Create uno.config.ts
```typescript
// uno.config.ts

import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
  ],
})
```
#### 5. Modify package.json
```typescript
// package.json

{
  "type": "module",
  "scripts": {
    "devCSS": "postcss src/*.css --dir dist -w"
  },
  "dependencies": {
    // dependencies
  }
}
```
#### 6. Create `index.css` inside `src` folder
```bash
mkdir src
touch src/index.css
```
### 7. Use `@apply` in `index.css`
```css
body {
  @apply bg-red;
}
```
#### 8. Run postcss script (`devCSS`)
```bash
bun devCSS
```
> At this point, it will produce the output CSS with no issue the first time. But now,
#### 9. Go to index.css and save it twice while the devCSS script is still running, then go back to the terminal
## Thus this issue
The terminal output is as follows:
```bash
tomri:/mnt/t/tomri/dev/uno $ bun devCSS
$ postcss src/*.css --dir dist -w
/mnt/t/tomri/dev/uno/node_modules/dependency-graph/lib/dep_graph.js:43
          throw new DepGraphCycleError(currentPath);
          ^

Error: Dependency Cycle Found: /mnt/t/tomri/dev/uno/src/index.css -> /mnt/t/tomri/dev/uno/src/index.css
    at /mnt/t/tomri/dev/uno/node_modules/dependency-graph/lib/dep_graph.js:43:17
    at DepGraph.dependantsOf (/mnt/t/tomri/dev/uno/node_modules/dependency-graph/lib/dep_graph.js:263:7)
    at Object.dependantsOf (file:///mnt/t/tomri/dev/uno/node_modules/postcss-cli/lib/DependencyGraph.js:26:45)
    at FSWatcher.<anonymous> (file:///mnt/t/tomri/dev/uno/node_modules/postcss-cli/index.js:145:12)
    at FSWatcher.emit (node:events:515:28)
    at FSWatcher.emitWithAll (/mnt/t/tomri/dev/uno/node_modules/chokidar/index.js:540:8)
    at awfEmit (/mnt/t/tomri/dev/uno/node_modules/chokidar/index.js:607:14)
    at /mnt/t/tomri/dev/uno/node_modules/chokidar/index.js:728:9
    at FSReqCallback.oncomplete (node:fs:200:5) {
  cyclePath: [
    '/mnt/t/tomri/dev/uno/src/index.css',
    '/mnt/t/tomri/dev/uno/src/index.css'
  ]
}

Node.js v21.1.0
error: script "devCSS" exited with code 1 (SIGHUP)
```
