### ISSUE TITLE
After using the autoprefixer preset, vscode extensions stopped working.

### ISSUE THREAD

**Issue by hestudy** [unocss/unocss#3178] opened 2023-09-27 08:22 UTC
### UnoCSS version

0.53.1

### Describe the bug

For compatibility with older browsers, I have introduced the community's preset `unocss-preset-autoprefixer`.

But it seems to have disrupted the operation of vscode extensions, and I can no longer get CSS intelligent prompts and previews.

It is confusing that the error of expanding output is empty.

![image](https://github.com/unocss/unocss/assets/46753332/9173ec32-01d9-4815-a831-1ad2108c6a08)

The culprit of everything is it, remove it and expansion can work normally.

![image](https://github.com/unocss/unocss/assets/46753332/ca4e0efc-ab59-408f-8514-170c14014da2)

But what is even more confusing is that the CLI program of unocss can run normally, seemingly everything is normal except for the vscode extension.

I don't understand if it's a preset issue or an expansion issue, so I also reported this error in the preset repository.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-yxv2n6?file=vite.config.ts

**You can reproduce it in the vscode editor with the unocss extension installed.**

![image](https://github.com/unocss/unocss/assets/46753332/28fdb5d0-c2c5-44dd-aa07-f94c7240871f)

In normal working condition, it should have an underline and can be previewed.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chengpeiquan** [comment] 2023-11-13 03:13
Me too! Seems like there's no progress?

**Comment by chengpeiquan** [comment] 2023-11-13 06:35
> Me too! Seems like there's no progress?

I spent my lunch break on troubleshooting. It seems to be caused by the API of lightningcss. I have now changed to configuring the postcss option in vite.config.ts to deal with the prefix problem. I'll just have to not use this preset until this problem is solved, It’s really Egg-Pain to have no code prompts.

```ts
// vite.config.ts
import autoprefixer from 'autoprefixer';

export default defineConfig({
  // ...
  css: {
    postcss: {
      plugins: [autoprefixer()],
    },
  },
})
```

**Comment by hestudy** [comment] 2023-11-13 06:39
> > Me too! Seems like there's no progress?我也是！似乎没有进展？
> 
> I spent my lunch break on troubleshooting. It seems to be caused by the API of lightningcss. I have now changed to configuring the postcss option in vite.config.ts to deal with the prefix problem. I'll just have to not use this preset until this problem is solved, It’s really Egg-Pain to have no code prompts.我在午餐休息时间解决问题。看起来是由于lightningcss的API引起的。我现在已经改为在vite.config.ts中配置postcss选项来处理前缀问题。在这个问题解决之前，我只能不使用这个预设，没有代码提示真的很痛苦。
> 
> ```ts
> // vite.config.ts
> import autoprefixer from 'autoprefixer';
> 
> export default defineConfig({
>   // ...
>   css: {
>     postcss: {
>       plugins: [autoprefixer()],
>     },
>   },
> })
> ```

Try updating your preset version, it seems that the author of autoprefixer has already solved the problem.
[issues](https://github.com/unpreset/unocss-preset-autoprefixer/issues/6)

Currently, I can use the extension normally on my side.

**Comment by chengpeiquan** [comment] 2023-11-13 06:48
> > > Me too! Seems like there's no progress?我也是！似乎没有进展？
> > 
> > 
> > I spent my lunch break on troubleshooting. It seems to be caused by the API of lightningcss. I have now changed to configuring the postcss option in vite.config.ts to deal with the prefix problem. I'll just have to not use this preset until this problem is solved, It’s really Egg-Pain to have no code prompts.我在午餐休息时间解决问题。看起来是由于lightningcss的API引起的。我现在已经改为在vite.config.ts中配置postcss选项来处理前缀问题。在这个问题解决之前，我只能不使用这个预设，没有代码提示真的很痛苦。
> > ```ts
> > // vite.config.ts
> > import autoprefixer from 'autoprefixer';
> > 
> > export default defineConfig({
> >   // ...
> >   css: {
> >     postcss: {
> >       plugins: [autoprefixer()],
> >     },
> >   },
> > })
> > ```
> 
> Try updating your preset version, it seems that the author of autoprefixer has already solved the problem. [issues](https://github.com/unpreset/unocss-preset-autoprefixer/issues/6)
> 
> Currently, I can use the extension normally on my side.

I saw that this issue was marked as resolved, but I am current using the latest version "0.0.7" and the problem still exists in my project.
There is no attempt to minimize the demo for the time being. It may also be caused by conflicts with other plug-ins.
I've managed it through the Vite configuration for now, Thx!

**Closed** 2023-11-13 06:50 UTC
