### ISSUE TITLE
some errors in using 'uno. config. ts'.

### ISSUE THREAD

**Issue by hequ9** [unocss/unocss#1668] opened 2022-09-30 10:36 UTC
`vite@3.1.4` `unocss@0.45.26`

my `uno.config.ts`:
```ts
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons(),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
})

```
and vscode extension is also successfully loaded it, but when i started vite, i got a error:
![微信截图_20220930182424](https://user-images.githubusercontent.com/49673052/193250395-0af825a1-f492-4130-88fd-670387b2daac.png)

it doesn't seem to be loaded correctly.
I try to use `vite.config.ts` to configure it and it's ok,is this a bug?

**Comment by antfu** [comment] 2022-09-30 10:57
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-09-30 10:57 UTC
