### ISSUE TITLE
the warning user @unocss/webpack with webpack fileSystem cache

### ISSUE THREAD

**Issue by yejinjian** [unocss/unocss#4010] opened 2024-07-24 11:10 UTC
### UnoCSS version

0.61.5

### Describe the bug

when use @unocss/webpack in webpack@5.93.0
here is the warning info in console
```
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\local-pkg\dist\index.mjs for build dependencies failed at 'import(path)'.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\local-pkg\dist\index.mjs for build dependencies failed at 'import(path)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\unimport\dist\index.mjs for build dependencies failed at 'import(i.from)'.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\unimport\dist\index.mjs for build dependencies failed at 'import(i.from)'.
.mjs for build dependencies failed at 'import(i.from)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\mlly\dist\index.mjs<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\mlly\dist\index.mjs for build dependencies failed at 'import(dataURL)'.
 for build dependencies failed at 'import(dataURL)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\importx\dist\index.mjs for build dependencies failed at 'import(fullPath)'.
mjs for build dependencies failed at 'import(fullPath)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\neo\app\iretail-web-front\node_modules\bundle-require\dist\index.js for build dependencies failed at 'import(file)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
```

### Reproduction

my webpack config: 
```javascript
import UnoCss from '@unocss/webpack'

export default {
    ....,
   plugins: [
      ...,
      UnoCss()
   ],
   cache: {
            type: 'filesystem',
            buildDependencies: {
                config: [__filename],
            }
        },
}
```

my uno config
```
import presetUno from '@unocss/preset-uno'

export default {
    preflights: false,
    content: {
        filesystem: [
            'src/new/**/*.{html,js,ts,jsx,tsx,vue}',
        ],
    },
    presets: [
        presetUno({ preflight: false }),
    ],
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-07-29 13:15
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-29 13:15 UTC
Labels: webpack
