### ISSUE TITLE
Syntax Error with @screen directive when using SCSS nesting (Nuxt.js)

### ISSUE THREAD

**Issue by MuratBuyukcelebi** [unocss/unocss#3971] opened 2024-07-10 12:18 UTC
### UnoCSS version

0.61.3

### Describe the bug

I'm encountering a syntax error when using 
the @screen directive with SCSS nesting in a Nuxt.js project. 
Console error: `[WARNING] Expected "{" but found "}" [css-syntax-error]`
Build code:
![imaaaaaaage](https://github.com/unocss/unocss/assets/73561693/2af75431-fbe6-4c91-a290-27f9dc5313b3)

### Reproduction

1. create nuxt project, install uno 0.61.3 and scss
```
@screen lt-md {
      .footer {
        &-header {
          display: flex;
        }
      }
    }
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-07-13 08:37
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-07-13 08:37 UTC
