### ISSUE TITLE
about dynamic attributify mode

### ISSUE THREAD

**Issue by Handpear** [unocss/unocss#1915] opened 2022-11-25 08:20 UTC
Hello guys,

I have a class need to use attributify mode,

`pos="!fixed"` it's working

`pos={isSideFixed ? '!fixed' : 'relative'}` it's not working

How do I get the corresponding css generated in advance? using the `safelist` ?

**Comment by antfu** [comment] 2022-11-25 08:37
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-11-25 08:37 UTC

**Comment by Handpear** [comment] 2022-11-25 09:10
![image](https://user-images.githubusercontent.com/40299372/203942123-26525723-5a76-4d14-8964-00c4c522fd4f.png)

`fixed` and `relative` has extracted but not working like other attributify

[minimal reproduction](https://github.com/Handpear/unocss-test)

**Comment by Handpear** [comment] 2022-11-25 09:11
It doesn't seem to be antd5 problem either

**Comment by Handpear** [comment] 2022-11-25 09:13
@zyyv

**Comment by zyyv** [comment] 2022-11-25 09:18
This does not affect anything, because unocss is a static analysis, and extracts the token to generate css.

**Comment by Handpear** [comment] 2022-11-25 09:41
I don't understand how this could be invalid, it's working in windicss..

**Comment by sibbng** [comment] 2022-11-26 16:21
@Handpear I made a PR to fix this issue: #1921

In the meantime, you could you this roughly written extractor:

[Test it in playground](https://uno.antfu.me/play/?html=DwEwlgbgUABDAOB7AzgXgN5mQZTCApgGJgAe%2BIMA-DAOQCEAZqeTTAFy0BO%2BANgIYAXSPhoBfKAHoAfFCA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFZs9hIw0HQAXHAA2v6ocLj2IBiRejAYUAlQ-AC0gVDBoVB6sgGWQSE%2BIZYAlIhUcXBOjHB0cAC8cFUAdFKY9XFSuHTw8s4wrR1RALr9qIPDcLTtcAD0ADxRADoA7l1TANRRAHoAfFMAVAD84Zc%2B1z5b29kH1W0xegBEUz5d%2B7fXXWqV02l32d3CgKu4Kin2%2Bx1h%2B2qMK%2B-3Cm1wAB9IfcAUDLsi4UcEUjYZdqki1LDwdjqvsVqQQHRZo1miB7DAJAALZnbTnAJpwHxsjmc5a0LpWDASHx0cl1BoNCYtLq0MBOYIYIXsrlRABMU3I%2Bj01WZqHF6uGYlwmEsywADKbOtJ4Oy2MthTqAIwzBVxPg%2BV1QdptDp6CQW0xwDEYuCB4Oh8P2EwAOUSGGNTtwvFwXAwjvm8CaWHgHQ9nKiAGYfb6WcWunQ1cAYD49Ppql0sNAAKLBTk%2BYDtE6LehjOhdMBcOh9gAGUQAJAhA2oAH5tD4L4BqL7T8n552LbycktwMtRAAs1d97FIR-rjebreNHe7vf7g%2BHdFH48nM-ni9YUArmuG5blMO4mjWmZ0BATRdE4EC%2BKMLiysyajMrQMBcBkH6jv0aiyGoBpUFAzj0JEUT9DCEiTqEIDZCRTTFIgTrwVAKS0GgraEVQRGoFO0AcjwETynEYY0To2T8bA1EwHoKRpGU2ROKQcAKTA2TQPYuCkBgcCchAABu6ThGp2RpPYThmKg%2BFUCICjCRRDR2YwygQD41QlHIojMABnA8Hw-DuZ5zkwJI0h%2BMydASBZyRwJ6XS6p5cxoLgKRHjAYARCsKz0CA9acisVlxGoHk8UgJVIEAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

```ts
export default defineConfig({
  extractors: [{
  name: 'ternary-extractor',
  extract(ctx) {
    let s = ctx.code
    const results = []
    const re = /<[\w.]+[^>]*?:?(?:([\w-]+)=[{'"](.+?(?:.)*?\?+(?:.)*?(?:['"]([^'"]+)['"]?(?:.)*?:(?:.)*?['"]([^'"]+)['"]?))[}'"](?:.)*?)+/gms
    let match
    while (match = re.exec(s)) {
      s = s.replace(match[2], '')
      re.lastIndex = 0
      const attr = match[1]
      if(attr === 'class' || attr === 'className') continue
      const left = match[3]
      left.split(' ').forEach(i => results.push(`[${attr}~="${i}"]`))
      const right = match[4]
      right.split(' ').forEach(i => results.push(`[${attr}~="${i}"]`))
      console.log(results)
    }
    return results
  },
}],
  ```

**Comment by zyyv** [comment] 2022-11-26 16:43
@sibbng Can you check your pr with this [playground](https://uno.antfu.me/play/?html=DwEwlgbgUABDAOB7AzgXgN5mQZTCApgGJgAe%2BIMA-DAOQCEAZqeTTAFy0BO%2BANgIYAXSPhoBfWAhQAVfMgEYsuAsTIVq9AfhICAtNxCsONTdp2a%2BPMVAD0APihA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFZs9hIw0HQAXHAA2v6ocLj2IBiRejAYUAlQ-AC0gVDBoVB6sgGWQSE%2BIZYAlIhUcXBOjHB0cAC8cFUAdFKY9XFSuHTw8s4wrR1RALr9qIPDcLTtcAD0ADxRADoA7l1TANRRAHoAfFMAVAD84Zc%2B1z5b29kH1W0xegBEUz5d%2B7fXXWqV02l32d3CgKu4Kin2%2Bx1h%2B2qMK%2B-3Cm1wAB9IfcAUDLsi4UcEUjYZdqki1LDwdjqvsVqQQHRZo1miB7DAJAALZnbTnAJpwHxsjmc5a0LpWDASHx0cl1BoNCYtLq0MBOYIYIXsrlRABMU3I%2Bj01WZqHF6uGYlwmEsywADKbOtJ4Oy2MthTqAIwzBVxPg%2BV1QdptDp6CQW0xwDEYuCB4Oh8P2EwAOUSGGNTtwvFwXAwjvm8CaWHgHQ9nKiAGYfb6WcWunQ1cAYD49Ppql0sNAAKLBTk%2BYDtE6LehjOhdMBcOh9gAGUQAJAhA2oAH5tD4L4BqL7T8n552LbycktwMtRAAs1d97FIR-rjebreNHe7vf7g%2BHdFH48nM-ni9YUArmuG5blMO4mjWmZ0BATRdE4EC%2BKMLiysyajMrQMBcBkH6jv0aiyGoBpUFAzj0JEUT9DCEiTqEIDZCRTTFIgTrwVAKS0GgraEVQRGoFO0AcjwETynEYY0To2T8bA1EwHoKRpGU2ROKQcAKTA2TQPYuCkBgcCchAABu6ThGp2RpPYThmKg%2BFUCICjCRRDR2YwygQD41QlHIojMABnA8Hw-DuZ5zkwJI0h%2BMydASBZyRwJ6XS6p5cxoLgKRHjAYARCsKz0CA9acisVlxGoHk8UgJVIEAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by Handpear** [comment] 2022-11-28 00:58
@sibbng Thank you
