### ISSUE TITLE
transformCompileClass not working

### ISSUE THREAD

**Issue by ARZarkesh** [unocss/unocss#2580] opened 2023-05-06 09:44 UTC
### UnoCSS version

0.38.1

### Describe the bug

the transformerCompileClass not works when it is used with include option in unocss.config.ts

when i remove include option, it works properly.

### Reproduction

// unocss.config.ts

import { defineConfig, presetUno, presetIcons, transformerVariantGroup, transformerCompileClass, transformerDirectives } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons(),
  ],
  include: [
    './src/**/*.{vue,ts,tsx}',
  ],
  transformers: [
    transformerCompileClass({ layer: 'components', classPrefix: 'n-' }),
    transformerVariantGroup(),
    transformerDirectives(),
  ],
})

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2023-05-06 10:33
Can you upgrade UnoCSS version and try again? Or provide a minimal repo.

**Comment by zyyv** [comment] 2023-05-06 10:33
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2023-05-06 10:33 UTC
