### ISSUE TITLE
在 vite 开发环境中 开启 presetAttributify 功能会导致浏览器内存高涨占满

### ISSUE THREAD

**Issue by miaojinsing** [unocss/unocss#4035] opened 2024-07-31 09:31 UTC
### UnoCSS version

0.60.2

### Describe the bug

在 vite 开发环境中 开启 presetAttributify 功能会导致浏览器内存高涨占满

### Reproduction

在 vite 开发环境中 开启 presetAttributify 功能会导致浏览器内存高涨占满

### System Info

mac 谷歌浏览器  windows10 edge浏览器

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-07-31 13:51
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-31 13:51 UTC
