### ISSUE TITLE
@unocss/runtime的捆绑器使用不起作用

### ISSUE THREAD

**Issue by daixiangwen** [unocss/unocss#3753] opened 2024-04-23 08:37 UTC
### UnoCSS version

0.58.6

### Describe the bug

我在mian.js中配置了
![image](https://github.com/unocss/unocss/assets/40290758/204b6f3a-1323-4dcb-b3e8-776b2e4a66fc)
在js动态赋值的时候无法生成css
![image](https://github.com/unocss/unocss/assets/40290758/d5f74151-8054-4fa0-ae8d-4731115b8d50)

### Reproduction

无

### System Info

无

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-04-23 08:45
I think you can take a look at the demo and test use cases first, which may solve your doubts.
https://github.com/unocss/unocss/blob/main/packages/runtime/play/index.html
https://github.com/unocss/unocss/blob/main/test/runtime-dom.test.ts

**Comment by daixiangwen** [comment] 2024-04-23 08:56
> I think you can take a look at the demo and test use cases first, which may solve your doubts. https://github.com/unocss/unocss/blob/main/packages/runtime/play/index.html https://github.com/unocss/unocss/blob/main/test/runtime-dom.test.ts

Hello, can you give me an example directly? I really didn't call it out on my side, rookie player.

**Comment by daixiangwen** [comment] 2024-04-23 09:01
> I think you can take a look at the demo and test use cases first, which may solve your doubts. https://github.com/unocss/unocss/blob/main/packages/runtime/play/index.html https://github.com/unocss/unocss/blob/main/test/runtime-dom.test.ts

Or where is it configured and used? I consulted here because I didn't understand it.

**Comment by Simon-He95** [comment] 2024-04-23 10:03
I have never used this API. You can try it yourself first. If I have time, I can study it later.

**Comment by daixiangwen** [comment] 2024-04-24 01:16
> 我从未使用过这个 API。你可以先自己试试。如果我有时间，我可以稍后学习它。

Thank you, I just did not succeed, so I asked here, if it is convenient for you, you can try, and then tell me, thank you very much!

**Comment by antfu** [comment] 2024-04-24 01:36
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-24 01:36 UTC
