### ISSUE TITLE
Using unocss in react + vite results in an error "hook is not a function"

### ISSUE THREAD

**Issue by AarNtyon** [unocss/unocss#3351] opened 2023-11-18 15:02 UTC
### UnoCSS version

^0.57.5

### Describe the bug

Use unocss according to this document  [unocss/vite](https://unocss.dev/integrations/vite)
![image](https://github.com/unocss/unocss/assets/49551405/6808232f-7a5b-41fc-bab7-7fab9242b2e5)

### Reproduction

!

### System Info

{
  "name": "hello unocss",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20.9.1",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@vitejs/plugin-react": "^2.1.0",
    "typescript": "^4.6.4",
    "unocss": "^0.57.5",
    "vite": "^3.1.0"
  }
}

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AarNtyon** [comment] 2023-11-18 15:07
![image](https://github.com/unocss/unocss/assets/49551405/13809987-cdfd-4ea3-b29a-6c284adcac79)

**Comment by zyyv** [comment] 2023-11-18 15:12
Are you sure this is a Uno problem?

**Comment by zyyv** [comment] 2023-11-18 15:12
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2023-11-18 15:12 UTC
