### ISSUE TITLE
Icons do not get loaded in shadow-dom

### ISSUE THREAD

**Issue by davidboom95** [unocss/unocss#1106] opened 2022-06-16 17:07 UTC

**Comment by userquin** [comment] 2022-06-17 12:42
@davidboom95 the logo on `vite-lit` example is not working?

**Comment by antfu** [comment] 2022-06-18 11:15
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-18 11:15 UTC
