### ISSUE TITLE
Unocss Class not correctly resolved

### ISSUE THREAD

**Issue by orangelckc** [unocss/unocss#1393] opened 2022-08-08 13:20 UTC
Today I face this issue, I want to load an image from remote, which is in a child component container with fixed height and width.

I got these two different results with same codes.
![image](https://user-images.githubusercontent.com/48410934/183425429-c287cdbb-f086-4169-b6e0-f7b25f2173d2.png)
![image](https://user-images.githubusercontent.com/48410934/183427240-5aee100a-4294-48c0-8c67-80ea309d00d9.png)

Anyone has an idea for this case, I can't figure out why `h-40 w-40` is not correctly resolved.

**Comment by equt** [comment] 2022-08-09 00:40
Setting the `mode` to `vue-scoped` acts the same as the `<style scoped />`. And as you've mentioned, it's _somewhere inside a child component_, it won't take effect.

**Comment by antfu** [comment] 2022-08-21 18:03
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-21 18:03 UTC
