### ISSUE TITLE
unocss not woking in Vue-cli5.0.8

### ISSUE THREAD

**Issue by izrio** [unocss/unocss#3825] opened 2024-05-22 03:27 UTC
### UnoCSS version

0.59.4

### Describe the bug

I installed Unocss "0.59.4" and @unocss/webpack "0.59.4" based on the documentation.but  not working

node version 14.20.1

### Reproduction

<img width="1459" alt="image" src="https://github.com/unocss/unocss/assets/46107383/9229bd35-34f9-4634-965e-9fd9b63212a9">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by telangY** [comment] 2024-05-22 05:48
I suggest you use Node 18 or higher version.Recommend use nvm in window or n in mac.

**Comment by Simon-He95** [comment] 2024-05-22 15:39
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-05-22 15:39 UTC
