### ISSUE TITLE
I can reproduce the error when using it in VitePress rc10:

### ISSUE THREAD

**Issue by janleslie** [unocss/unocss#3280] opened 2023-10-27 07:01 UTC
This is still an issue with latest version of Vitepress. 

I can reproduce the error when using it in VitePress rc10:

![imagen](https://github.com/unocss/unocss/assets/6311119/5b2686f3-e07d-4a29-936e-f3524d785bb9)

_Originally posted by @userquin in https://github.com/unocss/unocss/issues/2977#issuecomment-1712538958_

**Comment by Simon-He95** [comment] 2023-10-27 09:47
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

[Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2023-10-27 09:47 UTC
