### ISSUE TITLE
logos from iconify-json not working

### ISSUE THREAD

**Issue by akyag** [unocss/unocss#1884] opened 2022-11-17 07:23 UTC
I am in the middle of converting my project from tailwind to unocss. I was trying the icons preset instead of using astro-icon. Here is my config file - 
uno.config.ts
```
import { defineConfig, presetIcons, presetUno } from "unocss";
import { presetForms } from "@julr/unocss-preset-forms";
import { presetHeroPatterns } from "@julr/unocss-preset-heropatterns";
import { presetScrollbar } from "unocss-preset-scrollbar";

export default defineConfig({
  shortcuts: [
    { "i-logo": "i-logos-astro w-6em h-6em transform transition-800" },
  ],
  presets: [
    presetUno(),
    presetIcons({
      extraProperties: {
        display: "inline-block",
        "vertical-align": "middle",
      },
      collections: {
        carbon: () =>
          import("@iconify-json/carbon/icons.json").then((i) => i.default),
        bx: () => import("@iconify-json/bx/icons.json").then((i) => i.default),
        logos: () =>
          import("@iconify-json/logos/icons.json").then((i) => i.default),
      },
    }),
    presetForms(),
    presetHeroPatterns(),
    presetScrollbar(),
  ],
  rules: [
    ["font-display", { "font-family": '"Montserrat", sans-serif;' }],
    ["font-body", { "font-family": '"Mulish", sans-serif;' }],
  ],
  theme: {
    colors: {
      geraldine: {
        "50": "#fff9f9",
        "100": "#fef2f2",
        "200": "#fddfdf",
        "300": "#fbcbcb",
        "400": "#f8a5a5",
        "500": "#f57e7e",
        "600": "#dd7171",
        "700": "#b95a58",
        "800": "#934c4c",
        "900": "#783e3e",
      },
      dark: {
        "50": "#333d3d",
        "100": "#313b3b",
        "200": "#2f3939",
        "300": "#2a3434",
        "400": "#293333",
        "500": "#242e2e",
        "600": "#222c2c",
        "700": "#1f2929",
        "800": "#1b2525",
        "900": "#111b1b",
      },
    },
  },
});

```
It throws this error - 
```
[{
	"resource": "/home/akya/code/website/current/astro/astro-wor/uno.config.ts",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '() => Promise<{}>' is not assignable to type '(() => Awaitable<IconifyJSON>) | CustomIconLoader | InlineCollection | undefined'.\n  Type '() => Promise<{}>' is not assignable to type '() => Awaitable<IconifyJSON>'.\n    Type 'Promise<{}>' is not assignable to type 'Awaitable<IconifyJSON>'.\n      Type 'Promise<{}>' is not assignable to type 'Promise<IconifyJSON>'.\n        Type '{}' is missing the following properties from type 'IconifyJSON': prefix, icons",
	"source": "ts",
	"startLineNumber": 21,
	"startColumn": 9,
	"endLineNumber": 21,
	"endColumn": 14
}]
```

**Comment by zyyv** [comment] 2022-11-18 07:10
You can try to use the latest version. 

Install the corresponding dependencies, and remove these lines, UnoCSS can automatically load icons for you.
```diff
presetIcons({
    extraProperties: {
      display: "inline-block",
      "vertical-align": "middle",
    },
-  collections: {
-    carbon: () => import("@iconify-json/carbon/icons.json").then((i) => i.default),
-    bx: () => import("@iconify-json/bx/icons.json").then((i) => i.default),
-    logos: () => import("@iconify-json/logos/icons.json").then((i) => i.default),
-  },
}),
```

**Comment by antfu** [comment] 2022-11-18 08:02
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-11-18 08:02 UTC
