### ISSUE TITLE
Breakpoint names can break rules

### ISSUE THREAD

**Issue by lorenzlars** [unocss/unocss#3968] opened 2024-07-09 06:37 UTC
### UnoCSS version

0.61.2

### Describe the bug

Breakpoint names can break rules, just look at the example below.

### Reproduction

Create a config with a breakpoint `m`, try to use any class starting with `m` like `m-1`. The class will not be recognized by any rule and therefor not be included into the final build. But `mb-1` for example, will work.

```js
import {defineConfig, presetWind,} from 'unocss'
import {presetBase} from "./uno.preset";

export default defineConfig({
  presets: [
    presetWind(),
  ],
  theme: {
    breakpoints: {
      m: 100px,
    },
  }
})
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lorenzlars** [comment] 2024-07-19 15:57
@Simon-He95 what do you want to tell me?

This is not working:
```js

import {defineConfig, presetWind,} from 'unocss'
import {presetBase} from "./uno.preset";

export default defineConfig({
  presets: [
    presetWind(),
  ],
  rules: [
    [/^m-(\d+)$/, ([, d]) => ({ margin: `${d / 4}rem` })],
  ],
  theme: {
    breakpoints: {
      m: 100px,
    },
  }
})
```

**Comment by antfu** [comment] 2024-07-29 13:01
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-29 13:01 UTC
