### ISSUE TITLE
The latest version of the rule is not effective

### ISSUE THREAD

**Issue by xxwangkaimin** [unocss/unocss#3860] opened 2024-05-31 02:11 UTC
### UnoCSS version

0.60.3

### Describe the bug

After upgrading to the latest version,Most style rules have no effect

### Reproduction

![image](https://github.com/unocss/unocss/assets/33536543/93d6884c-7249-4afe-9d5c-47c55dc39910)
As shown in the above figure, the height style "h-full" is acceptable, but the "flex" and "items center" styles are invalid

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-05-31 02:39
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-05-31 02:39 UTC
