### ISSUE TITLE
[Bug] `question mark` rule will cause styleLoader crash because of `\n` 

### ISSUE THREAD

**Issue by jk4235** [unocss/unocss#3626] opened 2024-03-15 11:13 UTC
### UnoCSS version

latest

### Describe the bug

![image](https://github.com/unocss/unocss/assets/18319040/559184f5-25fe-4c94-815f-0c255d6df128)
https://github.dev/unocss/unocss/blob/94dffd8be003aa8d515385ec8e7631d490aea0d7/packages/preset-mini/src/_rules/question-mark.ts#L13-L14

could we just remove the `\n`  or escape it?

### Reproduction

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-03-15 11:22
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by jk4235** [comment] 2024-03-25 02:22
reproduction

https://stackblitz.com/edit/webpack-webpack-js-org-zr3wbe?file=src%2Fcomponents%2FHello.tsx

**Comment by userquin** [comment] 2024-04-12 13:29
@urzhumskov do you know you can use `shell-emulator=true` inside `.npmrc` when using [pnpm](https://pnpm.io/cli/run#shell-emulator) (don't need cross-env))?

```json
  "scripts": {
    "dev": "NODE_ENV=\"development\" webpack serve --mode=development"
  },
```

**Comment by urzhumskov** [comment] 2024-04-12 13:44
wow, thanks, @userquin -- I'm quite new to pnpm, cool feature, great to know!

**Closed** 2024-04-12 15:02 UTC
Labels: bug
