### ISSUE TITLE
remove commented code make compile pass

### ISSUE THREAD

**Issue by oluceps** [unocss/unocss#4208] opened 2024-10-16 19:36 UTC
### UnoCSS version

0.63.4

### Describe the bug

As titled, deleting code that has already been commented could make the compile pass.

```patch
--- a/src/ingredients/quick-link.tsx
+++ b/src/ingredients/quick-link.tsx
@@ -24,13 +24,7 @@ export const QuickLinks: ParentComponent<QuickLinksProps> = (props) => {
 	// 	setInnerW(0);
 	// };
 
-	// const innerWText = createMemo(() => `w-[${innerW()}%]`);
 
-	// onCleanup(() => clearTimeout(timeoutId));
-
-	// <a href={props.href} target="_blank">
-	// 	<span class="absolute -inset-px rounded-xl" />
-	// </a>
 	return (
 		<div/>
 	);
-- 
```

BTW I know the commented code actually didn't work, thus commented.

### vinxi build

```
> pnpm build

> 's blog@ build /home/elen/Src/blog.nyaw.xyz
> pnpm gen && vinxi build


> 's blog@ gen /home/elen/Src/blog.nyaw.xyz
> node ./scripts/writeData.mjs && node ./scripts/writeSitemap.mjs && node ./scripts/time.mjs

Data successfully written to data.ts
Sitemap generated and saved as sitemap.xml
written time.json
vinxi v0.4.3
The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.


⚙  Building your app...
removing /home/elen/Src/blog.nyaw.xyz/.vinxi/build/ssr
vinxi v0.4.3
The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.


⚙ Building your router ssr...


📦 Compiling ssr router...
vinxi building router ssr in http mode
vite v5.4.9 building SSR bundle for production...
✓ 234 modules transformed.
x Build failed in 9.98s

[03:09:23]  ERROR  [unocss:global:build:scan] [postcss] /home/elen/Src/blog.nyaw.xyz/assets/ssr-!~{001}~.js-unocss-hash.css:1:26577: Unknown word

  at Input.error (node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/input.js:106:16)
  at Parser.unknownWord (node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/parser.js:593:22)
  at Parser.other (node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/parser.js:435:12)
  at Parser.parse (node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/parser.js:470:16)
  at parse (node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/parse.js:11:12)
  at new LazyResult (node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/lazy-result.js:133:16)
  at Processor.process (node_modules/.pnpm/postcss@8.4.47/node_modules/postcss/lib/processor.js:53:14)
  at compileCSS (node_modules/.pnpm/vite@5.4.9_@types+node@16.18.11_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:36889:59)
  at async Object.transform (node_modules/.pnpm/vite@5.4.9_@types+node@16.18.11_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:36170:11)
  at async applyCssTransform (node_modules/.pnpm/@unocss+vite@0.62.4_rollup@4.24.0_vite@5.4.9_@types+node@16.18.11_terser@5.36.0_/node_modules/@unocss/vite/dist/index.mjs:539:20)
  at async Object.renderChunk (node_modules/.pnpm/@unocss+vite@0.62.4_rollup@4.24.0_vite@5.4.9_@types+node@16.18.11_terser@5.36.0_/node_modules/@unocss/vite/dist/index.mjs:651:15)
  at async transformChunk (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:18791:16)
  at async node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:18865:17
  at async Promise.all (index 0)
  at async transformChunksAndGenerateContentHashes (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:18860:5)
  at async renderChunks (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:18769:151)
  at async Bundle.generate (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19009:13)
  at async node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:21688:27
  at async catchUnfinishedHookActions (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:21076:16)
  at async Module.build (node_modules/.pnpm/vite@5.4.9_@types+node@16.18.11_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65438:16)
  at async createViteBuild (node_modules/.pnpm/vinxi@0.4.3_@types+node@16.18.11_ioredis@5.4.1_terser@5.36.0_webpack-sources@3.2.3/node_modules/vinxi/lib/build.js:381:17)
  at async createRouterBuild (node_modules/.pnpm/vinxi@0.4.3_@types+node@16.18.11_ioredis@5.4.1_terser@5.36.0_webpack-sources@3.2.3/node_modules/vinxi/lib/build.js:506:2)
  at async node_modules/.pnpm/vinxi@0.4.3_@types+node@16.18.11_ioredis@5.4.1_terser@5.36.0_webpack-sources@3.2.3/node_modules/vinxi/lib/build.js:51:5
  at async createBuild (node_modules/.pnpm/vinxi@0.4.3_@types+node@16.18.11_ioredis@5.4.1_terser@5.36.0_webpack-sources@3.2.3/node_modules/vinxi/lib/build.js:50:4)
  at async Object.run (node_modules/.pnpm/vinxi@0.4.3_@types+node@16.18.11_ioredis@5.4.1_terser@5.36.0_webpack-sources@3.2.3/node_modules/vinxi/bin/cli.mjs:235:5)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
  at async runMain (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7) 



[03:09:23]  ERROR  [unocss:global:build:scan] [postcss] /home/elen/Src/blog.nyaw.xyz/assets/ssr-!~{001}~.js-unocss-hash.css:1:26577: Unknown word


 ERROR  Exited with code: 1                                                                03:09:23

  at CommandChild.pipedStdoutBuffer (node_modules/.pnpm/dax-sh@0.39.2/node_modules/dax-sh/esm/mod.js:9392:19)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 



 ERROR  Exited with code: 1                                                                03:09:23

 ELIFECYCLE  Command failed with exit code 1.
```

### vinxi dev

https://gist.github.com/oluceps/edcc4070644cb7cf45d4e91509f406bf

## after change

Everything works

### Reproduction

This appears despite different environments, I tried:

+ Let Vercel build it
+ deleting node_modules
+ remove `.vinxi`
+ reboot machine
+ delete and clone the repo

None works.
# Reproducing

I'm using `solid-start v1.0`, to reproduce this, here is an repo

https://github.com/oluceps/debug-602658b2e9488d4c

It passes compile after this change https://github.com/oluceps/debug-602658b2e9488d4c/commit/9cd6f507a5eca7e7027d53d28e607378071ba358  feel free to test it,

**To reproduce this needs to checkout `63397b721179971221e05338971798bfd32cc95c`**

here's my uno config imports
```js
import {
	defineConfig,
	presetTypography,
	presetUno,
	transformerDirectives,
	transformerCompileClass,
	presetIcons,
} from "unocss";
import presetWind from "@unocss/preset-wind";
import presetRemToPx from "@unocss/preset-rem-to-px";
```

### System Info

Both the vercel cloud compile env, and local:

```
> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.0-cachyos, NixOS, 24.11 (Vicuna), 24.11.20240917.46dc692`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0-dev-pre20240909-c14486a
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/elen/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/elen/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/elen/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/elen/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/elen/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/3vfhb3qpbfn42kw55xbz0kkwzidcpnxm-lix-2.92.0-dev-pre20240909-c14486a/share`
 - nixpkgs: `/nix/store/68p7jk1sqqsqgbbaqzp7cds3kxkahmh7-21asjvqjhmy385ki1zrvb0n18alr1knv-source`
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-10-17 05:41
It is indeed a good idea to remove some commented code in advance, which will reduce a lot of unnecessary parsing, improve performance, and reduce parsing errors and redundant class generation.

**Comment by oluceps** [comment] 2024-10-17 07:48
> It is indeed a good idea to remove some commented code in advance, which will reduce a lot of unnecessary parsing, improve performance, and reduce parsing errors and redundant class generation.

That makes debugging incredibly hard. I can't even understand why removing commented code affecting the compilation result, I'm not so familiar with web toolchains.

**Comment by zyyv** [comment] 2024-10-21 02:12
@oluceps Can you provide a minimal reproduction?

**Comment by oluceps** [comment] 2024-10-21 07:03
> @oluceps Can you provide a **minimal** reproduction?

I made a minimal [branch](https://github.com/oluceps/debug-602658b2e9488d4c/tree/min) for reproducing that. Now the codebase has been eliminated from `2k+ to 200L`

I marked several points by `REMOVE` that could make it pass compilation once any of them were removed. You could review with `rg REMOVE`.

I think this issue is partially related to `presetIcons`.

**Comment by zyyv** [comment] 2024-10-21 07:46
@oluceps This error occurs at 
```tsx
// quick-link.tsx

// ...
// const innerWText = createMemo(() => `w-[${innerW()}%]`);
```

`w-[${innerW()}%]` This syntax participates in the incorrect uno extraction and is parsed and output to css by uno. You can see that the result (see [Playground](https://unocss.dev/play/#html=DwEwlgbgBAfAUAegVAxgewHYGcAuUwYYCmATgOoAqRAHngLyolECGORAskQLZoAUvASih0YUAAYB3ALQBtACQBvAsXKCAvgFIAumIEBuOMATgI8IA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQoksicYKKlaoYAVRHp6AGzIUqNBkzasAtIOGjV9STK6dUAD17w06AIYzTGbHgLEAFAk5w4rABbQYzejFYAuRBdXOAB3KHMwMFQoQNpQ1VZmIVQsOHdE5NRUimY82gAaYNIi1w0RP0CAbWCyoQqJDBknWpDU8wAjaVQAJU0YAGUYAE9ugIpzaRFSkNdgZgJx51nZpMnUQIBGADoAJhmVuGZkLDj3GBgwAIB6a%2BEQbY9rwtbXEtbSAEoZgF0ir84QA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA)) is not a correct css, causing the compilation to fail.

<img width="484" alt="image" src="https://github.com/user-attachments/assets/67311dc9-7d9a-426a-a736-e85afafefcda">


> And I think you are using dynamic class, if you want to use Dynamic class better, please use it with `safelist`.

Workaround
1. Because uno's `[ ]` syntax customization is very high and its content is not verified, we can use other syntaxes to support it.
Such as: `w-${innerW}%` , successful case `w-2%`

2. Add magic comment
```diff
export const QuickLinks: ParentComponent<{}> = (props) => {
  // const handleMouseLeave = () => {
  // 	clearTimeout(timeoutId);
  // 	setIsRelative(false);
  // 	clearTimeout(intervalId);
  // 	setInnerW(0);
  // };
  // REMOVE below

+ // @unocss-skip-start
  // const innerWText = createMemo(() => `w-[${innerW()}%]`);
+ // @unocss-skip-end

  // onCleanup(() => clearTimeout(timeoutId));

  // <a href={props.href} target="_blank">
  // 	<span class="absolute -inset-px rounded-xl" />
  // </a>
  return <div />;
};
```

**Comment by MarvinXu** [comment] 2024-10-30 08:04
I may have the same problem. Here is my minimal reproduction: https://stackblitz.com/edit/withastro-astro-8kgw9z?file=src%2Fpages%2Findex.astro

I found that dynamic class using `${var}` syntax breaks alongside `@iconify-json/mdi`, removing either one will make build pass.

**Comment by zyyv** [comment] 2024-11-05 02:35
@MarvinXu Hi, this error is not caused by the `aspect` rule. We have a high degree of freedom in the `bracket` syntax and we will not over-parse the values ​​in the brackets.
So when extracting the class, `aspect-[${ratio}]` is extracted, and its generated CSS is, 
```css
.aspect-\[\$\{ratio\}\]{
  aspect-ratio: ${ratio};
}
```
so it causes a CSS syntax error.

You can use `aspect-${ratio}` get the same effect.

**Comment by zyyv** [comment] 2024-11-05 02:38
I will close this issue. For more details, please refer to https://github.com/unocss/unocss/pull/4212#discussion_r1815146213.

UnoCSS does not actively participate in deleting and skipping user code. This is not the original intention of unocss. It is more about parsing. I hope you can give good guidance to unocss.

**Closed by zyyv** 2024-11-05 02:38 UTC
