### ISSUE TITLE
unocss configuration is a configuration generation function，unocss vscode plugin don't work

### ISSUE THREAD

**Issue by SKT1yang** [unocss/unocss#2056] opened 2023-01-08 14:54 UTC
> I separate the unocss configuration into independent ts files and it is a configuration generation function. Therefore, 

the vscode extension of unocss does not take effect. Can you find a way to support this feature

> I originally wanted to make the vite app and vscode plugin run normally by providing methods and configuration 

objects at the same time, but it didn't work as expected, and recursion would lead to serious memory overflow
![image](https://user-images.githubusercontent.com/34095649/211202913-ce87e8b5-7edf-4e00-9d40-a9c1e7688631.png)

```
/**
 * The instant on-demand atomic CSS engine.
 * @see https://github.com/unocss/unocss
 */

import type { PluginOption } from 'vite'
import type { UserConfig } from 'unocss'
import Unocss from 'unocss/vite'
import { presetIcons, presetMini, presetUno} from 'unocss'
import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders'

// 静态配置
export const staticConfig: UserConfig = {
  rules: [
    ['custom-rule', { color: 'red' }]
  ],
  exclude: ['node_modules', '.git', 'dist'],
  presets: [
    presetIcons({
      collections: {
        // key as the collection name
        app: FileSystemIconLoader("./src/assets/icons"),
      },
      prefix: "i-",
      extraProperties: {
        display: "inline-block",
      },
    }),
    presetMini({
      dark: 'class',
    }),
    presetUno()
  ],
  shortcuts: {
    'flex-center': 'flex justify-center items-center',
    'flex-between': 'flex justify-between items-center',
  },
  theme: {
    colors: {
      primary: 'var(--primary-color)',
    },
    backgroundColor: {},
    transitionProperty: [],
  },
}

/**
 * export default形式给 unocss的vscode插件使用
 * 原因：By default the extension will search for the config files under project root. 
 * When there is no config found, the extension will be disabled. 
 * To work with monorepo, you need to change the unocss.root option in 
 * your settings.json to the directory that contains the config file.
 */
// export default defineConfig(staticConfig)

export function configUnocssPlugin(): PluginOption {
  return Unocss(staticConfig)
}
```

**Comment by lishaobos** [comment] 2023-01-11 08:28
hi, you can try like this：

```js
// vite.config.ts

import { defineConfig } from 'vite'
import Unocss from 'unocss/vite'
import unoConfig from './uno.config'

export default defineConfig({
  plugins: [
    Unocss(unoConfig),
  ]
})
```

```js
// uno.config.ts

import { defineConfig } from 'unocss/vite'
import { presetIcons, presetMini, presetUno} from 'unocss'

export default defineConfig({
  rules: [
    ['custom-rule', { color: 'red' }]
  ],
  exclude: ['node_modules', '.git', 'dist'],
  presets: [
    presetIcons({
      collections: {
        // key as the collection name
        app: FileSystemIconLoader("./src/assets/icons"),
      },
      prefix: "i-",
      extraProperties: {
        display: "inline-block",
      },
    }),
    presetMini({
      dark: 'class',
    }),
    presetUno()
  ],
  shortcuts: {
    'flex-center': 'flex justify-center items-center',
    'flex-between': 'flex justify-between items-center',
  },
  theme: {
    colors: {
      primary: 'var(--primary-color)',
    },
    backgroundColor: {},
    transitionProperty: [],
  },
})
```

**Comment by Natan-Cruz** [comment] 2023-02-20 14:49
i would like remove color:inherit default. Is it possible?

**Comment by hopkinson** [comment] 2023-02-24 03:38
it's not useful for me too..

**Comment by 1614080902102** [comment] 2023-04-20 15:33
> 
尝试了，该插件还是不生效……

**Comment by antfu** [comment] 2023-04-20 15:56
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-04-20 15:56 UTC
