### ISSUE TITLE
vite中使用vite-plugin-html后，http://localhost:3000/__unocss无法正常打开

### ISSUE THREAD

**Issue by maddenBoy** [unocss/unocss#1439] opened 2022-08-20 10:13 UTC
当我再项目中使用vite-plugin-html插件后，在我的本地开发服务器无法正常访问 http://localhost:3000/__unocss 页面，弃用该插件则可以正常访问。
![image](https://user-images.githubusercontent.com/71129660/185741147-012b4bba-d27b-4eba-b0df-cb05287cd849.png)

**Comment by antfu** [comment] 2022-08-21 16:04
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-21 16:04 UTC
