### ISSUE TITLE
Why doesn't my plug-in take effect 

### ISSUE THREAD

**Issue by each1026** [unocss/unocss#1383] opened 2022-08-06 07:04 UTC
> Plug-in settings have not changed. Generally speaking, plug-ins can take effect, right? My 'vite.config.ts' is in the root directory.

If there is a solution, can you tell me how to set it up directly? I have read the tutorial of plug-in, but I have not understood it.

```js
import presets from './presets'
export default defineConfig({
	plugins: [presets()],
})
```

```js
import WindiCSS from 'vite-plugin-windicss'
import Unocss from 'unocss/vite'
import { presetAttributify, presetUno } from 'unocss'


export default () => {
	return [
		WindiCSS(),
		Unocss({ presets: [presetAttributify(), presetUno()] }),
		uni()
	]
}
```

**Comment by each1026** [comment] 2022-08-06 07:05
Also, I don't know what to do after it takes effect. Do you want to show the code suggestions windicss?

**Comment by chen-see** [comment] 2022-08-06 07:37
it's my config file
```
// uno.config.ts

import { defineConfig, presetUno, presetAttributify, presetIcons } from 'unocss';
export default defineConfig({
  presets: [presetUno(), presetAttributify(), presetIcons()],
});

```

**Comment by antfu** [comment] 2022-08-06 08:19
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-06 08:19 UTC
