### ISSUE TITLE
[@unocss/transformer-directives] @apply directives not transformed in prod build

### ISSUE THREAD

**Issue by Innei** [unocss/unocss#725] opened 2022-03-17 02:40 UTC
In prod build preivew, like this.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/41265413/158725605-2f053d07-89cc-4c5a-9f7c-17cb4f728943.png">

Dev mode is working.

**Comment by antfu** [comment] 2022-03-17 08:40
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by Innei** [comment] 2022-03-17 09:15
In dev:

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/41265413/158776542-511eee97-ae93-40d1-96ea-19382d88270f.png">

In prod:
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/41265413/158776629-89060076-f32a-4ade-8306-a567f89456ce.png">

Reproduction: https://github.com/Innei/unocss-reproduction

**Comment by Innei** [comment] 2022-03-17 09:15
@antfu Thank you.

**Comment by xmsz** [comment] 2022-03-18 07:05
Any update?

**Comment by kidonng** [comment] 2022-08-26 02:39
Can no longer reproduce this issue.

**Closed** 2022-08-26 06:05 UTC
Labels: directives

**Comment by aspiiire** [comment] 2022-10-07 14:59
I have the same issue, do you have any idea on how you solved? @kidonng
