### ISSUE TITLE
[BUG] Classes not re-generating without full server restart in SSR frameworks

### ISSUE THREAD

**Issue by AaronBeaudoin** [unocss/unocss#1351] opened 2022-07-29 21:48 UTC
Minimal reproduction with steps:

https://github.com/AaronBeaudoin/unocss-issue-server-only

## Description

UnoCSS classes in `vite-plugin-ssr` ~"server"~ pages ~(page files ending in `.server.page.xyz`)~ are generated once when the page is first loaded, but are not regenerated on file modifications. A full server restart is required to see the changes.

**Comment by AaronBeaudoin** [comment] 2022-08-02 16:10
A few updates. It appears that this issue isn't actually isolated to pages that end in `.page.server.vue`, it also applies to regular SSR pages ending `.page.vue`. It looks like the issue only occurs when `import "uno.css";` is in `_default.page.server.js` instead of `_default.page.client.js`, so it also appears to be related to UnoCSS's `global` mode. If I change the mode to `vue-scoped` everything seems to work normally.

**Comment by alping** [comment] 2022-08-05 12:27
I see a similar issue when using UnoCSS with Nuxt 3 (Content 2). I have to fully restart the server and sometimes also delete the `.nuxt` folder for new classes to be applied. Unfortunately the vue-scoped mode is not available for UnoCSS with Nuxt (as far as I know), so I haven't found a workaround. Since Nuxt uses SSR by default, I suspect this is a related issue.

**Comment by AaronBeaudoin** [comment] 2022-08-05 13:25
@alping It looks like UnoCSS just uses [`@unocss/vite`](https://github.com/unocss/unocss/tree/main/packages/vite) internally as you can see in the [`package.json`](https://github.com/unocss/unocss/blob/main/packages/nuxt/package.json), so have you tried just adding `mode: "vue-scoped"` to your `nuxt.config.js` sort of like described [here](https://github.com/unocss/unocss/tree/main/packages/nuxt#configuration)?

**Comment by antfu** [comment] 2022-08-06 08:32
@alping I use UnoCSS with Nuxt quite a lot and does not encounted such an issue. Please open a new issue with a minimal reproduction of your issue. The original post is probably related to `vite-plugin-ssr`'s integration rather than SSR in general.

**Comment by antfu** [comment] 2022-08-06 08:37
with `vite-plugin-ssr`, the `.css` is no longer reactive: 

<img width="611" alt="image" src="https://user-images.githubusercontent.com/11247099/183241550-b012c6ff-5d2f-47b7-a0f6-a22a159323e5.png">

Where we expect a regular Vite app to have CSS like this, which handles HMR itself:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/11247099/183241581-6a06f0b2-1b4a-4d15-a023-d0a5ff11ee16.png">

/cc @brillout - we might not consider this as a bug of either side, but I guess it's more like an integration issue we could improve?

**Comment by brillout** [comment] 2022-08-06 12:52
The thing is that [HTML-only](https://vite-plugin-ssr.com/render-modes#html-only) pages may have

Thanks for the ping.

**Comment by brillout** [comment] 2022-08-06 13:08
When using vite-plugin-ssr in [HTML-only](https://vite-plugin-ssr.com/render-modes#html-only) mode then `uno.css` is not imported from JavaScript. Instead it is directly injected into the HTML. (Which makes sense since HTML-only is about having no/minimal browser-side JavaScript.)

That said, it would still be possible for vite-plugin-ssr to inject `uno.css` from within a tiny JavaScript shell instead. So it's fixable.

It's low priority though since HTML-only is more of an experiment than something people actually use.

Although technologies such as React Server Components (which also have no/minimal browser-side JavaScript) will need a solution for that. For example, chances are that UnoCSS's HMR also doesn't work with Hydrogen.

I think we can close this ticket in favor of https://github.com/brillout/vite-plugin-ssr/issues/411.

Thanks for the ping.

**Comment by antfu** [comment] 2022-08-06 15:18
Thanks for the explaination.

Close in favor of https://github.com/brillout/vite-plugin-ssr/issues/411

**Closed by antfu** 2022-08-06 15:18 UTC
Labels: integration

**Comment by alping** [comment] 2022-08-08 09:36
@AaronBeaudoin Unfortunately `mode: "vue-scoped"` doesn't seem to work with Nuxt 3, which is also hinted at by TypeScript typing errors when using it with `unocss` inside `defineNuxtConfig`.

@antfu Thanks for the reply, I'll do some more testing and get back with a new issue if it persists.
