### ISSUE TITLE
@iconify-json/logos Package Installed But Encounter "Failed to Load Icon" Error in Command Line During Dev Run

### ISSUE THREAD

**Issue by totorofly** [unocss/unocss#2905] opened 2023-07-23 08:32 UTC
### UnoCSS version

0.50.8

### Describe the bug

Despite successfully installing the @iconify-json/logos package via pnpm, I'm encountering an error message in my command line stating "[unocss] failed to load icon" when running pnpm run dev. This issue seems unusual as the icons appear to be displayed correctly on the frontend of the application.
<img width="1902" alt="image" src="https://github.com/unocss/unocss/assets/41875799/6340df4f-a1f5-4017-9152-30bf7f8c49e0">

### Reproduction

Install @iconify-json/logos package via pnpm by running pnpm install @iconify-json/logos
Use a logo from @iconify-json/logos in the application.
Run the application in dev mode by executing pnpm run dev.
Observe the error message in the command line.

### System Info

<img width="1902" alt="image" src="https://github.com/unocss/unocss/assets/41875799/99301969-ff48-4ceb-8509-f459736990fa">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ahspagh** [comment] 2024-01-28 13:51
the same problem……
bro, how do you resolve that?

**Comment by github-cherry** [comment] 2024-03-18 05:02
我也遇到过，控制台虽然警告，但页面能正常显示

**Comment by MrFoxPro** [comment] 2024-04-24 10:33
Not stale, there is still false warning.

**Comment by zyyv** [comment] 2024-11-05 08:59
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2024-11-05 08:59 UTC
