### ISSUE TITLE
After upgrading to `0.49`, the vscode extension does not work

### ISSUE THREAD

**Issue by cinob** [unocss/unocss#2156] opened 2023-02-06 09:45 UTC
The `0.48` version is fine

**Comment by danielwaltz** [comment] 2023-02-11 05:56
Just to assist in troubleshooting, I believe this may be related to if you have an `include` config option defined in your `uno.config.ts` file.

I'm using the PrimeReact component library in my project, and rather than load their entire icon and utility stylesheets I opted to use `unocss` and `presetIcons` to only include the icons/styles I'm actually using.

By default, this means that without their icon stylesheet loaded, internal components imported from Prime will not have their icons visible because `unocss` is not parsing those files to check for icon matches.

To solve this, I added this option to my `uno.config.ts` file:

```ts
import { defineConfig } from 'unocss';

export default defineConfig({
  include: [/(.*\/)primereact(.*)\.(c|m)?(js)(x?)$/, 'src/**/*.tsx']
});
```

And here it what it looks like with the rest of the config:

```ts
import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders';
import { presetIcons, presetWind, defineConfig } from 'unocss';
import presetPrime from 'unocss-preset-prime';

// https://uno.antfu.me/
export default defineConfig({
  presets: [
    presetWind(),
    presetPrime(),
    presetIcons({
      collections: {
        app: FileSystemIconLoader('src/assets/icons'),
      },
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
        scale: '1.75',
      },
    }),
  ],
  include: [/(.*\/)primereact(.*)\.(c|m)?(js)(x?)$/, 'src/**/*.tsx'],
  shortcuts: [
    [/^pi-(.*?)$/, ([, d]) => `i-prime-${d}`]
  ],
});
```

When I have this `include` option entered, all editor tools like autocomplete/hover info/underlined classes stop working. If I comment that line out and reload VSCode, it starts working again.

**Comment by cinob** [comment] 2023-02-15 02:06
> Just to assist in troubleshooting, I believe this may be related to if you have an `include` config option defined in your `uno.config.ts` file.只是为了帮助故障排除，我相信这可能与您在 `include` 文件中定义了 `uno.config.ts` 配置选项有关。
> 
> I'm using the PrimeReact component library in my project, and rather than load their entire icon and utility stylesheets I opted to use `unocss` and `presetIcons` to only include the icons/styles I'm actually using.我在我的项目中使用 PrimeReact 组件库，而不是加载他们的整个图标和实用程序样式表，我选择使用 `unocss` 和 `presetIcons` 只包含我实际使用的图标/样式。
> 
> By default, this means that without their icon stylesheet loaded, internal components imported from Prime will not have their icons visible because `unocss` is not parsing those files to check for icon matches.默认情况下，这意味着如果没有加载其图标样式表，从 Prime 导入的内部组件将不会显示其图标，因为 `unocss` 不会解析这些文件以检查图标匹配。
> 
> To solve this, I added this option to my `uno.config.ts` file:为了解决这个问题，我将此选项添加到我的 `uno.config.ts` 文件中：
> 
> ```ts
> import { defineConfig } from 'unocss';
> 
> export default defineConfig({
>   include: [/(.*\/)primereact(.*)\.(c|m)?(js)(x?)$/, 'src/**/*.tsx']
> });
> ```
> 
> And here it what it looks like with the rest of the config:这是配置其余部分的样子：
> 
> ```ts
> import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders';
> import { presetIcons, presetWind, defineConfig } from 'unocss';
> import presetPrime from 'unocss-preset-prime';
> 
> // https://uno.antfu.me/
> export default defineConfig({
>   presets: [
>     presetWind(),
>     presetPrime(),
>     presetIcons({
>       collections: {
>         app: FileSystemIconLoader('src/assets/icons'),
>       },
>       extraProperties: {
>         display: 'inline-block',
>         'vertical-align': 'middle',
>         scale: '1.75',
>       },
>     }),
>   ],
>   include: [/(.*\/)primereact(.*)\.(c|m)?(js)(x?)$/, 'src/**/*.tsx'],
>   shortcuts: [
>     [/^pi-(.*?)$/, ([, d]) => `i-prime-${d}`]
>   ],
> });
> ```
> 
> When I have this `include` option entered, all editor tools like autocomplete/hover info/underlined classes stop working. If I comment that line out and reload VSCode, it starts working again.当我输入此 `include` 选项时，所有编辑器工具（如自动完成/悬停信息/带下划线的类）都将停止工作。如果我注释掉该行并重新加载 VSCode，它会再次开始工作。
> 
> EDIT: After a touch more troubleshooting, I now think it's related to the path `src/**/*.tsx`. If I modify that line to not include a path and only match on files `**/*.tsx` is starts working again as well. I am using a multi-root workspace setup and have configured unocss to use a custom root, so I wonder if something about how that path is resolving is messing things up.编辑：经过更多的故障排除，我现在认为它与路径 `src/**/*.tsx` 有关。如果我将该行修改为不包含路径并且仅在文件 `**/*.tsx` 上匹配，则也会再次开始工作。我正在使用多根工作区设置，并将unocss配置为使用自定义根，所以我想知道该路径如何解决是否使事情搞砸了。

Thank you very much for your kind answer, but unfortunately I didn't configure the `include` option. 😑

**Comment by antfu** [comment] 2023-02-16 23:18
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-16 23:18 UTC

**Comment by cinob** [comment] 2023-02-17 01:37
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

My development environment is Windows WSL. After upgrading to version 0.49, the VSCode extensions for my Nuxt and Vite projects stopped working. I have recently created a new vitesse-lite project to confirm this.
