### ISSUE TITLE
unocss not work in lerna on local packages

### ISSUE THREAD

**Issue by social-uni** [unocss/unocss#1634] opened 2022-09-25 15:25 UTC
Sorry I didn't provide a minimal reproducible version, I used lerna for several project associations and it wasn't very easy to do

Can you figure out the problem by looking at the picture information?

Error: Cannot find module '@sociauni/socialuni-constant/constant/DevModeType'

![image](https://user-images.githubusercontent.com/14007972/192151352-2c82220d-c92c-4511-b7b3-e47c931b8d29.png)

![image](https://user-images.githubusercontent.com/14007972/192151343-93eaca92-d0be-4048-b115-406451e6173b.png)

I only installed the local library in the outermost layer through lerna, but this library is not configured in package.json, does it matter?

It's available in .vue pages, but doesn't work in vite.config.js

**Comment by antfu** [comment] 2022-09-25 18:39
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-09-25 18:39 UTC
