### ISSUE TITLE
nuxt layers merge configs on windows 11

### ISSUE THREAD

**Issue by qoo1476** [unocss/unocss#4027] opened 2024-07-30 04:27 UTC
### UnoCSS version

0.61.7

### Describe the bug

hi i want to use nuxt layers with unocss config
so i followed unocss.dev guide mergeConfigs like this

```
import { mergeConfigs } from '@unocss/core'
import config from './.nuxt/uno.config.mjs'

export default mergeConfigs([
  config,
  ...[some merge settings]
])
```

and it throws error like this
![image](https://github.com/user-attachments/assets/968ae505-0161-4bf2-9e90-5347f2111e9d)

so i checked uno.config.mjs
```
import { mergeConfigs } from '@unocss/core'
import cfg0 from 'C:/source/full_kit/unocss.config.ts'

export default mergeConfigs([cfg0])
```
maybe it should contains file:/// with windows platform?

it works fine with this
```
import { mergeConfigs } from '@unocss/core'
// @ts-ignore
import cfg0 from 'file:///C:/source/full_kit/unocss.config.ts'

export default mergeConfigs([
  cfg0,
  ...[some merge settings]
])
``` 

### Reproduction

none of reproduction

### Validations

- [ ] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [ ] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-07-31 23:23
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-31 23:23 UTC

**Comment by flapili** [comment] 2024-12-05 15:07
got the same issue,

reproduction : https://github.com/flapili/nuxt-layer-unocss-bug

Please considere reopening this issue

Best Regards

**Comment by flapili** [comment] 2024-12-13 08:17
@antfu should I duplicate the issue ?

Best regards
