### ISSUE TITLE
Attributify and Input won't change text and font attrs

### ISSUE THREAD

**Issue by Gruce** [unocss/unocss#1261] opened 2022-07-14 08:48 UTC
### Hello,
I have input with text attribute set to "red-500" but color of the text won't be changed even font attribute set to sans and won't changed.

![image](https://user-images.githubusercontent.com/5357529/178941816-f6cdad09-b9af-49f1-bcb7-04de8fc9a7c9.png)

![image](https://user-images.githubusercontent.com/5357529/178941316-2761d967-af16-45a6-adab-5be0747710ce.png)

![image](https://user-images.githubusercontent.com/5357529/178942443-77ac1e5d-e2f5-428d-8e8d-7550aa43dd1e.png)

My Nuxt Config
```javascript
unocss: {
        // autoImport: true,
        // preflight: true,
        uno: true, // enabled `@unocss/preset-uno`
        // https://icon-sets.iconify.design/
        icons: true, // enabled `@unocss/preset-icons`
        attributify: {
            ignoreAttributes: ['label'],
            // prefix: 'un-',
        }, // enabled `@unocss/preset-attributify`,
        typography: true, // enabled `@unocss/preset-typography`
        webFonts: {
            provider: 'google', // default provider
            fonts: {
                // these will extend the default theme
                sans: ['Tajawal:200,300,400,500,700,800,900'],
                // mono: ['Fira Code', 'Fira Mono:400,700'],
            },
        },
        theme: {
            colors: {
                'primary': { DEFAULT: '#244481', '50': '#FFFFFF', '100': '#F0F4FB', '200': '#D1DCF2', '300': '#B1C4E9', '400': '#91ACE0', '500': '#7194D7', '600': '#517CCE', '700': '#3666C1', '800': '#2D55A1', '900': '#244481' },
                'secondary': { DEFAULT: '#6B7280', '50': '#CDD0D5', '100': '#C2C5CC', '200': '#ACB0BA', '300': '#969BA7', '400': '#7F8694', '500': '#6B7280', '600': '#515761', '700': '#383C43', '800': '#1E2024', '900': '#050506' },
                'error': { DEFAULT: '#EF4444', '50': '#FDEDED', '100': '#FCDADA', '200': '#F9B5B5', '300': '#F58F8F', '400': '#F26A6A', '500': '#EF4444', '600': '#E71414', '700': '#B30F0F', '800': '#800B0B', '900': '#4C0707' },
                'warning': { DEFAULT: '#F59E0B', '50': '#FCE4BB', '100': '#FBDCA8', '200': '#FACD81', '300': '#F8BD59', '400': '#F7AE32', '500': '#F59E0B', '600': '#C07C08', '700': '#8A5906', '800': '#543603', '900': '#1E1401' },
                'success': { DEFAULT: '#10B981', '50': '#8CF5D2', '100': '#79F3CB', '200': '#53F0BC', '300': '#2EEDAE', '400': '#13DF9B', '500': '#10B981', '600': '#0C855D', '700': '#075239', '800': '#031E15', '900': '#000000' },
            },
        },
    },
```

Thank you

**Comment by antfu** [comment] 2022-07-14 16:34
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-14 16:34 UTC
