### ISSUE TITLE
部分页面需要适配，搭配postcss-pxtorem，unocss未生效

### ISSUE THREAD

**Issue by DreamZhang97** [unocss/unocss#3239] opened 2023-10-16 03:16 UTC
### UnoCSS version

lastest

### Describe the bug

当部分页面需要去适配，搭配postcss-pxtorem，unocss未生效。例如：pl-24px，页面应该转为rem，但是未转。
若全部页面都适配，unocss单位转化就生效了。
当前的解决方案：在需要适配的页面重写 unocss关于px单位的属性。例如：pl-24px：padding-left:24px; 转rem单位正常。
When some pages need to be adapted and used with postcss-pxtorem, unocss does not take effect. For example: pl-24px, the page should be converted to rem, but it is not converted.

If all pages are adapted, unocss unit conversion will take effect.

The current solution: Rewrite unocss's px unit attributes on the page that needs to be adapted. For example: pl-24px: padding-left:24px; The conversion to rem unit is normal.

### Reproduction

import Unocss from 'unocss/vite'
import { presetAttributify, presetIcons } from 'unocss'
import presetUno from '@unocss/preset-uno'
export function configUnoCssPlugin() {
  const unoCssPlugin = Unocss({
    presets: [
      presetUno(),
      presetAttributify(),
      presetIcons(),
    ],
  })
  return unoCssPlugin
}

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-10-16 04:42
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-16 04:42 UTC
