### ISSUE TITLE
unocss cli  v0.31.22 can't work ?

### ISSUE THREAD

**Issue by 729902288** [unocss/unocss#857] opened 2022-04-22 01:35 UTC
but , v0.22.7 can work!

![image](https://user-images.githubusercontent.com/20468762/164579231-49ac372a-a52e-40ba-a9c8-94938352c5ec.png)

**Comment by antfu** [comment] 2022-04-22 05:09
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-04-22 05:09 UTC
