### ISSUE TITLE
When I use @unocss/webpack, I import uno.css in the entry, reporting * uno.css in. /src/main.ts    To install it, you can run: npm install --save uno.css

### ISSUE THREAD

**Issue by Rengge** [unocss/unocss#3019] opened 2023-08-22 09:35 UTC
### UnoCSS version

0.55.2

### Describe the bug

When I use @unocss/webpack, I import uno.css in the entry, reporting * uno.css in. /src/main.ts    To install it, you can run: npm install --save uno.css

### Reproduction

When I use @unocss/webpack, I import uno.css in the entry, reporting * uno.css in. /src/main.ts    To install it, you can run: npm install --save uno.css

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ThinkMars** [comment] 2023-08-22 12:41
i meet the same question, it shoule be your webpack plugin has not setup successfully, try to debug the webpack

**Comment by Rengge** [comment] 2023-08-23 01:57
> 我遇到了同样的问题，您的 webpack 插件没有成功设置，请尝试调试 webpack

How do you debug webpack

**Comment by ThinkMars** [comment] 2023-08-23 14:02
add the breakpoint to webpack dist, then run command with debug

**Comment by antfu** [comment] 2023-08-25 17:26
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-25 17:26 UTC

**Comment by tong822218** [comment] 2023-10-12 07:46
我也遇到了这个问题，请问大家怎么解决的
