### ISSUE TITLE
Shortcuts with Breakpoints, it doesn't seem to work

### ISSUE THREAD

**Issue by kuworking** [unocss/unocss#3140] opened 2023-09-19 19:14 UTC
### Clear and concise description of the problem

Something like this, doesn't work (at least in my code):

```
  shortcuts: {
    responsive: 'max-w-fit sm:max-w-[500px] md:max-w-[700px] lg:max-w-[900px]',
  },
```

But it would be useful for unification purposes in one's code, imho.

### Suggested solution

Completely ignorant about if this is feasible, or it requires a major recoding, but I just think it makes sense that this could work.

### Alternative

The alternative is not to use shortcuts.

### Additional context

*Haven't found any related info in google and in the issues

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment] 2023-09-20 01:15
First, you need to provide a framework you use such as vite+vue or vite+react or other versions you use. It is best to give a demo that can be reproduced, otherwise, there will be no way to solve better the problem you encounter. question

**Comment by zyyv** [comment] 2023-09-20 03:33
Any questions?  [Playground](https://unocss.dev/play/?html=DwEwlgbgBATgpgZwA4HsB2DJygIwHwBQUUwOArgC4Xp4WIXAD05VNBT4EeQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpwxQCGuAzltCBlACLBQYDGMwANwwNKqGvSYs2ANVpRg9GAHEoEAK5hKAXzhZVIOAHI1uCDwYNDSUJFiI4YbgwwwAqs6xqANnB16IBsam5gwAtI7CLqFqHt5WSBgAHrbwmFi03qnYeITEZAAUyKgMABbQMDxqMAwAXIhUqADudGBgbHWGjaEMPNwYuHAl3b0Y-bo8E4aiqHBOkIyCGB0gtImhXTjwDCA1K2tdANoArAAMJ2CJALpwIGi7q%2BuhBwDsZxfXXqT3%2B08AnG9XKZULTTCLOap1A4NBxOFzubDeQrQ1DAHjEWr1GZYuA9WheJZwACMADoAEzTbFwHhoXAdEowGBgWoAemZwhAxNKzKBlJB0K0AEpppdpuJGMwoKwoBiDmLJJK2JxuHxFgx8kLqHRxVIoLJ5IoVOowOqRUhBUggA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA)

**Comment by antfu** [comment] 2023-09-20 03:49
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-20 03:49 UTC

**Comment by kuworking** [comment] 2023-09-20 05:37
> Any questions? [Playground](https://unocss.dev/play/?html=DwEwlgbgBATgpgZwA4HsB2DJygIwHwBQUUwOArgC4Xp4WIXAD05VNBT4EeQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpwxQCGuAzltCBlACLBQYDGMwANwwNKqGvSYs2ANVpRg9GAHEoEAK5hKAXzhZVIOAHI1uCDwYNDSUJFiI4YbgwwwAqs6xqANnB16IBsam5gwAtI7CLqFqHt5WSBgAHrbwmFi03qnYeITEZAAUyKgMABbQMDxqMAwAXIhUqADudGBgbHWGjaEMPNwYuHAl3b0Y-bo8E4aiqHBOkIyCGB0gtImhXTjwDCA1K2tdANoArAAMJ2CJALpwIGi7q%2BuhBwDsZxfXXqT3%2B08AnG9XKZULTTCLOap1A4NBxOFzubDeQrQ1DAHjEWr1GZYuA9WheJZwACMADoAEzTbFwHhoXAdEowGBgWoAemZwhAxNKzKBlJB0K0AEpppdpuJGMwoKwoBiDmLJJK2JxuHxFgx8kLqHRxVIoLJ5IoVOowOqRUhBUggA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA)

Thanks @zyyv it does work, the mistake is that I didn't understand how shortcuts work. I was using `class="responsive"` instead of `<div responsive class="">`

Thanks again!
