### ISSUE TITLE
Using @ container and @ apply simultaneously does not work in production environments

### ISSUE THREAD

**Issue by dalidaliW** [unocss/unocss#3550] opened 2024-02-04 03:45 UTC
### UnoCSS version

0.58.2

### Describe the bug

Using @ container and @ apply simultaneously does not work in production environments
`
    [
      /^@cq-([\d]+)px-([\d]+)px:(.*)$/,
      ([, startnum, endNum], { rawSelector, theme }) => {
        const selector = e(rawSelector)
        const tail = rawSelector.split(/@cq-[\d]+px-[\d]+px:/)[1]
        return `
              @container  ( min-width: ${startnum}px )  and   (max-width: ${endNum}px ) {
                ${selector} {
                  @apply ${tail}
                }
              }
          `
      }
    ],
<div class='@container'>
  <div class='@cq-100px-200px:colol-red'>

  </div>
</div>

`
Everything is good in the dev environment. Pro environment: @ apply: incorrect attributes

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFKgABAmwycw7MgD4AUFCihIUALacoBFJ1q0AvACIFARzgBGGQAcccAJxePbngCMAczgyLBBrKC0dHT1obDw4AFYcdAQAd2dZQTAjbDg-FiRiIjhuDC5ibM5cxUL8VQRVEQ4snKw4ECQBUXFHWkionQBVVgBhAGUx7SjgAHpwCH7o%2BagWFwBmWTj8FADKVI3ZA0cdPyg-OAAKWhYUMBAoEJAASgipgYAVGA5VWmVSFeI7SwRmI9wAghgWAYwAQoOMxlASAFVFgAHRvXRzSCLXTLAwAJko1BwUAAVkhfmAEABPQgkciYXD4fHJFbrWQwFgQLBkGyrAAcUmsOOinAxAzAhE4ZHygJQLACLDgyIwMCQfnFUS2cFUXzIIk1OhgIQQNhgGAwLloPBmMxVar8qMUBhmhRYBAsrtYHto1kNmGlASwGBsAH0-GZiABrP0DHTqWacHGzeb9FPYzTphaZ5acPzXFBIbBnFgWqGJB5gALmuCyagIfCbJl00g8tkbPYHfriEDAwT3ADtUB%2BfzKQ%2BQaGpJgpkOhAC889RM1iFkA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XtIz9TMzwAB6AAJMAI7IxbUAOqgTANQAlNxEmzt7RydVxQB0AFSHACTA0zNbPW2Y-PAWnD3g8FQADlflNejRMAB3ADK4DwLD4PUQAAtwJxwONDqAALwAPgkDXmfQ8aQM8PaNBxEGKEJhcPACJoh0J83c8DaoEQmFg0CptNh5L4N0g3DgiGKwFWG3OBxOyBl%2ByuwEOtQAjBMWTM6IgLDR4KAAAaaokzVaqLmKSmgYqgTgIZCQ2CoFE1R7iT7fX6BE6gLGgTCAt6cTCnR3O5Gu8QA4Fen1YsomxPSN1khkU4IJpNJ5aYbii2ygN0W6CBY1Z0tZokVrNGk3V6RTHSN6SQZF8RAtAQ1TNRFptDqt9udyJDVgkZDQdSc4goPgB9QYtsAN3ANCqY5QrEw0G6OkCXicBi7dUJh78VGKh1eZ%2BMpkYlmsdkv158iDcHlKmsgTG34BqqpuAAmV5pCYVB4CGZFTG4SAqhAKBOGFZFgF3eZAivJsgmZIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFyQCuApgL5A

### System Info

vue:3.4.2  vite:5.0.10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TomatoDroid** [comment] 2024-04-18 14:04
your link doesn't work, it seems to be an error in the rule function, can you provide a reproducible environment

**Comment by Simon-He95** [comment] 2024-05-15 03:30
<img width="1184" alt="image" src="https://github.com/unocss/unocss/assets/57086651/4f6372e1-dfb3-4e7a-a01d-93374c11263c">
There is an error in your reproduced demo.
I will temporarily close this issue. Once you can reproduce it correctly, you are welcome to open this issue again.

**Closed by Simon-He95** 2024-05-15 03:30 UTC
