### ISSUE TITLE
 plugin 'unocss:xxxxxx' uses deprecated 'transform' option. Use 'handler' option instead. 

### ISSUE THREAD

**Issue by rczdgbg** [unocss/unocss#3530] opened 2024-01-26 06:53 UTC
### UnoCSS version

0.58.4

### Describe the bug

![image](https://github.com/unocss/unocss/assets/38928451/442f579b-c89b-4578-9f8c-92d407720a8b)

### Reproduction

-

### System Info

Nuxt: 3.9.3
@unocss/nuxt: 0.58.4
vite:5.0.11

### Validations

- [ ] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [ ] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by w3bsite** [comment] 2024-02-15 01:26
I have the same issue, anything there do about it?

**Comment by userquin** [comment] 2024-02-15 11:23
you can ignore the warning, I'll try to add the new transform

**Comment by userquin** [comment] 2024-02-15 11:45
It is already there, the warning can be ignored, no idea why Vite warning is there.

Here the warning in Vite https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/html.ts#L1150-L1163 and here https://github.com/unocss/unocss/blob/main/packages/vite/src/transformers.ts#L19-L25 the transform plugins, every transformer with new order and handler (Vite 5) and old enforce and transform (Vite < 5) pair entries

The `unocss:global` plugin also with both pair entries: https://github.com/unocss/unocss/blob/main/packages/vite/src/modes/global/dev.ts#L134-L146

can you provide a minimal reproduction?

**Comment by antfu** [comment] 2024-02-15 11:56
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by antfu** [comment] 2024-02-15 11:56
This is already be fixed a long while ago. It's probably because you still have the old version, if not, a reproduction is required.

**Closed by antfu** 2024-02-15 11:56 UTC
