### ISSUE TITLE
uno.config.mjs Error[modlue not found], import with relative path module

### ISSUE THREAD

**Issue by rex-ll** [unocss/unocss#4034] opened 2024-07-31 08:02 UTC
### UnoCSS version

0.61.8

### Describe the bug

Importing a module with a relative path in the configuration file gives an error module not found

### Reproduction

![image](https://github.com/user-attachments/assets/9075d012-b9c3-44af-b942-520905b259ec)
![image](https://github.com/user-attachments/assets/1264f65c-adb8-4755-85b7-04732acf7aa0)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rex-ll** [comment] 2024-07-31 08:46
It had been loading fine before, but after upgrading to the latest version it reported an error.

**Comment by QaahirStewart** [comment] 2024-07-31 13:35
Yeah any updates after  0.61.4, anything in my Uno.config.js doesn't work/ not getting loaded.

**Comment by antfu** [comment] 2024-07-31 16:00
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-31 16:00 UTC

**Comment by rex-ll** [comment] 2024-08-01 10:38
> Yeah any updates after 0.61.4, anything in my Uno.config.js doesn't work/ not getting loaded.

As of now it's only a fallback version
