### ISSUE TITLE
How to fix UNOCSS config is not a known property in Nuxt 3 config

### ISSUE THREAD

**Issue by lynxionxs** [unocss/unocss#2383] opened 2023-03-22 10:19 UTC
### UnoCSS version

0.50.6

### Describe the bug

```Error: Object literal may only specify known properties, and 'unocss' does not exist in type 'NuxtConfig'...```

![unknown-config-prop_2023-03-22_12-11-09](https://user-images.githubusercontent.com/7606938/226872470-f04d08a9-ff69-4782-887b-d0e4c2b79572.png)

```json
// tsconfig.json
{
	"extends": "./.nuxt/tsconfig.json",
	"compilerOptions": {
		"module": "ESNext",
		"target": "es2016",
		"lib": [
			"es2016",
			"dom"
		],
		"moduleResolution": "node",
		"skipLibCheck": true,
		"typeRoots": [
			"./node_modules/@types"
		],
	},
	"vueCompilerOptions": {
		"skipTemplateCodegen": true
	}
}
```

### Reproduction

none

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrislutw** [comment] 2023-04-18 06:45
> ### UnoCSS version
> 0.50.6
> 
> ### Describe the bug
> `Error: Object literal may only specify known properties, and 'unocss' does not exist in type 'NuxtConfig'...`
> 
> ![unknown-config-prop_2023-03-22_12-11-09](https://user-images.githubusercontent.com/7606938/226872470-f04d08a9-ff69-4782-887b-d0e4c2b79572.png)
> 
> ```json
> // tsconfig.json
> {
> 	"extends": "./.nuxt/tsconfig.json",
> 	"compilerOptions": {
> 		"module": "ESNext",
> 		"target": "es2016",
> 		"lib": [
> 			"es2016",
> 			"dom"
> 		],
> 		"moduleResolution": "node",
> 		"skipLibCheck": true,
> 		"typeRoots": [
> 			"./node_modules/@types"
> 		],
> 	},
> 	"vueCompilerOptions": {
> 		"skipTemplateCodegen": true
> 	}
> }
> ```
> 
> ### Reproduction
> none
> 
> ### System Info
> _No response_
> 
> ### Validations
> * [x]  Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

What nuxt version do you use ?

I have same problem with

- nuxt: 3.2.2
- @nuocss/nuxt: 0.49.7

and upgrade to solved

- nuxt: 3.4.1
- @nuocss/nuxt: 0.51.4

**Comment by antfu** [comment] 2023-04-18 12:21
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2023-04-18 12:21 UTC
