### ISSUE TITLE
Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by vaechy** [unocss/unocss#1384] opened 2022-08-06 11:21 UTC
我尝试在vite+react+ts的工程中使用，引入"uno.css"报错。是什么原因？
```json
{
  "name": "vite-react-ts",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite --host",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.3.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "@unocss/preset-attributify": "^0.45.5",
    "@unocss/preset-icons": "^0.45.5",
    "@unocss/preset-uno": "^0.45.5",
    "@vitejs/plugin-react": "^2.0.0",
    "sass": "^1.54.1",
    "typescript": "^4.6.4",
    "unocss": "^0.45.5",
    "vite": "^3.0.0"
  }
}

```

**Comment by antfu** [comment] 2022-08-06 15:16
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-06 15:16 UTC
