### ISSUE TITLE
vitesse-lite dev startup problem      [unocss] entry module not found, have you add `import 'uno.css'` in your main entry?

### ISSUE THREAD

**Issue by xiaojia21190** [unocss/unocss#699] opened 2022-03-12 07:48 UTC
[unocss] entry module not found, have you add `import 'uno.css'` in your main entry?

**Comment by xiaojia21190** [comment] 2022-03-12 07:49
![image](https://user-images.githubusercontent.com/16084693/158009141-41c184cc-cbc5-482a-b181-26d39e9800c9.png)

**Comment by antfu** [comment] 2022-03-12 10:19
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-03-12 10:19 UTC

**Comment by MarvinXu** [comment] 2022-03-16 15:34
I have this problem occasionally. Fixed it by restarting server.
Not knowing how to reproduce yet, might look into it later.
![image](https://user-images.githubusercontent.com/7382357/158627503-630e15a0-7a31-492c-b4bd-63a5de7c54db.png)

**Comment by satrong** [comment] 2022-03-17 10:22
@antfu Maybe... [`resolvedId`](https://github.com/unocss/unocss/blob/main/packages/vite/src/modes/global/dev.ts#L114) will not be fired when the dev link is not opened in browser within 10 seconds, and `resolved` will be `false` always. 
After 10s, the `setTimeout`'s callback in the [`setWarnTimer`](https://github.com/unocss/unocss/blob/main/packages/vite/src/modes/global/dev.ts#L57) method will be fired.

**Comment by QC2168** [comment] 2022-08-07 04:37
I had same problem

**Comment by prodkt** [comment] 2022-10-09 02:18
I'm getting the same issue was this really not solved?
