### ISSUE TITLE
v0.59.3 breaks VSCode

### ISSUE THREAD

**Issue by tobiasdalhof** [unocss/unocss#3733] opened 2024-04-16 11:41 UTC
### UnoCSS version

v0.59.3

### Describe the bug

There seems to be an issue with the latest version of the VSCode extension. Saving files takes forever. Downgrading to v0.59.2 solves the issue.

### Reproduction

https://github.com/tobiasdalhof/unocss-issue-3733/

### System Info

VSCode

```
Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-04-16 13:28
@Simon-He95 Can you help to take a look? Thank you

**Comment by tobiasdalhof** [comment] 2024-04-16 13:51
Probably caused by https://github.com/unocss/unocss/pull/3728

**Comment by Simon-He95** [comment] 2024-04-16 14:22
> Probably caused by #3728

hi, @tobiasdalhof can you provide a reproduce demo

**Comment by tobiasdalhof** [comment] 2024-04-17 09:41
Hey @Simon-He95,

I'm unable to whip up a demo for you right now, but here's the deal: I've got a monorepo using pnpm. Inside, I've got a bunch of frontends built with Vite, and they all share a single `unocss.config.ts` file.

Here's what my repo structure looks like:

```
📁 /backend
📁 /frontend-1
  📄 package.json
  📄 vite.config.ts
📁 /frontend-2
  📄 package.json
  📄 vite.config.ts
📁 /frontend-3
  📄 package.json
  📄 vite.config.ts
📄 package.json
📄 unocss.config.ts
```

And here's a snippet from a `vite.config.ts` file as an example:

```ts
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import UnoCSS from 'unocss/vite'

export default defineConfig({
  plugins: [
    UnoCSS(resolve(__dirname, '../unocss.config.ts')),
  ],
})
```

Let me know if you need more info or if there's anything else I can assist you with.

**Comment by tobiasdalhof** [comment] 2024-04-18 09:22
I was able to solve the issue by adding a `unocss.config.ts` to each package. My structure now looks like this:

```
📁 /backend
📁 /frontend-1
  📄 package.json
  📄 unocss.config.ts
  📄 vite.config.ts
📁 /frontend-2
  📄 package.json
  📄 unocss.config.ts
  📄 vite.config.ts
📁 /frontend-3
  📄 package.json
  📄 unocss.config.ts
  📄 vite.config.ts
📁 /shared
  📄 package.json
  📄 unocss.config.ts
📄 package.json
```

Helper function in `/shared/unocss.config.ts` to create UnoCSS `UserConfig`:

```ts
import type { UserConfig } from 'unocss'

export function createConfig(): UserConfig {
  return {
    // ...
  }
}
```

**Comment by Simon-He95** [comment] 2024-04-18 10:05
@tobiasdalhof Can you help me test whether this version of the plugin can solve this problem? Please disable unocss and use this test version [unocss-test](https://marketplace.visualstudio.com/items?itemName=simonhe.unocss-test)

**Comment by tobiasdalhof** [comment] 2024-04-18 11:10
> @tobiasdalhof Can you help me test whether this version of the plugin can solve this problem? Please disable unocss and use this test version [unocss-test](https://marketplace.visualstudio.com/items?itemName=simonhe.unocss-test)

Thanks for looking into it. The issue still persists

**Comment by Simon-He95** [comment] 2024-04-19 08:29
> > @tobiasdalhof Can you help me test whether this version of the plugin can solve this problem? Please disable unocss and use this test version [unocss-test](https://marketplace.visualstudio.com/items?itemName=simonhe.unocss-test)
> 
> @Simon-He95 Thanks for looking into it. The issue still persists

I think the best way is for you to provide a repo that reproduces the problem you mentioned so that I can track it.

**Comment by antfu** [comment] 2024-04-19 08:50
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by Simon-He95** [comment] 2024-04-20 04:21
> @antfu @Simon-He95 I was able to reproduce the issue. Please check https://github.com/tobiasdalhof/unocss-issue-3733/
> 
> VSCode slows down when I open my laravel routes file. It contains a fair amount of square brackets, which is probably causing the issue
> 
> Regular expression was recently changed in #3712

Thank you very much for providing a particularly detailed reproduction demo.

**Closed** 2024-04-20 15:03 UTC

**Comment by oommgg** [comment] 2024-04-24 08:25
Hi, I have the same issue with this problem.

the test file is:

https://github.com/tobiasdalhof/unocss-issue-3733/blob/main/test.php

with 

```php
Route::get('/some-route', [SomeController::class, 'someMethod']);
Route::get('/some-route', [SomeController::class, 'someMethod']);
Route::get('/some-route', [SomeController::class, 'someMethod']);
...
```

and my `api.php` for laravel router is:

```php
Route::get('test', 'TestController@index');
Route::get('test', 'TestController@index');
Route::get('test', 'TestController@index');
```

<img width="787" alt="截圖 2024-04-24 16 23 28" src="https://github.com/unocss/unocss/assets/210464/6e255773-2d10-4dec-97e8-9d7c62ef4dc1">

I clone `https://github.com/tobiasdalhof/unocss-issue-3733/` this repo

and it still happend on unocss 0.59.4 vscode extension

**Comment by Simon-He95** [comment] 2024-04-24 08:49
> @Simon-He95 @antfu
> 
> Hi, I have the same issue with this problem.
> 
> the test file is:
> 
> https://github.com/tobiasdalhof/unocss-issue-3733/blob/main/test.php
> 
> with
> 
> ```
> Route::get('/some-route', [SomeController::class, 'someMethod']);
> Route::get('/some-route', [SomeController::class, 'someMethod']);
> Route::get('/some-route', [SomeController::class, 'someMethod']);
> ...
> ```
> 
> and my `api.php` for laravel router is:
> 
> ```
> Route::get('test', 'TestController@index');
> Route::get('test', 'TestController@index');
> Route::get('test', 'TestController@index');
> ```
> 
> <img alt="截圖 2024-04-24 16 23 28" width="787" src="https://private-user-images.githubusercontent.com/210464/325140435-6e255773-2d10-4dec-97e8-9d7c62ef4dc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDg1NTIsIm5iZiI6MTcxMzk0ODI1MiwicGF0aCI6Ii8yMTA0NjQvMzI1MTQwNDM1LTZlMjU1NzczLTJkMTAtNGRlYy05N2U4LTlkN2M2MmVmNGRjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwODQ0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjNjNTgwODMwNjVkYzI0Y2Y3NGFiYjczMDgxYzI1ZWRkZDU5YWFhYzI1YTRiMDc3ZDcxY2MzZDExY2Q0NmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zbxIGqX_KJRiBObvynCFewUCc_fGHZ220tYIVUbPkfc">
> I clone `https://github.com/tobiasdalhof/unocss-issue-3733/` this repo
> 
> and it still happend on unocss 0.59.4 vscode extension

0.59.4 did not merge this pr😂
