### ISSUE TITLE
在uniapp中显示不出来图标

### ISSUE THREAD

**Issue by github-cherry** [unocss/unocss#3633] opened 2024-03-18 05:08 UTC
### UnoCSS version

0.58.5

### Describe the bug

都配置好了unocss，但是iocnify出不来？我看[别人的项目就能出来](https://github.com/codercup/unibest)，怎么回事啊？
# 我的配置
uno.config.js
```javascript
import {
	defineConfig,
	presetAttributify,
	presetIcons,
	transformerDirectives,
	transformerVariantGroup,
} from 'unocss'

import {
	presetApplet,
	presetRemRpx,
	transformerApplet,
	transformerAttributify,
} from 'unocss-applet'


export default defineConfig({
	presets: [
		presetApplet(),
		presetAttributify(),
		presetRemRpx(),
		// 支持图标，需要搭配图标库，eg: @iconify-json/carbon, 使用 `<button class="i-carbon-sun dark:i-carbon-moon" />`
		presetIcons({
			scale: 1.2,
			warn: true,
			extraProperties: {
				display: 'inline-block',
				'vertical-align': 'middle',
			},
		}),
	],
	/**
	 * 自定义快捷语句
	 * @see https://github.com/unocss/unocss#shortcuts
	 */
	shortcuts: [
		['flex-center', 'flex justify-center items-center'],
		['grid-center', 'flex justify-center items-center']
	],
	transformers: [
		// 启用 @apply 功能
		transformerDirectives(),
		// 启用 () 分组功能
		// 支持css class组合，eg: `<div class="hover:(bg-gray-400 font-medium) font-(light mono)">测试 unocss</div>`
		transformerVariantGroup(),
		// Don't change the following order
		transformerAttributify({
			// 解决与第三方框架样式冲突问题
			prefixedOnly: true,
			prefix: 'fg',
		}),
		transformerApplet(),
	]
})

```

vite.config.js
![image](https://github.com/unocss/unocss/assets/43592730/97e75988-44b6-4bc1-bc50-1aa72fe17ab7)

main.js
![image](https://github.com/unocss/unocss/assets/43592730/4cecb8c5-34d8-4471-a2f7-8e8d7bbed503)

我安装的图标
![image](https://github.com/unocss/unocss/assets/43592730/f348d214-7f02-47a7-8221-bef6c25b43cf)

使用图标
![image](https://github.com/unocss/unocss/assets/43592730/9726c9dc-b735-4fe2-8747-c97272b15fc1)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-03-18 05:38
https://github.com/codercup/unibest/blob/main/package.json#L114 你装依赖了吗

**Comment by github-cherry** [comment] 2024-03-18 05:41
> https://github.com/codercup/unibest/blob/main/package.json#L114 你装依赖了吗

安装了，我用的是tabler
![image](https://github.com/unocss/unocss/assets/43592730/ff46355b-7d01-4f18-882e-48a4b751c323)

**Comment by Simon-He95** [comment] 2024-03-18 06:13
> > https://github.com/codercup/unibest/blob/main/package.json#L114 你装依赖了吗
> 
> 安装了，我用的是tabler ![image](https://private-user-images.githubusercontent.com/43592730/313561392-ff46355b-7d01-4f18-882e-48a4b751c323.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDI2NTcsIm5iZiI6MTcxMDc0MjM1NywicGF0aCI6Ii80MzU5MjczMC8zMTM1NjEzOTItZmY0NjM1NWItN2QwMS00ZjE4LTg4MmUtNDhhNGI3NTFjMzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA2MTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOGZlODRkYzI4YzUxNzEzZTkxOTE3MzlhYjRkOGRlYjRiNzZiMzdmZGIyYzc1MTI1YjBkNjEzZDRhZTdiMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b6hI7FserbRmT1r_u95HVs1Do0TLvuxYFmkiA-0v2tQ)

You'd better provide a minimal demo that can be reproduced

**Comment by antfu** [comment] 2024-03-18 09:30
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-18 09:30 UTC

**Comment by chergn** [comment] 2024-09-30 01:03
> You'd better provide a minimal demo that can be reproduced

https://gitee.com/eida/uniapp-init
