### ISSUE TITLE
Preset Icons is not working in Nuxt 3

### ISSUE THREAD

**Issue by cesswhite** [unocss/unocss#883] opened 2022-04-27 17:56 UTC
_nuxt.config.ts_

 ```
 unocss: {
    uno: true,
    icons: true,
    preflight: true,
    attributify: true,
  },
```

_package.json_

 ```
 "devDependencies": {
    "@babel/core": "^7.17.9",
    "@unocss/nuxt": "^0.31.5",
    "babel-loader": "^8.2.4",
    "nuxt3": "latest",
    "vue-loader": "^16.8.3"
  },
```

_app.vue_

<img width="359" alt="Captura de Pantalla 2022-04-27 a la(s) 12 53 56" src="https://user-images.githubusercontent.com/44076866/165589184-2f9613f9-2156-4f8f-b6c5-9f2a332f3740.png">

_unocss inspector_

![Captura de Pantalla 2022-04-27 a la(s) 12 54 43](https://user-images.githubusercontent.com/44076866/165589452-be8362fe-61b9-4996-ac4f-d48ccca8d13f.png)

**Comment by antfu** [comment] 2022-04-27 19:51
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://github.com/antfu/vitesse-nuxt3

**Closed by antfu** 2022-04-27 19:51 UTC
