### ISSUE TITLE
unocss/vite responsive not working on production

### ISSUE THREAD

**Issue by khaledtag98** [unocss/unocss#1080] opened 2022-06-08 14:06 UTC
Hello guys,

I'm using unocss/vite in my quasar website. My problem is when I use tailwindcss responsive template ( Ex:  md:h-9  lg:h-12 )
it doesn't work on production

**Comment by antfu** [comment] 2022-06-08 15:07
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-08 15:07 UTC
