### ISSUE TITLE
 Lost some style in the production environment

### ISSUE THREAD

**Issue by fxzer** [unocss/unocss#2837] opened 2023-07-06 09:04 UTC
### UnoCSS version

 "@unocss/nuxt": "^0.51.13", "nuxt": "^3.6.0",

### Describe the bug

前两天的项目一点问题没有，今天项目部署完发现 unocss 的样式丢失了，试着降了nuxt,unocss 版本降回上个礼拜一样，还是没有解决，是不是有什么配置不对呢？
There was no problem with the project in the previous two days. After the project deployment, I found that the style of the UNOCSS was lost. Try to reduce the NUXT. The UNOCSS version was reduced to the same week. It was still not solved. Is there any configuration?

## 生产环境样式丢失 Lost some style in the production environment
（pnpm build && pnpm generate && pnpm preview 和 部署到服务器样式都丢失）

![image](https://github.com/nuxt/nuxt/assets/68853957/919a2d69-acda-4495-b30e-4b4eaf61216c)

![image](https://user-images.githubusercontent.com/68853957/251400637-dc8044db-18ca-4fcd-a1b0-b38b0d50b05a.png)

## 开发环境正常 The development environment is normal

![image](https://github.com/nuxt/nuxt/assets/68853957/4658f5ae-b8b6-4cd4-a5b4-eebb96a59ea2)
![image](https://github.com/unocss/unocss/assets/68853957/7071b593-6b99-40ef-8445-4570a85e4b4b)

### Reproduction

Lost some style in the production environment

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-07-06 09:08
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by fxzer** [comment] 2023-07-06 09:39
I'm very sorry that I didn't consider it just now. This is an minimal reproduction(https://stackoverflow.com/help/minimal-reproducible-example)

```
git clone git@github.com:fxzer/loss-style.git
start:   ni && nr dev
preview:  nr build && nr generate && nr preview
```

**Comment by fxzer** [comment] 2023-07-06 10:03
Because I need to use (MAX-MD :) such a breakpoint range, at the beginning, only UNOCSS could not use this syntax, so I added TailWindCSS
因为我需要使用到 (max-md:)这样的自定义断点范围，刚开始仅仅用 unocss没办法使用这个语法，所以就把 tailwindcss加上了

**Closed** 2023-07-06 10:26 UTC

**Comment by fxzer** [comment] 2023-07-06 11:31
> Because I need to use (MAX-MD :) such a breakpoint range, at the beginning, only UNOCSS could not use this syntax, so I added TailWindCSS 因为我需要使用到 (max-md:)这样的自定义断点范围，刚开始仅仅用 unocss没办法使用这个语法，所以就把 tailwindcss加上了

我现在才发现可以用这个unocss 自带的这个语法，和 Tailwindcss的（max-lg:）一样的作用😁
![image](https://github.com/unocss/unocss/assets/68853957/4d03f965-9b09-4068-b2ec-5432804170c8)
