### ISSUE TITLE
Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by hi-noikiy** [unocss/unocss#3171] opened 2023-09-26 10:48 UTC
### UnoCSS version

0.46.5

### Describe the bug

使用pnpm安装的，用的淘宝的源。应该是某些依赖版本不够严谨。会出现下面的错误：
<img width="1112" alt="image" src="https://github.com/unocss/unocss/assets/32630320/92f86b34-5bb8-489b-8d3e-540000e65811">

console.log发现config并没有separators这个key

### Reproduction

1、clone这个项目https://github.com/xinlc/uniapp-vue3-ts-template
2、删掉里面的pnpm-lock.yaml
3、执行pnpm install
4、安装完毕后运行pnpm dev:h5即可重现

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-09-26 10:51
Can you help narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

**Comment by antfu** [comment] 2023-09-26 10:51
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-26 10:51 UTC
