### ISSUE TITLE
install unocss error

### ISSUE THREAD

**Issue by rex-ll** [unocss/unocss#3780] opened 2024-05-09 01:43 UTC
### UnoCSS version

0.60.0

### Describe the bug

No matching version found for @unocss/extractor-arbitrary-variants@0.60.0

This error happened while installing the dependencies of unocss@0.60.0

The latest release of @unocss/extractor-arbitrary-variants is "0.59.4".

If you need the full list of all 68 published versions run "$ pnpm view @unocss/extractor-arbitrary-variants versions".

### Reproduction

run `pnpm i unocss`

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-05-09 09:50
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-05-09 09:50 UTC
