### ISSUE TITLE
using transformerVariantGroup causes the component to load repeatedly

### ISSUE THREAD

**Issue by duanmw** [unocss/unocss#2091] opened 2023-01-18 03:19 UTC
in unocss.config.js
```
...
defineConfig({
  presets: [presetUno(), presetAttributify(), presetIcons()],
  transformers: [transformerVariantGroup()],
})
```
then use variant group in component 
![image](https://user-images.githubusercontent.com/31787613/213074722-01882d54-f9da-4f2f-87e2-496b2b7e65df.png)

Then I noticed that every time I switched routes, the component would reload, but it is a component of the parent route and should not be recreated. I tried other components and found that whenever I used variant group, it would be loaded repeatedly
![image](https://user-images.githubusercontent.com/31787613/213072100-349ad689-7a81-4a91-a247-120b56fe89af.png)

### expectation:
Using transformerVariantGroup should not cause components to load repeatedly

**Comment by lishaobos** [comment] 2023-02-07 07:00
Can you provide a reproduction?

**Comment by antfu** [comment] 2023-02-07 14:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-07 14:23 UTC

**Comment by duanmw** [comment] 2023-02-08 02:51
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)


**reproduction**:
https://stackblitz.com/edit/vitejs-vite-7hn1nr?file=src%2FApp.vue
in this example, 'HelloWorld' and 'OtherHello' are sibling components, 'HelloWorld' use variant group, the component would reload when switch route.

https://user-images.githubusercontent.com/31787613/217415428-884edbe7-20dd-4020-b409-496c6fb016d0.mp4

**Comment by lishaobos** [comment] 2023-02-08 06:58
@antfu is this behaviour intended?

if i use VariantGroup in A.vue, A.vue is add to affectedModules

![image](https://user-images.githubusercontent.com/46661044/217451258-a66e4e4d-dd59-44e1-b342-d13c619d3761.png)


if other file extracted, tokens.size always increaseed, so A.vue is repeat update

![image](https://user-images.githubusercontent.com/46661044/217450941-c99dbf66-3ee7-4d67-a333-ad4f276a7df5.png)

![image](https://user-images.githubusercontent.com/46661044/217450893-c796423f-5b0e-42cc-ab9c-27eb8c6a8666.png)

![image](https://user-images.githubusercontent.com/46661044/217455754-43a99d15-7a47-422d-a9e3-e551609ffa69.png)
