### ISSUE TITLE
@apply classes will not update when config updated

### ISSUE THREAD

**Issue by kaiser-9527** [unocss/unocss#826] opened 2022-04-13 17:09 UTC
// unicss.config.ts
```ts
{
    theme: {
        colors: {
            primary: '#333333'
        }
    }
}
```

// components

```css
.title {
    @apply text-primary;
}
```

when i update the primary color to `#666666`, the title text color is still `#333333`

**Comment by TrickyPi** [comment] 2022-06-05 05:00
I don't run into this issue when i config the theme in vite.config.ts.
It's my vite.config.ts
```ts
import { defineConfig } from 'vite'
import Unocss from 'unocss/vite'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'
import transformerDirectives from '@unocss/transformer-directives'
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    Unocss({
      transformers: [transformerDirectives()],
      theme: {
        colors: {
          primary: '#333333'
        }
      }
    }),
    tsconfigPaths(),
  ],
})
```

I guess the problem is that the change of uno.config.js didn't active vite/(other build tools) recompile, but I think if you need live updates when the theme is updated, it's more appropriate to config this in vite.config.ts.

**Comment by antfu** [comment] 2022-06-05 13:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by TrickyPi** [comment] 2022-06-06 01:56
this #837 pr has been reverted in #917

**Closed** 2022-06-29 08:57 UTC
Labels: directives, hmr
