### ISSUE TITLE
@unocss/webpack configure file not functional

### ISSUE THREAD

**Issue by whitemay** [unocss/unocss#1298] opened 2022-07-19 04:35 UTC
it seems that config file do not work functional. 
presets and shortcuts works fine, but themes not merged: no matter defined in config root or used in preset params.
my config file like below:
```
import presetMini from '@unocss/preset-mini'

module.exports = {
  presets: [
    presetMini(),
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      'center': 'flex justify-center items-center',
    },
  ],
  theme: {
    fontSize: {
      '3xl': ['0.75rem', '1rem']
    }
  }
}
```

**Comment by antfu** [comment] 2022-07-19 06:10
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by whitemay** [comment] 2022-07-19 07:19
参见 https://github.com/whitemay/unocss-error-2.git

**Closed** 2022-07-19 07:46 UTC
