### ISSUE TITLE
How to make sure the uno reset is in the first position?

### ISSUE THREAD

**Issue by SunnyCrypto** [unocss/unocss#932] opened 2022-05-04 06:58 UTC
I'm building a nuxt3 application with the `unocss` and a UI library.

I import the UI library through a nuxt plugin.

plugins/x-ui.ts
```ts
import XUI from 'x-ui'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(XUI)
})
```

Then specified the `preflight: true` in `nuxt.config.ts` file.

```ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: [
    '@unocss/nuxt',
    '@pinia/nuxt',
  ],
  build: {
    transpile: ['x-ui']
  },
  unocss: {
    preflight: true,
  },
  css: [
    'x-ui/style', // import the UI library style
  ],
})
```

When I run the project, I find the preset CSS is in front of the UI library CSS, which leads to some abnormal displays.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/59635374/166632345-1c5e55f4-4492-4fc6-b330-24c9f91902b7.png">

Checked the CSS load sequences, the tailwind reset CSS is loaded after the UI library CSS.

- style.css (UI Library CSS)
- main.css (main CSS from the nuxt project)
- tailwind.css (reset CSS from uno)

<img width="921" alt="image" src="https://user-images.githubusercontent.com/59635374/166633537-c59e6abb-a509-4f29-bdd6-60a1857e52a8.png">

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/59635374/166633624-974408ed-8602-424b-88da-74fd85eb7d9a.png">

**The question is could we always load the reset CSS in the first position?**
The ideal CSS load sequences should be
- tailwind.css (reset CSS from uno)
- style.css (UI Library CSS)
- main.css (main CSS from the nuxt project)

**Comment by gilesbutler** [comment] 2022-05-29 22:55
I just came across this issue too and I'm not using Nuxt. This happened after a fresh install of https://github.com/antfu/vitesse

**Comment by antfu** [comment] 2022-07-09 06:21
Can you share a reproduction so I can check it?

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-09 06:21 UTC
Labels: integration, nuxt
