### ISSUE TITLE
="" is added inside my files (RemixRun project)

### ISSUE THREAD

**Issue by AxelBriche** [unocss/unocss#1670] opened 2022-09-30 20:40 UTC
When I use this library, when I save my file (cmd+s), my attribute is changed.

`<div text-red-600>` become `<div text-red-600="">` inside my IDE code.

https://user-images.githubusercontent.com/1295251/193352630-4b28846c-c4de-43f3-9305-776644e3ac14.mp4

Is it normal that the transformer changes my .tsx code?

**Comment by sudongyuer** [comment] 2022-10-01 01:13
Can you provide a minimal reproduction ~

**Comment by chris-zhu** [comment] 2022-10-01 03:17
Are you using unocss `cli` package with `transformer-attributify-jsx`?

**Comment by antfu** [comment] 2022-10-01 05:00
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-10-01 05:00 UTC
Labels: cli
