### ISSUE TITLE
variables are incorrectly minified

### ISSUE THREAD

**Issue by jheng-jie** [unocss/unocss#2279] opened 2023-02-28 18:20 UTC
### UnoCSS version

0.50.1

### Describe the bug

- `0.50.1`

```css
:root {
  --un-pan-x:;--un-pan-y:;--un-pinch-zoom:;
}
```

- `0.49.4`

```css
:root {
  --un-pan-x: ;--un-pan-y: ;--un-pinch-zoom: ;
}
```

### Reproduction

- similar

[svelte#7288](https://github.com/sveltejs/svelte/issues/7288)
[esbuild#760](https://github.com/evanw/esbuild/issues/760)

### System Info

legacy browser will fail to resolve the variable

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-02-28 19:46
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by antfu** [comment] 2023-02-28 19:47
UnoCSS does not normally touches your own CSS. Please provide a proper production.

**Closed by antfu** 2023-02-28 19:46 UTC

**Comment by jheng-jie** [comment] 2023-03-01 02:30
@antfu sorry

[Reproducible](https://stackblitz.com/edit/nuxt-starter-8svbbt?file=nuxt.config.ts)

I found out that it is the problem of `transformerDirectives`

`0.49.4` or turn off `transformerDirectives` will not be wrong

```js
export default defineNuxtConfig({
  unocss: {
    transformers: [
      // variables are incorrectly minified
      transformerDirectives(),
    ],
    presets: [UnoPreset()],
  },
})
```

**Comment by sibbng** [comment] 2023-03-01 11:00
I confirm this is a regression introduced in #2229.
