### ISSUE TITLE
Tinymce Error

### ISSUE THREAD

**Issue by qiaer** [unocss/unocss#1405] opened 2022-08-12 06:01 UTC
- "tinymce": "^5.10.3"
- "unocss": "^0.45.6"
- "vite": "^2.9.9"

![image](https://user-images.githubusercontent.com/24616514/184294780-6bf41d5a-2995-4f60-8f49-bfa927ac3612.png)

![image](https://user-images.githubusercontent.com/24616514/184293846-129abaa4-cc3f-46a2-8bb7-958c9cd97e0d.png)

![image](https://user-images.githubusercontent.com/24616514/184293930-2a7b99ae-9614-44fa-ad7a-368b58cd941f.png)

**Comment by antfu** [comment] 2022-08-12 07:53
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-12 07:53 UTC

**Comment by cnelf** [comment] 2023-03-29 11:16
> * "tinymce": "^5.10.3"
> * "unocss": "^0.45.6"
> * "vite": "^2.9.9"
> 
> ![image](https://user-images.githubusercontent.com/24616514/184294780-6bf41d5a-2995-4f60-8f49-bfa927ac3612.png)
> 
> ![image](https://user-images.githubusercontent.com/24616514/184293846-129abaa4-cc3f-46a2-8bb7-958c9cd97e0d.png)
> 
> ![image](https://user-images.githubusercontent.com/24616514/184293930-2a7b99ae-9614-44fa-ad7a-368b58cd941f.png)

I encountered the same error. Have you solved this problem?
