### ISSUE TITLE
Deleting token in a transformer causing hmr error in nuxt

### ISSUE THREAD

**Issue by RebeccaStevens** [unocss/unocss#3585] opened 2024-02-29 04:10 UTC
### UnoCSS version

0.58.5

### Describe the bug

Calling `tokens.delete(token)` within a transformer results in an endless loop of errors and network requests for `index.vue` and `__uno.css`.

![image](https://github.com/unocss/unocss/assets/7224206/efc029ca-affb-4f35-93cc-0d8b886fa045)

<details>
<summary>Contents of those two files: </summary>

```js
import { createHotContext as __vite__createHotContext } from "/_nuxt/@vite/client";import.meta.hot = __vite__createHotContext("/pages/index.vue?macro=true");
const __nuxt_page_meta = null
export default __nuxt_page_meta

// Vite
if (import.meta.hot) {
  import.meta.hot.accept(mod => {
    Object.assign(__nuxt_page_meta, mod)
  })
}
// webpack
if (import.meta.webpackHot) {
  import.meta.webpackHot.accept((err) => {
    if (err) { window.location = window.location.href }
  })
}
```

```
import {createHotContext as __vite__createHotContext} from "/_nuxt/@vite/client";
import.meta.hot = __vite__createHotContext("/__uno.css");
import {updateStyle as __vite__updateStyle, removeStyle as __vite__removeStyle} from "/_nuxt/@vite/client"
const __vite__id = "/__uno.css"
const __vite__css = "..."
__vite__updateStyle(__vite__id, __vite__css)
import.meta.hot.accept()
import.meta.hot.prune(()=>__vite__removeStyle(__vite__id))
if (import.meta.hot) {
    try {
        let hash = __vite__css.match(/__uno_hash_(\w{6})/)
        hash = hash && hash[1]
        if (!hash)
            console.warn('[unocss-hmr]', 'failed to get unocss hash, hmr might not work')
        else
            await import.meta.hot.send('unocss:hmr', ['__ALL__']);
    } catch (e) {
        console.warn('[unocss-hmr]', e)
    }
    if (!import.meta.url.includes('?'))
        await new Promise(resolve=>setTimeout(resolve, 100))
}
document.querySelectorAll(`link[href="/_nuxt/__uno.css"]`).forEach(i=>i.remove())
document.querySelectorAll(`link[href="/_nuxt/@fs/__uno.css"]`).forEach(i=>i.remove())
```

</details>

### Reproduction

I tried recreating a minimal example but couldn't.

Essentially what my transformer is doing is looking for tokens and replacing them with that token prefixed with a variant group.
e.g. Changing all uses of `text-red` to `lg:text-red`.

`tokens.delete("text-red")` is causing the issue. If I don't remove the token, everything works fine but extra CSS is generated.

### System Info

Nuxt: 3.10.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RebeccaStevens** [comment] 2024-02-29 18:16
I'm no longer using this solution so closing for now. This is still probably a bug though.

**Comment by RebeccaStevens** [comment] 2024-02-29 18:18
Workaround solution for now:

```
if (config.envMode === "build") {
	// For some reason this fails in dev so only do it during build.
	tokens.delete(token);
}
```

**Comment by Simon-He95** [comment] 2024-05-15 03:15
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-05-15 03:15 UTC
