### ISSUE TITLE
[vite] Internal server error: Failed to resolve import "virtual:uno.css" from "src/main.ts". Does the file exist?

### ISSUE THREAD

**Issue by RAVER0306** [unocss/unocss#4249] opened 2024-11-05 06:41 UTC
### UnoCSS version

"unocss": "^0.63.6",

### Describe the bug

14:34:09 [vite] page reload src/main.ts
14:34:10 [vite] Pre-transform error: Failed to resolve import "virtual:uno.css" from "src/main.ts". Does the file exist?
14:34:10 [vite] Internal server error: Failed to resolve import "virtual:uno.css" from "src/main.ts". Does the file exist?

### Reproduction

Create a new Vite project.
Install UnoCSS.
Add virtual:uno.css in the main.ts or index.ts file.
Run the development server.

### System Info

Processor Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz 3.60 GHz
Onboard RAM 32.0 GB
Device ID 1D65A160-BB7C-457A-BD9E-73C211FA3493
Product ID 00330-80000-00000-AA773
System Type 64-bit operating system, x64-based processor
Pen and Touch No pen or touch input available for this display

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2024-11-05 06:52
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2024-11-05 06:52 UTC
