### ISSUE TITLE
VSCode extension autocomplete not working

### ISSUE THREAD

**Issue by hiovi** [unocss/unocss#3900] opened 2024-06-15 11:31 UTC
### UnoCSS version

v0.61.0

### Describe the bug

Autocomplete doesn't work in VSCode. I'm not sure if this is a bug or the feature hasn't been implemented yet.

### Reproduction

I have used both uno default preset as well as my own but couldn't get auto complete working. It does seem to work in the online playground though. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-06-15 16:46
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-06-15 16:46 UTC

**Comment by sanba-anass** [comment] 2024-06-28 21:32
i encouted the same issue today couldn't figure out why
