### ISSUE TITLE
failed to load icon for `vue key word: for, if, return, ...`

### ISSUE THREAD

**Issue by sweihub** [unocss/unocss#3908] opened 2024-06-18 04:21 UTC
### UnoCSS version

0.58.6

### Describe the bug

Hi, I have vue3 & unocss, why it complains of failure to load vue3 key words as icon such as `for`, `if`, `return`, `function`, ...

```
rendering chunks...
[unocss] failed to load icon "for"
[unocss] failed to load icon "i"
[unocss] failed to load icon "of"
[unocss] failed to load icon "if"
[unocss] failed to load icon "return"
[unocss] failed to load icon "true"
[unocss] failed to load icon "false"
[unocss] failed to load icon "function"
[unocss] failed to load icon "option"
```

### Reproduction

A simply vue3 & unocss

### System Info

ubuntu 22.04 LTS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-06-18 05:33
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-06-18 05:33 UTC
