### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by hbsjmsjwj** [unocss/unocss#2281] opened 2023-03-01 02:23 UTC
### UnoCSS version

"unocss": "^0.50.0",

### Describe the bug

![image](https://user-images.githubusercontent.com/45258156/222028188-ecb75d33-ab55-4f0a-ba9e-001fe9e9eef4.png)
我的依赖版本    
-------------------------------------------
"unocss": "^0.50.0",
 "@unocss/preset-uno": "^0.50.0",
    "@unocss/webpack": "^0.50.0",
--------------------------------------------
    "vue": "^3.2.11",
    "@vue/cli-service": "~4.5.0",
-------------------------------------------
    "ant-design-vue": "^3.2.4",
------------------------------------------
我加了cross-env NODE_OPTIONS=--max-old-space-size=10000 ，然后稍好一些，但是我ctrl+s多次(约10次)后，还是会内存溢出
"dev": "cross-env NODE_OPTIONS=--max-old-space-size=10000 vue-cli-service serve --open --port 9528"

### Reproduction

暂时没有

### System Info

window10
chrome
vue3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-03-01 16:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-01 16:31 UTC
