### ISSUE TITLE
How to use unocss in an external stylesheet

### ISSUE THREAD

**Issue by MuhammadM1998** [unocss/unocss#1295] opened 2022-07-18 20:33 UTC
Hello,

I'm using unocss for the first time in a nuxt 3 project and it works well in class, attribute and within `<style>` with the `@apply` directive.

I wanted to add general styles to my project (e.g `app-section` , etc..) so I created a stylesheet and added it to `nuxt.config` but using `@apply` doesnt' work! (the classes is highlighted by the vscode extension though).

I used traditional css to test if the file is working and it does.

**Comment by antfu** [comment] 2022-07-19 06:12
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-19 06:12 UTC
