### ISSUE TITLE
How do I customize a variable so that I can use it in UNOCSS

### ISSUE THREAD

**Issue by muchenfine** [unocss/unocss#1464] opened 2022-08-25 04:16 UTC
How do I customize a variable so that I can use it in UNOCSS

less :
   @primaryColor = '#000'

<div class="primayColor  bg-primaryColor">hello uno</div>

or 

custom variable

unocss :
<div class="primayColor  bg-primaryColor">hello uno</div>

**Comment by antfu** [comment] 2022-08-25 06:37
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-25 06:37 UTC

**Comment by chris-zhu** [comment] 2022-08-25 06:42
I guess you are finding [extend theme](https://github.com/unocss/unocss#extend-theme)
