### ISSUE TITLE
`VSCode` 插件无法提示预置类名

### ISSUE THREAD

**Issue by evanlong0926** [unocss/unocss#1983] opened 2022-12-11 05:18 UTC
插件无法对预置的 `windcss` 完整做出提示

**Comment by xijaja** [comment] 2022-12-13 06:06
我也尝试了，插件确实没有任何提示。

**Comment by evanlong0926** [comment] 2022-12-13 06:07
> 我也尝试了，插件确实没有任何提示。

我虽然没有证据，但它却是事实🥲

**Comment by antfu** [comment] 2022-12-13 09:29
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-12-13 09:29 UTC

**Comment by evanlong0926** [comment] 2022-12-16 14:27
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

Ok.

**Comment by heflyaway** [comment] 2023-02-17 07:36
.vscode > settings.json  add
{
   "editor.quickSuggestions": {
      "strings": true
   }
}
