### ISSUE TITLE
Theme color with number in name fails

### ISSUE THREAD

**Issue by FireMasterK** [unocss/unocss#1914] opened 2022-11-24 16:15 UTC
Example playground: [here](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIYHs5YE4C0AdviAIxnoB8AEgKZy5QDq%2BcIwA9OBFQFBA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwod6gBccADawRrCbFQwagC0fraoGmRIorbQQRqUyBqKALq5JN7kkrRUQcFFPvxSshDuAJSFPlUl9IzM7Jw8DU1wBUUwABaoIKhBXs1wqdBliJXNclDIAAwZAMQATACiAMwALHvLSfM%2Bi8gAjOs7AEJ7GwCsG8eTp9DIG%2Bt7%2B7j3W88vZx2nx%2BADYQXR-pMznt1gARAAcsK2WwAnJCFm97ustr8UQAxI69KFvEHY3BbPF4vbo15LADs63heOuuGu1xpcDO8MZ8Nwy1hhJOnLeKMZ5zo51w5w5Z3Oq00a1%2B8PFuBlb3OlwV1zxIPO4LVS3OHwVAvhdLpgpewsNQIVWxZ13h7KJGMNMIVdBuW15BouWK1e3hWzosPRCl64YMCnqBiAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by zyyv** [comment] 2022-11-25 02:18
Duplicate of #1894

**Closed by zyyv** 2022-11-25 02:18 UTC
