### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AsherSun** [unocss/unocss#1504] opened 2022-09-01 02:39 UTC
- Issue Type: `Performance`
- Extension Name: `unocss`
- Extension Version: `0.45.13`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.70.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/admin/AppData/Local/Temp/antfu.unocss-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by antfu** [comment] 2022-09-03 06:18
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-09-03 06:18 UTC
