### ISSUE TITLE
Webpack minimal setup not working

### ISSUE THREAD

**Issue by untoreh** [unocss/unocss#1311] opened 2022-07-21 07:40 UTC
```
❯ node --version
v16.5.0
```
```
❯ npm list @unocss/webpack
test@ /tmp/test
├── @unocss/webpack@0.44.5
└─┬ unocss@0.44.5
  └── @unocss/webpack@0.44.5 deduped
```
```
webpack: 5.73.0
webpack-cli: 4.10.0
webpack-dev-server not installed
```
I create an empty project:
`mkdir test && cd test`
Install unocss
`npm i -D unocss @unocss/webpack`
Create lib file `./app/main.js`
with content:
```js
import 'uno.css';
```
and `webpack.config.js`:
```js
const UnoCSS = require("unocss/webpack").default;

module.exports = {
  entry: ["./app/main.js"],
  mode: "development",
  plugins: [
    UnoCSS({
      /* options */
    }),
  ],
};
```
When I run `webpack build`, I get:
```
asset main.js 6.65 KiB [compared for emit] (name: main)
runtime modules 937 bytes 4 modules
cacheable modules 44 bytes
  ./app/main.js 18 bytes [built] [code generated]
  ./_virtual_/__uno.css 26 bytes [built] [code generated] [1 error]

ERROR in ./_virtual_/__uno.css 1:1
Module parse failed: Unexpected character '-' (1:1)
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/load.js
You may need an additional loader to handle the result of these loaders.
> #--unocss--{layer:__ALL__}
 @ ./app/main.js 1:0-17

webpack 5.73.0 compiled with 1 error in 108 ms
```

**Comment by zuramai** [comment] 2022-08-03 03:00
I got the same issue, have you solved it yet?

**Comment by untoreh** [comment] 2022-08-03 06:28
nope, I just switched to vite for the unocss stuff

**Comment by antfu** [comment] 2022-08-21 18:05
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2022-08-21 18:05 UTC
