### ISSUE TITLE
space-x and space-y utility classes are not being generated

### ISSUE THREAD

**Issue by therealokoro** [unocss/unocss#923] opened 2022-05-03 00:33 UTC
So I noticed that space-x and space-y utility classes are ignored when for some reason. These happens both in a class attribute and also when using them in attributify mode.

On checking the developers tool, all other classes have styles generated for them except for the aforementioned once, these includes both predefined once(eg. space-x-xs, space-y-md) and dynamic once(eg. space-x-10, space-y-4).

**Comment by zirbest** [comment] 2022-05-03 08:29
it's working normally in the [palyground](https://uno.antfu.me/play/?html=DwEwlgbgBAzgDgQwMYFMC0APNAmAfAKCimHgQDsoAjAczQDMBXJACxjASjgEYAGKMMgBsB6SoID2SANa5gAelJkCREogo16TVu069%2BQkWjGSZ8xQXngIBfKEixEqTDgyCoAWwAuaAKzLiilS0AE4oILp8AsJkohLSsgpq-qrkQWih4dyRBjFGcaaJ5BZyVrhAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdOwaqgXDBegD0AHomZpYKADrIANQAlBYKAHQpACRhDgq6dsgOWMIgqP6hjlDCAO4Ayqg2zOZQDiZQnlgwDU0tDgBuwlDAwl0AEqPINlCsDjAAFqhlZMlwALwAfIiVzlisLqjpyMBQCoPDozATWFOoM8mVnjD0UFiqAAZZCCVl5AA%2BcC%2ByDCACZ-oCENV6o1UM1oOCvu1Ot0YXCoAiEOcRuNJtNWLoAAy%2BdIgYQwZiLdFwAFfBZLQ4AI08wgA1pBsDBWOlWCBSO8QoZBaFSL5ggZRaRkkA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by antfu** [comment] 2022-05-03 17:08
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-03 17:08 UTC

**Comment by therealokoro** [comment] 2022-05-03 20:35
Alright so a simple reproduction of the issue would look as follows.

```vue
<ul class="flex space-x-3 font-semibold">
	  <li v-for="(item, index) in navLinks" :key="index">
	  		<nuxt-link class="transition hover:c-accent-200" :to="item.link">
					{{ item.label }}
			</nuxt-link>
	  </li>
</ul>
```

Notice the space-x-3 class on the `ul` element which is suppose to put a horizontal margin between all `li` items but doesn't

Here's a screenshot of the devtool

![image](https://user-images.githubusercontent.com/41494675/166561252-f1312d7c-f9b0-472c-9271-a1be099ed757.png)

You would notice that no styling was generated for the space-x-3 class and thus making the elements squashed up together.

I think its worth noting that i am using this with vitesse-nuxt template. Thanks 😊

**Comment by therealokoro** [comment] 2022-05-03 20:36
> it's working normally in the [palyground](https://uno.antfu.me/play/?html=DwEwlgbgBAzgDgQwMYFMC0APNAmAfAKCimHgQDsoAjAczQDMBXJACxjASjgEYAGKMMgBsB6SoID2SANa5gAelJkCREogo16TVu069%2BQkWjGSZ8xQXngIBfKEixEqTDgyCoAWwAuaAKzLiilS0AE4oILp8AsJkohLSsgpq-qrkQWih4dyRBjFGcaaJ5BZyVrhAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdOwaqgXDBegD0AHomZpYKADrIANQAlBYKAHQpACRhDgq6dsgOWMIgqP6hjlDCAO4Ayqg2zOZQDiZQnlgwDU0tDgBuwlDAwl0AEqPINlCsDjAAFqhlZMlwALwAfIiVzlisLqjpyMBQCoPDozATWFOoM8mVnjD0UFiqAAZZCCVl5AA%2BcC%2ByDCACZ-oCENV6o1UM1oOCvu1Ot0YXCoAiEOcRuNJtNWLoAAy%2BdIgYQwZiLdFwAFfBZLQ4AI08wgA1pBsDBWOlWCBSO8QoZBaFSL5ggZRaRkkA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

Yeah i noticed, don't know why it isn't working locally ☹️

**Comment by chu121su12** [comment] 2022-05-06 23:29
divide and space rules are available in preset-wind/uno. please check if you are using only preset-mini

**Comment by therealokoro** [comment] 2022-05-07 20:12
> divide and space rules are available in preset-wind/uno. please check if you are using only preset-mini

@chu121su12 so are you saying that it doesn't come with the default presetUno(), because that's what is set by default in the vitesse-nuxt template by @antfu

**Comment by therealokoro** [comment] 2022-05-07 23:59
@chu121su12 so after replacing `presetUno()` with `presetMini()` it worked. Thanks mate 😌

**Comment by folamy** [comment] 2022-05-22 18:10
This was really helpful
thanks @therealokoro!

**Comment by fernandolguevara** [comment] 2022-07-27 21:11
@antfu for reference, in my case the issue was caused if I specify a configuration object on the `UnoCssPlugin` function, removing it fixed my issue, btw I'm using svelte-kit 

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/969516/181371811-9b54d28f-ea0d-4ea7-853f-ff28fc7497bd.png">

bug:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/969516/181372976-f425593c-19ee-4f38-8da8-a4a567ffc794.png">

fixed:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/969516/181372849-1425e128-4596-40be-87ad-826dfdb316c8.png">

**Comment by fernandolguevara** [comment] 2022-08-08 21:54
@antfu  Do you need anything else to reopen this issue?
