### ISSUE TITLE
uniapp 使用rpx时打包无法转成rem，但WindiCSS可以。。

### ISSUE THREAD

**Issue by liangei** [unocss/unocss#798] opened 2022-04-04 16:25 UTC
各位大佬有什么方案能解决吗？

**Comment by antfu** [comment] 2022-05-02 14:46
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-02 14:46 UTC
