### ISSUE TITLE
`@unocss/postcss` The style.css will call the postcss processor, but unocss doesn't convert @apply correctly

### ISSUE THREAD

**Issue by nexmoe** [unocss/unocss#3429] opened 2023-12-07 13:42 UTC
### UnoCSS version

0.58.0

### Describe the bug

In the unbuild + mkdist environment, unocss cannot parse `@apply` of style in vue, but can compile style.css normally, and tailwind can be used normally

## Unocss

`@apply` using unocss in vue

![image](https://github.com/unocss/unocss/assets/16796652/f7bd667e-c9d2-4365-9170-3ee81b296191)

`@apply` using unocss in style.css

![image](https://github.com/unocss/unocss/assets/16796652/9cc01ee1-2bae-43d6-89fe-3ce5be67095a)

## Tailwind

`@apply` using Tailwind in vue

![image](https://github.com/unocss/unocss/assets/16796652/bbc9ae40-c5da-4a3a-b833-18fae039e00a)

The expectation should be as follows

![568dff94e376f26081078aebe1bea879](https://github.com/unocss/unocss/assets/16796652/83d16c5f-e7db-424f-95ac-99769b99fc6f)

### Reproduction

```
// build.config.ts
import { defineBuildConfig } from 'unbuild'
import unocss from 'unocss/postcss'
// import tailwindcss from 'tailwindcss'

export default defineBuildConfig({
    entries: [
        { builder: 'mkdist', input: './src/' },
        { builder: 'mkdist', input: './src/', format: 'cjs', ext: 'cjs' }
    ],
    clean: true,
    declaration: true,
    sourcemap: true,
    externals: ['vue'],
    hooks: {
        'mkdist:entry:options': (a, b, options) => {
            options.postcss = {
                ...options.postcss,
                plugins: [
                    unocss()
                    // tailwindcss()
                ]
            }
        }
    }
})

```

```
// style.css
@unocss all;
```

### System Info

macOS 14, m2 chip
node v19.9.0
unbuild v2.0.0
mkdist v1.3.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by greenhat616** [comment] 2024-02-06 04:24
not stale

**Comment by Simon-He95** [comment] 2024-06-13 06:59
Due to the lack of a minimal reproducible demo, I will temporarily close this issue. Please feel free to open it when a reproducible demo is provided.

**Closed by Simon-He95** 2024-06-13 06:59 UTC
