### ISSUE TITLE
VSCODE: unocss extension not suggest 

### ISSUE THREAD

**Issue by minologyVN** [unocss/unocss#4336] opened 2024-12-18 15:29 UTC
### UnoCSS version

0.65.1

### Describe the bug

Previously I got suggestions from this extension. But now when I'm back, it does not suggest any more.
For example: I type "tex", It does not show anything

### Reproduction

<img width="959" alt="image" src="https://github.com/user-attachments/assets/274a26ac-b4ed-42f4-b296-8322fcc1716d" />

### System Info

MacOS Ventura 13.5 (M2)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2024-12-19 14:24
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by zyyv** 2024-12-19 14:24 UTC
Labels: needs reproduction

**Comment by minologyVN** [comment] 2024-12-25 14:16
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

I found in the UnoCSS log that in my uno.config.ts had imported with the alias path 
```
import { colors } from '@/themes/color';
```
and got this error
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/3f6d93d1-f69e-450f-9b66-cad7602b1cad" />
I remove the import and the extension worked fine!

Is there any workaround that I can still use the alias import?
