### ISSUE TITLE
Can't resolve 'uno.css'

### ISSUE THREAD

**Issue by ZGH0717** [unocss/unocss#1906] opened 2022-11-23 10:15 UTC
把 examples/vue-cli5 package.json 改为如下图
![image](https://user-images.githubusercontent.com/20718604/203521422-3cffe127-b5a4-435a-b7e5-94f0c431f94c.png)

然后运行起来会报 
![image](https://user-images.githubusercontent.com/20718604/203521620-c2bbe739-4acf-453b-90c8-5863377c8758.png)

**Comment by deleonio** [comment] 2022-11-23 14:45
We have the same magic bug - over night.

https://github.com/public-ui/kolibri/actions/runs/3532183631/jobs/5926320169

<img width="817" alt="image" src="https://user-images.githubusercontent.com/6279703/203575622-b7161cb2-8c9c-4894-86f7-8bba9cc39c9b.png">

**Comment by deleonio** [comment] 2022-11-23 14:58
I think them should be a wildcard version number in the dep tree!

We can go backwards and all Green Pipe Runs - become Broken.

:-(

**Comment by sudongyuer** [comment] 2022-11-24 03:47
Do you think is this ` "@rollup/pluginutils": "^5.0.1"` case this issue ?

**Comment by azaleta** [comment] 2022-11-24 06:04
Nothing wrong.
![image](https://user-images.githubusercontent.com/22554452/203706111-c9a680d9-f43d-44c0-a5aa-c0c62c4b386b.png)

**Comment by ZGH0717** [comment] 2022-11-24 06:23
@azaleta 感觉是内部依赖别的第三包的问题，我昨天本地启动不行，一直构建也不行。
![image](https://user-images.githubusercontent.com/20718604/203708993-f1c515a1-1a16-48e9-9114-b8d92d6a2e1a.png)
刚看到你回复，我重新尝试了下构建又可以了。
![image](https://user-images.githubusercontent.com/20718604/203708825-d97d80be-49c0-4257-8b3c-4557c21ac5a2.png)

**Comment by deleonio** [comment] 2022-11-24 11:16
> Do you think is this ` "@rollup/pluginutils": "^5.0.1"` cause this issue ?

**No**, that was only a sample. I think it would be much resilient to make all dep versions fix.

**Comment by MellowCo** [comment] 2022-11-24 14:11
It may be a problem with this `enhanced-resolve`  [webpack/enhanced-resolve#363](https://github.com/webpack/enhanced-resolve/issues/363)，now it's fix in [webpack/enhanced-resolve#364](https://github.com/webpack/enhanced-resolve/pull/364), 

delete .lock and reInsall 

yesterdya I have the same problem in https://github.com/NervJS/taro/issues/12869,

**Comment by antfu** [comment] 2022-11-24 16:35
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-11-24 16:35 UTC
Labels: bug, webpack

**Comment by tong822218** [comment] 2023-10-12 08:05
解决了吗，我也遇到了这个问题
