### ISSUE TITLE
async Config Import Fails with ESM Error in VSCode Extension (0.65.1)

### ISSUE THREAD

**Issue by marco-land** [unocss/unocss#4314] opened 2024-12-06 11:06 UTC
### UnoCSS version

0.65.1

### Describe the bug

I am trying to fetch some theme variables from the backend and use them in an async preset. While this works during local development (haven’t tested in production yet), the VSCode extension fails to handle the imports.

In version `0.64.1`, no error is thrown, but the config is not recognized if it includes an async fetch. With version `0.65.0` & `0.65.1`, I encounter the following error when loading the configuration:

```bash
🛠 Resolving config for /Users/xyz/Documents/GitHub/proj/web
⚠️ Error on loading config. Config directory: /Users/xyz/Documents/GitHub/proj/web
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xyz/Documents/GitHub/proj/web/node_modules/.pnpm/@sanity+client@6.24.1/node_modules/@sanity/client/dist/index.js from /Users/xyz/.vscode/extensions/antfu.unocss-0.65.0/dist/jiti-KGMJ66AV.cjs not supported.
Instead change the require of index.js in /Users/xyz/.vscode/extensions/antfu.unocss-0.65.0/dist/jiti-KGMJ66AV.cjs to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/xyz/.vscode/extensions/sanity-io.vscode-sanity-0.2.1/node_modules/ts-node/dist/index.js:851:20)
    at c._load (node:electron/js2c/node_init:2:16955)
    at e._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10900)
    at t._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
    at i._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
    at Module.require (/Users/xyz/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:195:34657)
    at /Users/xyz/.vscode/extensions/antfu.unocss-0.65.0/dist/jiti-KGMJ66AV.cjs:28181:82
    at async import (/Users/xyz/.vscode/extensions/antfu.unocss-0.65.0/dist/jiti-KGMJ66AV.cjs:2898:202)
    at async /Users/xyz/Documents/GitHub/proj/web/uno.config.ts:1:195
    at async Function.import (/Users/xyz/.vscode/extensions/antfu.unocss-0.65.0/dist/jiti-KGMJ66AV.cjs:2898:202)
    at async Object.loader (/Users/xyz/.vscode/extensions/antfu.unocss-0.65.0/dist/jiti-KGMJ66AV.cjs:28203:15)
🗂️ Enabled context: [none]
```

### Reproduction

```ts
import { createClient } from '@sanity/client'
import { defineConfig, presetUno } from 'unocss'
import { SITE_COLORS_QUERY } from './shared/queries/sanity.queries'

export default defineConfig({
  presets: [
    presetUno(),
    async () => {
      /**
       * ! Prefetch colors from the backend
       */
      const client = createClient({
        projectId: process.env.NUXT_SANITY_PROJECT_ID!,
        dataset: process.env.NUXT_SANITY_DATASET!,
        useCdn: false,
        apiVersion: process.env.NUXT_SANITY_API_VERSION || '2024-12-03',
      })
      const {
        site,
        page,
        primary,
        secondary,
      } = await client.fetch(SITE_COLORS_QUERY)
      return {
        theme: {
          colors: {
            brand: {
              site: {
                bg: site?.background || '#1a1a1a',
                text: site?.foreground || '#ffffff',
              },
              page: {
                bg: page?.background || '#cbcbcb',
                text: page?.foreground || '#000000',
              },
              primary: {
                bg: primary?.background || '#000000',
                text: primary?.foreground || '#ffffff',
              },
              secondary: {
                bg: secondary?.background || '#ffffff',
                text: secondary?.foreground || '#000000',
              },
            },
          },
        },
      }
    },
  ],
})

```

### Validations

- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).

**Comment by antfu** [comment] 2024-12-10 05:32
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-12-10 05:32 UTC
Labels: needs reproduction
