### ISSUE TITLE
vue-cli4 开启css.extract，图片丢失

### ISSUE THREAD

**Issue by lianghang1** [unocss/unocss#2759] opened 2023-06-12 14:12 UTC
### UnoCSS version

webpack4

### Describe the bug

vue-cli4 使用unocss，开启css.extract配置后，vue 页面css背景图片无法使用。有不开启css.extract的使用方式吗？

### Reproduction

css: {
  extract: {
   filename: "[name].[hash:9].css",
  },
 },

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment] 2023-06-12 14:17
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2023-06-12 14:17 UTC

**Comment by mdxiaohu** [comment] 2023-09-20 13:13
@zyyv I also encountered this problem.
You can use the example on the official website Vue cli4 to delete the css.extract configuration.
set up .
background: url("~@/assets/headerBg.svg")
Can be reproduced .

**Comment by moliyu** [comment] 2023-11-07 07:25
```
{
     filename: '[name].css',
     // add this line,it will work
     chunkFilename: '[name].css',
 }
```
