### ISSUE TITLE
[extension]Initializing JS/TS language features forever if unocss is not installed

### ISSUE THREAD

**Issue by QQCif** [unocss/unocss#1432] opened 2022-08-17 13:22 UTC
Type: <b>Bug</b>

VSC stuck at Initializing JS/TS language features. After running extension bisect, seems caused by unocss extension. VSC works fine if I disable unocss extension. The folder opened in VSC is a vite react typescript project without unocss installed. There's also a file named `__unconfig_vite.config.ts` generated under project root.

Extension version: 0.45.7
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (2.85GB free)|
|Process Argv|--crash-reporter-id c347f436-4030-41e1-ab10-e62718e0a066|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by antfu** [comment] 2022-08-21 18:03
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-21 18:03 UTC
Labels: vscode

**Comment by QQCif** [comment] 2022-08-22 14:06
Here's a [minimal reproduction](https://github.com/QQCif/unocss-troubleshooting) I just created for this issue.
