### ISSUE TITLE
[plugin:unocss:transformers:pre] Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by renzhenqi** [unocss/unocss#2328] opened 2023-03-07 21:41 UTC
### UnoCSS version

0.48.0

### Describe the bug

This is all.
05:38:55.664 uni-app 有新版本发布，请执行 `npx @dcloudio/uvm alpha` 更新，更新日志详见：https://update.dcloud.net.cn/hbuilderx/changelog/3.7.6.20230227-alpha.html
05:38:57.075 [plugin:unocss:transformers:pre] Cannot read properties of undefined (reading 'join')
05:38:57.075 at pages/index/index.vue:1:0

### Reproduction

05:38:55.664 uni-app 有新版本发布，请执行 `npx @dcloudio/uvm alpha` 更新，更新日志详见：https://update.dcloud.net.cn/hbuilderx/changelog/3.7.6.20230227-alpha.html
05:38:57.075 [plugin:unocss:transformers:pre] Cannot read properties of undefined (reading 'join')
05:38:57.075 at pages/index/index.vue:1:0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-03-07 22:12
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-07 22:12 UTC
