### ISSUE TITLE
dynamic safelist or how to change config

### ISSUE THREAD

**Issue by zh-neng** [unocss/unocss#2775] opened 2023-06-18 15:31 UTC
### Clear and concise description of the problem

I want to base  vite-plugin-pages   meta.icon   dynamic generate the icon,    so  I need to add it to safelist dynamicly.   I want to  know  how to  chang  unocss config  and apply

### Suggested solution

![image](https://github.com/unocss/unocss/assets/24434147/35f6ee42-b311-48b1-ab56-c80486759b83)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment] 2023-06-19 08:20
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-06-19 08:20 UTC
