### ISSUE TITLE
[vite] hot updated: /__uno.css

### ISSUE THREAD

**Issue by shiwanjun1995** [unocss/unocss#856] opened 2022-04-21 14:55 UTC
## main.js
import 'uno.css'
## result
chrome console tab
25285client.ts:352 [vite] hot updated: /__uno.css
## why?
<img width="566" alt="截屏2022-04-21 下午10 54 17" src="https://user-images.githubusercontent.com/38515714/164486018-cce829e8-276c-4529-aa45-c2cbe4360392.png">

**Comment by antfu** [comment] 2022-04-21 14:59
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-04-21 14:59 UTC

**Comment by izhaoqing** [comment] 2022-06-08 06:20
控制台一直输出 [vite] hot updated: /__uno.css，我这里也遇到了这个问题。

**Comment by coderzhaoziwei** [comment] 2022-07-14 02:42
我也遇到了这个问题，热更新好像是陷入了某个死循环停不下来，CPU开始升温。具体原因暂时没找到，公司项目无法提供出来。如果我有办法复现这个问题了，我会提交过来。

---

I also encountered this problem. The hot update seems to be stuck in an infinite loop and cannot stop, and the CPU starts to heat up.
The specific reason has not been found for the time being, and the company's project cannot be provided.
If I have a way to reproduce this problem, I will submit it.
(translate by google)

**Comment by zgsgs** [comment] 2022-07-19 10:28
我遇到的场景是: 在 `npm run dev` 运行环境下, 当使用 `git pull` 命令更新代码时会出现这类问题.

**Comment by astronautchen** [comment] 2022-08-17 06:36
I also encountered this problem

**Comment by Dragonlord1005** [comment] 2022-12-11 08:38
[Astro-boi](https://github.com/Dragonlord1005/astro-boi/tree/revamp-projects) happening on revamp project branch

**Comment by kunjinW** [comment] 2024-08-27 06:31
我也遇到了这个问题
