### ISSUE TITLE
Vite + UniApp Build Error

### ISSUE THREAD

**Issue by ModyQyW** [unocss/unocss#1999] opened 2022-12-14 14:34 UTC
Hi. I am facing problems when I am using `vite`, `uni-app` and `unocss`.

```shell
npx degit dcloudio/uni-preset-vue#vite-ts playground
cd playground
echo 'shamefully-hoist=true' > .npmrc
npx @dcloudio/uvm alpha # choose pnpm here
pnpm install unocss -D
```

```ts
// unocss.config.ts
import { defineConfig } from "unocss";

export default defineConfig({
  presets: [],
});
```

```ts
// src/main.ts
import { createSSRApp } from "vue";
import App from "./App.vue";
import "uno.css";
export function createApp() {
  const app = createSSRApp(App);
  return {
    app,
  };
}
```

```ts
// vite.config.ts
import { defineConfig } from "vite";
import unocss from "unocss/vite";
import uni from "@dcloudio/vite-plugin-uni";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [unocss(), uni()],
});
```

```shell
pnpm run dev:mp-weixin
```

There should be a `dist/dev/mp-weixin/app.wxss`. But I get `dist/dev/mp-weixin/app.css`.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/31850793/207626866-180b73d4-eeed-4343-8635-9f7a5bd3d228.png">

```shell
➜  [playground] node -v                
v18.12.0
➜  [playground] npm -v                                            
9.2.0
➜  [playground] pnpm -v           
7.18.2
```

With `unocss@0.46.5`, everything is fine. But with `unocss@0.47`, `app.wxss` is missing.

Is it a expected behavior? If so, how can I get `app.wxss` back? Thanks.

**Comment by sibbng** [comment] 2022-12-14 23:17
Could be related to Vite 4 upgrade. Does it work with `unocss@0.47.5`?

I couldn't find the source code of `@dcloudio/vite-plugin-uni` package. Do you know where is it?

**Comment by ModyQyW** [comment] 2022-12-15 01:54
@sibbng  Thanks for your reply.

> Could be related to Vite 4 upgrade.

I am using vite 3.2.5. Maybe you mean related to unocss upgrade for vite 4?

> Does it work with unocss@0.47.5?

No. Doesn't work with unocss v0.47.0, v0.47.5 and v0.47.6. But works with unocss v0.46.5.

> I couldn't find the source code of @dcloudio/vite-plugin-uni package. Do you know where is it?

I don't know where it is, either. Sorry about that.

**Comment by ModyQyW** [comment] 2022-12-15 02:07
I just created a repo following the steps. You can try on it.

<https://github.com/ModyQyW/playground>

**Comment by sibbng** [comment] 2022-12-15 07:24
I looked at it but, couldn't find the source problem. Probably it's caused by #1926. But I don't think it's something we have to fix. 

I believe this could be fixed on uni-app side by just changing the priority of a plugin. If you can show them #1926, they may know where the fix might be.

**Comment by ModyQyW** [comment] 2022-12-15 07:31
I have linked the issue. Can you please keep this issue open until the problem is solved? Thanks!

**Comment by yckbilly1929** [comment] 2022-12-31 12:33
0.46.5 to 0.47.0 also breaks my build (a react SPA project). Below is the diff before and after, running unocss cli:
![Screenshot 2022-12-31 at 20 28 25](https://user-images.githubusercontent.com/12884758/210136836-0290344c-c9cd-4ffc-895c-ae276e382db6.jpg)

and the only places with the word container:
![Screenshot 2022-12-31 at 20 29 31](https://user-images.githubusercontent.com/12884758/210136840-0d22a659-5d21-40ff-a77f-08fbfde8b820.jpg)

**Comment by ModyQyW** [comment] 2022-12-31 12:35
@yckbilly1929 You should open another issue for this. This issue focuses on uni-app and is solved. I am closing it.

**Comment by yckbilly1929** [comment] 2022-12-31 12:36
> @yckbilly1929 You should open another issue for this. This issue focuses on uni-app and is solved. I am closing it.

no problem

**Closed** 2022-12-31 12:35 UTC
