### ISSUE TITLE
@unocss/cli will exit when encountering text-shadow

### ISSUE THREAD

**Issue by hi-noikiy** [unocss/unocss#4136] opened 2024-09-11 01:43 UTC
### UnoCSS version

0.61.0

### Describe the bug

When I use unocss to @process/cli a vue file, if the style of the vue file contains text-shadow, it will exit abnormally.

### Reproduction

![image](https://github.com/user-attachments/assets/ce0bf0fd-7c16-4335-baa1-bb466a29f272)

### System Info

node:14.21.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-noikiy** [comment] 2024-09-11 01:50
but 0.60.0 is ok

**Comment by Simon-He95** [comment] 2024-09-11 05:53
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by Simon-He95** 2024-09-11 05:53 UTC
