### ISSUE TITLE
自定义背景颜色、字体颜色、边框颜色没有代码提示 

### ISSUE THREAD

**Issue by thikiiii** [unocss/unocss#4097] opened 2024-08-23 08:57 UTC
### UnoCSS version

^0.62.2

### Describe the bug

` uno.config.ts`中配置自定义主题后，使用的时候没有代码提示
```ts
// uno.config.ts
import { defineConfig, presetUno, transformerDirectives } from 'unocss'
import { Theme } from '@unocss/preset-uno'

export default defineConfig<Theme>({
    content: {
        pipeline: {
            exclude: [ 'node_modules', 'dist' ],
        }
    },
    transformers: [
        transformerDirectives()
    ],
    presets: [
        presetUno(),
    ],
    extendTheme: (theme)=>{
        return {
            ...theme,
            colors: {
                ...theme.colors,
                'primary': 'red',
            },
            textColor: {
                ...theme.textColor,
                'main': 'red',
            },
            backgroundColor: {
                ...theme.backgroundColor,
                'main': '#445cdc',
            },
            borderColor: {
                ...theme.borderColor,
                'main': 'red',
            },
        }
    },
})
```

### Reproduction

比如给一个`div`的 `class` 输入`bg-main`的时候没有代码提示，输入`bg-primary`的时候有代码提示

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2024-08-23 09:53
You provided too little information and did not post your custom settings.

**Comment by thikiiii** [comment] 2024-08-27 02:57
和颜色相关的都没有代码提示，除了`colors`

**Comment by antfu** [comment] 2024-08-27 10:50
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-08-27 10:50 UTC
