### ISSUE TITLE
taro h5 开发场景中 unocss 部分代码失效

### ISSUE THREAD

**Issue by JamesMonges** [unocss/unocss#3240] opened 2023-10-16 06:07 UTC
### UnoCSS version

0.56.5

### Describe the bug

我写了一个页面需要在小程序和h5都运行，目前小程序的样式是OK的，但是h5的部分样式会丢失，如下所示失效代码为“w-[27.5rem]  p-[0.5rem]”，代码和运行效果如下：
h5运行效果：
<img width="1680" alt="image" src="https://github.com/unocss/unocss/assets/49359382/e34c57ee-6c53-4ac1-bbc9-76d02d82f073">
小程序运行效果：
<img width="1450" alt="image" src="https://github.com/unocss/unocss/assets/49359382/6e3e13bc-cf35-4c4d-94d8-5a02644787fb">
<img width="762" alt="image" src="https://github.com/unocss/unocss/assets/49359382/917882e4-ed93-41a9-a7c3-9261874c927e">
在上面的展示中其实按钮的颜色也失效了，篇幅有限，就只标注了w-[] 和p-p[]

### Reproduction

参考 bug中的描述

### System Info

开发环境如下：
 "devDependencies": {
    "@babel/core": "^7.8.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.6.17",
    "@tarojs/plugin-html": "^3.6.17",
    "@tarojs/taro-loader": "3.6.17",
    "@tarojs/test-utils-react": "^0.1.1",
    "@tarojs/webpack5-runner": "3.6.17",
    "@types/jest": "^29.3.1",
    "@types/node": "^18.15.11",
    "@types/react": "^18.0.0",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^6.2.0",
    "@typescript-eslint/parser": "^6.2.0",
    "@unocss/webpack": "^0.56.5",
    "babel-preset-taro": "3.6.17",
    "eslint": "^8.12.0",
    "eslint-config-plugin": "^1.0.11",
    "eslint-config-taro": "3.6.17",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest": "^29.3.1",
    "jest-environment-jsdom": "^29.5.0",
    "postcss": "^8.4.18",
    "prettier": "^3.0.3",
    "react-refresh": "^0.11.0",
    "stylelint": "^14.4.0",
    "ts-node": "^10.9.1",
    "tsconfig-paths-webpack-plugin": "^4.0.1",
    "typescript": "^5.1.0",
    "unocss": "^0.56.5",
    "unocss-applet": "^0.5.5",
    "webpack": "5.78.0"
  }

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment] 2023-10-16 06:22
Please provide a minimum demo that can reproduce the problem so that we can help you solve the problem faster.

**Comment by antfu** [comment] 2023-10-16 07:16
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-16 07:16 UTC
