### ISSUE TITLE
transformerVariantGroup not working with production build in NextJS 13 App Router

### ISSUE THREAD

**Issue by quangkhaidam93** [unocss/unocss#3407] opened 2023-12-01 09:16 UTC
### UnoCSS version

0.56.4

### Describe the bug

With `webpack` config follow this article https://unocss.dev/integrations/next

Everything work perfectly in development mode but when I build and start Next server (tested both in local and server) → `transformerVariantGroup` is not working. Particularly group breakpoint such as `lg:(flex-row pb-0px bg-white)` does not work → Currently I temporarily convert into `lg:flex-row lg:pb-0px lg:bg-white` to work around. 

This feature absolutely make dx better but not working in production build is terrible.

Note: I have config target in `tsconfig` to "ES2015"

### Reproduction

Provide later if needed

### System Info

Device: Macbook Pro M1 2020
OS: macOS Sonoma 14.1.1
NextJS version: 13.5.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by champ7champ** [comment] 2023-12-02 00:15
same problem, only in nuxt 3 (>3.5.2)
I want to write lg:(mt-4 pl-4 pb-4)
and get lg:mt-4 lg:pl-4 lg:pb-4
The problem is only with breakpoints

Grid-cols-[200px,auto] etc doesn't work either
Is this being resolved? Or is there a way to solve this?

**Comment by greenhat616** [comment] 2023-12-07 13:14
https://github.com/unocss/unocss/issues/3198

**Comment by quangkhaidam93** [comment] 2023-12-12 04:38
> #3198

Nice. It works perfectly. But is this a right solution or just work around? Thank a lot.

**Comment by greenhat616** [comment] 2024-02-10 07:41
Not stale

**Comment by Simon-He95** [comment] 2024-06-13 06:56
Due to the lack of a minimal reproducible demo, I will temporarily close this issue. Please feel free to open it when a reproducible demo is provided.

**Closed by Simon-He95** 2024-06-13 06:56 UTC
